# Generated by Django 5.2.8 on 2025-11-08 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_sistema', models.CharField(default='Gestão de Estoque', max_length=200, verbose_name='Nome do Sistema')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('email_contato', models.EmailField(blank=True, max_length=254, verbose_name='Email de Contato')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('endereco', models.TextField(blank=True, verbose_name='Endereço')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='configuracao/', verbose_name='Logo')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='configuracao/', verbose_name='Favicon')),
                ('cor_primaria', models.CharField(default='#0ea5e9', help_text='Cor primária do sistema (hex)', max_length=7, verbose_name='Cor Primária')),
                ('cor_secundaria', models.CharField(default='#0284c7', help_text='Cor secundária do sistema (hex)', max_length=7, verbose_name='Cor Secundária')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('manutencao_ativa', models.BooleanField(default=False, help_text='Quando ativo, o sistema exibe mensagem de manutenção', verbose_name='Modo Manutenção')),
                ('mensagem_manutencao', models.TextField(blank=True, default='Sistema em manutenção. Voltaremos em breve.', verbose_name='Mensagem de Manutenção')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
                'verbose_name_plural': 'Configurações do Sistema',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INFO', 'Informação'), ('WARNING', 'Aviso'), ('ERROR', 'Erro'), ('CRITICAL', 'Crítico'), ('SUCCESS', 'Sucesso')], default='INFO', max_length=10, verbose_name='Tipo')),
                ('acao', models.CharField(max_length=200, verbose_name='Ação')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
                'ordering': ['-criado_em'],
            },
        ),
    ]
