# Generated by Django 5.1.11 on 2025-10-29 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0008_alter_intranethomepage_body_alter_intranetpage_body'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IntranetPage',
        ),
    ]
