# Generated by Django 5.1.13 on 2025-11-10 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0011_alter_intranethomepage_body_and_more'),
        ('intranet', '0013_alter_intranethomepage_widgets'),
    ]

    operations = [
    ]
