# Generated by Django 5.1.11 on 2025-11-13 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0012_alter_intranethomepage_descricao'),
        ('intranet', '0015_alter_intranethomepage_body_and_more'),
    ]

    operations = [
    ]
