# Generated by Django 5.1.11 on 2025-11-19 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0013_alter_intranethomepage_body'),
        ('intranet', '0018_alter_intranethomepage_body_and_more'),
    ]

    operations = [
    ]
