# Generated by Django 5.1.13 on 2025-10-31 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_alter_eventospage_body'),
        ('eventos', '0002_remove_eventospage_images_and_more'),
    ]

    operations = [
    ]
