# Generated by Django 5.1.13 on 2025-11-07 15:23

import datetime
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_merge_20251031_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventospage',
            name='arquivos',
            field=wagtail.fields.StreamField([('arquivo', 0)], blank=True, block_lookup={0: ('blocks.models.EspecificDocumentChooserBlock', (), {'label': 'Arquivos', 'required': True})}, null=True, verbose_name='Arquivos'),
        ),
        migrations.AlterField(
            model_name='eventospage',
            name='body_migrated',
            field=models.TextField(blank=True, help_text='Usado apenas para conteúdo do antigo site Plone.', null=True, verbose_name='Conteúdo migrado do Plone'),
        ),
        migrations.AlterField(
            model_name='eventospage',
            name='data_publicacao',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Data de publicação'),
        ),
        migrations.AlterField(
            model_name='eventospage',
            name='nao_exibir_lista_de_arquivos',
            field=models.BooleanField(default=False, help_text='Marque para ocultar a lista de arquivos.', verbose_name='Não exibir lista de arquivos'),
        ),
        migrations.AlterField(
            model_name='eventospage',
            name='plone_node_id',
            field=models.TextField(blank=True, db_index=True, help_text='ID do nó no Plone, usado para identificar a página migrada.', null=True, unique=True, verbose_name='ID Plone'),
        ),
        migrations.AlterField(
            model_name='eventospage',
            name='sensivel_periodo_eleitoral',
            field=models.BooleanField(default=False, help_text='Marque se este conteúdo deve ser ocultado durante o período eleitoral.', verbose_name='Sensível ao período eleitoral'),
        ),
    ]
