# Generated by Django 5.1.11 on 2025-11-13 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_alter_eventospage_arquivos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventospage',
            name='subtitle',
        ),
    ]
