# Generated by Django 5.1.14 on 2025-11-24 19:31

import django.db.models.deletion
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtailimages', '0027_image_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_habilitada', models.BooleanField(default=False, help_text='Marque esta opção para ativar a busca de conteúdo de um portal externo.', verbose_name='Habilitar Integração via API')),
                ('api_url', models.URLField(blank=True, help_text='URL base da API do portal de conteúdo externo. Ex:https://paraiba.pb.gov.br/', verbose_name='URL da API Externa')),
                ('api_usuario', models.CharField(blank=True, help_text='Usuário para autenticação na API externa.', max_length=255, verbose_name='Usuário da API')),
                ('api_senha', models.CharField(blank=True, help_text='Senha para autenticação na API externa. Cuidado: será armazenada como texto plano.', max_length=255, verbose_name='Senha da API')),
                ('puxar_noticias', models.BooleanField(default=False, help_text='Ativar para buscar notícias do portal externo.', verbose_name='Consumir Notícias')),
                ('tags_noticias', models.CharField(blank=True, help_text="Separar tags por vírgula. Ex: 'geral, importante'. Deixe em branco para buscar todas.", max_length=255, verbose_name='Tags para filtrar Notícias')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Configurações de Conteúdo Externo',
            },
        ),
        migrations.CreateModel(
            name='ConsentimentoLGPD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aceite_coleta_dados', models.BooleanField(default=False, verbose_name='Aceite de Coleta de Dados')),
                ('aceite_analise_ia', models.BooleanField(default=False, verbose_name='Aceite de Análise por IA')),
                ('aceite_pesquisa_anonima', models.BooleanField(default=False, verbose_name='Aceite de Uso em Pesquisa Anônima')),
                ('aceite_compartilhamento_profissionais', models.BooleanField(default=False, verbose_name='Aceite de Compartilhamento com Profissionais')),
                ('data_aceite', models.DateTimeField(auto_now_add=True, verbose_name='Data do Aceite')),
                ('data_revogacao', models.DateTimeField(blank=True, null=True, verbose_name='Data da Revogação')),
                ('ip_aceite', models.GenericIPAddressField(verbose_name='IP do Aceite')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consentimento_lgpd', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Consentimento LGPD',
                'verbose_name_plural': 'Consentimentos LGPD',
            },
        ),
        migrations.CreateModel(
            name='LogAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=100, verbose_name='Ação Realizada')),
                ('tabela_acessada', models.CharField(blank=True, max_length=100, verbose_name='Tabela Acessada')),
                ('objeto_id', models.IntegerField(blank=True, null=True, verbose_name='ID do Objeto')),
                ('ip', models.GenericIPAddressField(verbose_name='Endereço IP')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='User Agent')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_acesso', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de Acesso',
                'verbose_name_plural': 'Logs de Acesso',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(choices=[('responsavel', 'Responsável/Pai/Mãe'), ('profissional', 'Profissional de Saúde'), ('admin', 'Administrador')], default='responsavel', max_length=20, verbose_name='Tipo de Usuário')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('aceite_termos', models.BooleanField(default=False, verbose_name='Aceite dos Termos de Uso')),
                ('data_aceite_termos', models.DateTimeField(blank=True, null=True, verbose_name='Data do Aceite dos Termos')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_neuroprev', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuários',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_suffix', models.CharField(default='NeuroPrev', help_text="Título do site e utilizado como sufixo na tag meta. Ex.: ' | NeuroPrev'", max_length=255, verbose_name='Título do Site')),
                ('periodo_eleitoral_habilitado', models.BooleanField(default=False, help_text='Ative para indicar que o site está em período eleitoral.', verbose_name='Habilitar Período Eleitoral')),
                ('periodo_eleitoral_inicio', models.DateField(blank=True, null=True, verbose_name='Data de início do período eleitoral')),
                ('periodo_eleitoral_fim', models.DateField(blank=True, null=True, verbose_name='Data de fim do período eleitoral')),
                ('texto_informativo_periodo_eleitoral', models.TextField(blank=True, default='Em respeito à legislação eleitoral (Lei 9.504/97), as notícias deste site/portal estão temporariamente suspensas.', verbose_name='Texto informativo do período eleitoral')),
                ('redes_sociais', wagtail.fields.StreamField([('lista_redes', 7)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Siga-nos nas redes sociais', 'required': False}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Imagem que será exibida ao lado do texto.', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'required': True}), 3: ('wagtail.blocks.URLBlock', (), {'required': True}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('fa-brands fa-facebook', 'Facebook'), ('fa-brands fa-instagram', 'Instagram'), ('fa-brands fa-linkedin', 'LinkedIn'), ('fa-brands fa-spotify', 'Spotify'), ('fa-brands fa-telegram', 'Telegram'), ('fa-brands fa-tiktok', 'TikTok'), ('fa-brands fa-whatsapp', 'WhatsApp'), ('fa-brands fa-square-x-twitter', 'X'), ('fa-brands fa-youtube', 'YouTube')]}), 5: ('wagtail.blocks.StructBlock', [[('nome', 2), ('link', 3), ('icone', 4)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {'max_num': 4}), 7: ('wagtail.blocks.StructBlock', [[('titulo', 0), ('imagem', 1), ('redes', 6)]], {})}, help_text='Defina as redes sociais do Portal.', verbose_name='Redes Sociais (Globais)')),
                ('menu_max_levels', models.PositiveIntegerField(default=1, help_text='Define até quantos níveis de páginas o menu principal irá exibir. (Máximo: 3)', verbose_name='Níveis máximos do menu')),
                ('cookies_habilitado', models.BooleanField(default=False, help_text='Ative para exibir o banner de consentimento de cookies no site.', verbose_name='Habilitar Aviso de Cookies')),
                ('google_analytics_tag', models.CharField(blank=True, help_text='Insira a tag do Google Analytics (ex: G-XXXXXXXXXX).', max_length=20, verbose_name='Tag do Google Analytics')),
                ('intranet_habilitada', models.BooleanField(default=False, help_text='Marque esta opção para ativar todas as funcionalidades da Intranet no site.', verbose_name='Ativar Intranet')),
                ('footer_titulo_instituicao', models.CharField(blank=True, default='CENTRO ADMINISTRATIVO ESTADUAL', max_length=255, verbose_name='Título da Instituição no Rodapé')),
                ('footer_informacoes', models.TextField(blank=True, default='Rua João da Mata, S/N, Jaguaribe - CEP: 58.015-020<br>\nFone: Recepção: (83) 98658-8328 - JOÃO PESSOA - PARAÍBA<br>\nHorário de Atendimento: Das 8:00 às 16:30<br>\nCNPJ: 09.189.499/0001-00', help_text='Endereço, telefone, horário, CNPJ. Use <br> para quebras de linha.', verbose_name='Informações do Rodapé')),
                ('footer_link_sic', models.URLField(blank=True, default='https://sic.pb.gov.br/', verbose_name='Link para o SIC (Serviço de Informação ao Cidadão)')),
                ('captcha_site_key', models.CharField(blank=True, help_text='Chave pública (site key) do reCAPTCHA usada no cliente (frontend).', max_length=255, verbose_name='Captcha Site Key (pública)')),
                ('captcha_secret_key', models.CharField(blank=True, help_text='Chave secreta do reCAPTCHA usada para validação no servidor. (Deixe em branco se não usar captcha)', max_length=255, verbose_name='Captcha Secret Key (secreta)')),
                ('compartilhamento_habilitado', models.BooleanField(default=True, help_text='Ative para exibir os botões de compartilhamento nas páginas.', verbose_name='Habilitar Compartilhamento')),
                ('compartilhamento_facebook', models.BooleanField(default=True, help_text='Permitir compartilhamento no Facebook', verbose_name='Facebook')),
                ('compartilhamento_twitter', models.BooleanField(default=True, help_text='Permitir compartilhamento no X (antigo Twitter)', verbose_name='X (Twitter)')),
                ('compartilhamento_linkedin', models.BooleanField(default=True, help_text='Permitir compartilhamento no LinkedIn', verbose_name='LinkedIn')),
                ('compartilhamento_whatsapp', models.BooleanField(default=True, help_text='Permitir compartilhamento no WhatsApp', verbose_name='WhatsApp')),
                ('compartilhamento_telegram', models.BooleanField(default=False, help_text='Permitir compartilhamento no Telegram', verbose_name='Telegram')),
                ('compartilhamento_email', models.BooleanField(default=True, help_text='Permitir compartilhamento via e-mail', verbose_name='E-mail')),
                ('compartilhamento_copiar_link', models.BooleanField(default=True, help_text='Permitir copiar o link da página', verbose_name='Copiar Link')),
                ('footer_imagem_sic', models.ForeignKey(blank=True, help_text='Faça o upload da imagem do logo do SIC.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagem do SIC no rodapé')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoExclusao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(verbose_name='Motivo da Solicitação')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_processamento', 'Em Processamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='pendente', max_length=20, verbose_name='Status')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Solicitação')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data da Conclusão')),
                ('processado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exclusoes_processadas', to=settings.AUTH_USER_MODEL, verbose_name='Processado Por')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_exclusao', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Solicitante')),
            ],
            options={
                'verbose_name': 'Solicitação de Exclusão',
                'verbose_name_plural': 'Solicitações de Exclusão',
                'ordering': ['-data_solicitacao'],
            },
        ),
    ]
