# Generated by Django 5.1.9 on 2025-06-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='periodo_eleitoral_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Data de fim do período eleitoral'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='periodo_eleitoral_habilitado',
            field=models.BooleanField(default=False, help_text='Ative para indicar que o site está em período eleitoral.', verbose_name='Habilitar Período Eleitoral'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='periodo_eleitoral_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Data de início do período eleitoral'),
        ),
    ]
