# Generated by Django 5.1.14 on 2025-11-24 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='periodo_eleitoral_habilitado',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='periodo_eleitoral_inicio',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='periodo_eleitoral_fim',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='texto_informativo_periodo_eleitoral',
        ),
    ]
