# Generated by Django 5.1.9 on 2025-06-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings_periodo_eleitoral_fim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='texto_informativo_periodo_eleitoral',
            field=models.TextField(blank=True, default='Em respeito à legislação eleitoral, Lei 9.504/97, este site/portal está temporariamente suspenso.', verbose_name='Texto informativo do período eleitoral'),
        ),
    ]
