# Generated by Django 5.1.14 on 2025-11-25 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_periodo_eleitoral'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_neuroathena', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='title_suffix',
            field=models.CharField(default='NEUROATHENA', help_text="Título do site e utilizado como sufixo na tag meta. Ex.: ' | NEUROATHENA'", max_length=255, verbose_name='Título do Site'),
        ),
    ]
