# Generated by Django 5.1.9 on 2025-06-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesettings_texto_informativo_periodo_eleitoral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='texto_informativo_periodo_eleitoral',
            field=models.TextField(blank=True, default='Em respeito a legislação eleitoral, Lei 9.504/97, as notícias deste site/portal está temporariamente suspensa.', verbose_name='Texto informativo do período eleitoral'),
        ),
    ]
