# Generated by Django 5.1.9 on 2025-07-02 12:55

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sitesettings_redes_sociais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='redes_sociais',
            field=wagtail.fields.StreamField([('lista_redes', 7)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Siga-nos nas redes sociais', 'required': False}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Imagem que será exibida ao lado do texto.', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'required': True}), 3: ('wagtail.blocks.URLBlock', (), {'required': True}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('fa-brands fa-facebook', 'Facebook'), ('fa-brands fa-instagram', 'Instagram'), ('fa-brands fa-youtube', 'YouTube'), ('fa-brands fa-spotify', 'Spotify'), ('fa-brands fa-square-x-twitter', 'X'), ('fa-brands fa-tiktok', 'TikTok'), ('fa-brands fa-linkedin', 'LinkedIn'), ('fa-brands fa-whatsapp', 'WhatsApp'), ('fa-brands fa-telegram', 'Telegram')]}), 5: ('wagtail.blocks.StructBlock', [[('nome', 2), ('link', 3), ('icone', 4)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {'max_num': 4}), 7: ('wagtail.blocks.StructBlock', [[('titulo', 0), ('imagem', 1), ('redes', 6)]], {})}, verbose_name='Redes Sociais'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='texto_informativo_periodo_eleitoral',
            field=models.TextField(blank=True, default='Em respeito a legislação eleitoral, Lei 9.504/97, as notícias deste site/portal estão temporariamente suspensa.', verbose_name='Texto informativo do período eleitoral'),
        ),
    ]
