# Generated by Django 5.1.9 on 2025-07-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_sitesettings_redes_sociais_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('view_conteudo_migrado', 'Pode ver conteúdo migrado (body_migrated)')],
                'default_permissions': [],
            },
        ),
    ]
