# Generated by Django 5.1.9 on 2025-07-04 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
