# Generated by Django 5.1.11 on 2025-07-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='menu_max_levels',
            field=models.PositiveIntegerField(default=1, help_text='Define até quantos níveis de páginas o menu principal irá exibir.', verbose_name='Níveis máximos do menu'),
        ),
    ]
