# Generated by Django 5.1.11 on 2025-08-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_sitesettings_menu_max_levels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='menu_max_levels',
            field=models.PositiveIntegerField(default=1, help_text='Define até quantos níveis de páginas o menu principal irá exibir. (Máximo: 3)', verbose_name='Níveis máximos do menu'),
        ),
    ]
