# Generated by Django 5.1.11 on 2025-09-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_sitesettings_redes_sociais'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='cookies_habilitado',
            field=models.BooleanField(default=False, help_text='Ative para exibir o banner de consentimento de cookies no site.', verbose_name='Habilitar Aviso de Cookies'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_analytics_tag',
            field=models.CharField(blank=True, help_text='Insira a tag do Google Analytics (ex: G-XXXXXXXXXX). O aviso de cookies analíticos só será exibido se esta tag estiver definida.', max_length=20, verbose_name='Tag do Google Analytics'),
        ),
    ]
