# Generated by Django 5.1.13 on 2025-10-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_sitesettings_cookies_habilitado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='captcha_secret_key',
            field=models.CharField(blank=True, help_text='Chave secreta do reCAPTCHA usada para validação no servidor. (Deixe em branco se não usar captcha)', max_length=255, verbose_name='Captcha Secret Key (secreta)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='captcha_site_key',
            field=models.CharField(blank=True, help_text='Chave pública (site key) do reCAPTCHA usada no cliente (frontend).', max_length=255, verbose_name='Captcha Site Key (pública)'),
        ),
    ]
