# Generated by Django 5.1.13 on 2025-10-21 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_sitesettings_cookies_habilitado_and_more'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_url', models.URLField(blank=True, help_text='URL base da API do portal de conteúdo externo.', verbose_name='URL da API Externa')),
                ('api_login', models.CharField(blank=True, help_text='Usuário para autenticação na API externa.', max_length=255, verbose_name='Login da API')),
                ('api_senha', models.CharField(blank=True, help_text='Senha para autenticação na API externa. Cuidado: será armazenada como texto plano.', max_length=255, verbose_name='Senha da API')),
                ('puxar_noticias', models.BooleanField(default=False, help_text='Ativar para buscar notícias do portal externo.', verbose_name='Puxar Notícias')),
                ('tags_noticias', models.CharField(blank=True, help_text="Separar tags por vírgula. Ex: 'geral, importante'. Deixe em branco para buscar todas.", max_length=255, verbose_name='Tags de Notícias')),
                ('puxar_avisos', models.BooleanField(default=False, help_text='Ativar para buscar avisos do portal externo.', verbose_name='Puxar Avisos')),
                ('tags_avisos', models.CharField(blank=True, help_text="Separar tags por vírgula. Ex: 'urgente, comunicado'. Deixe em branco para buscar todos.", max_length=255, verbose_name='Tags de Avisos')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Configurações da API Externa',
            },
        ),
    ]
