# Generated by Django 5.1.13 on 2025-10-20 13:03

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_sitesettings_cookies_habilitado_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='compartilhar_rede_social',
            field=wagtail.fields.StreamField([('redes_compartilhar', 2)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('facebook', 'Facebook'), ('x', 'X (Twitter)'), ('linkedin', 'LinkedIn'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('email', 'E-mail'), ('sms', 'SMS'), ('print', 'Imprimir'), ('copy', 'Copiar Link'), ('reddit', 'Reddit'), ('pinterest', 'Pinterest'), ('messenger', 'Messenger')], 'label': 'Rede de compartilhamento'}), 1: ('wagtail.blocks.ListBlock', (0,), {'help_text': 'Selecione as redes sociais nas quais o conteúdo poderá ser compartilhado.', 'label': 'Selecionar Redes de Compartilhamento'}), 2: ('wagtail.blocks.StructBlock', [[('redes', 1)]], {})}, help_text='Escolha quais redes sociais estarão disponíveis para compartilhamento.', verbose_name='Selecionar Redes para Compartilhamento'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='compartilhar_redes_sociais',
            field=models.BooleanField(default=False, help_text='Ative para exibir os botões de compartilhamento nas páginas.', verbose_name='Ativar Compartilhamento em Redes Sociais'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='intranet_habilitada',
            field=models.BooleanField(default=False, help_text='Marque esta opção para ativar todas as funcionalidades da Intranet no site.', verbose_name='Ativar Intranet'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='google_analytics_tag',
            field=models.CharField(blank=True, help_text='Insira a tag do Google Analytics (ex: G-XXXXXXXXXX).', max_length=20, verbose_name='Tag do Google Analytics'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='texto_informativo_periodo_eleitoral',
            field=models.TextField(blank=True, default='Em respeito à legislação eleitoral (Lei 9.504/97), as notícias deste site/portal estão temporariamente suspensas.', verbose_name='Texto informativo do período eleitoral'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='title_suffix',
            field=models.CharField(default='Site Padrão', help_text="Título do site e utilizado como sufixo na tag meta. Ex.: ' | Site Padrão'", max_length=255, verbose_name='Título do Site'),
        ),
    ]
