# Generated by Django 5.1.13 on 2025-10-21 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_apisettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apisettings',
            options={'verbose_name': 'Conteúdo Externo via API'},
        ),
    ]
