# Generated by Django 5.1.13 on 2025-10-21 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_sitesettings_captcha_secret_key_and_more'),
        ('core', '0013_sitesettings_compartilhar_rede_social_and_more'),
    ]

    operations = [
    ]
