# Generated by Django 5.1.11 on 2025-10-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_sitesettings_captcha_secret_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='compartilhamento_copiar_link',
            field=models.BooleanField(default=True, help_text='Permitir copiar o link da página', verbose_name='Copiar Link'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='compartilhamento_email',
            field=models.BooleanField(default=True, help_text='Permitir compartilhamento via e-mail', verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='compartilhamento_facebook',
            field=models.BooleanField(default=True, help_text='Permitir compartilhamento no Facebook', verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='compartilhamento_habilitado',
            field=models.BooleanField(default=True, help_text='Ative para exibir os botões de compartilhamento nas páginas.', verbose_name='Habilitar Compartilhamento'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='compartilhamento_linkedin',
            field=models.BooleanField(default=True, help_text='Permitir compartilhamento no LinkedIn', verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='compartilhamento_telegram',
            field=models.BooleanField(default=False, help_text='Permitir compartilhamento no Telegram', verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='compartilhamento_twitter',
            field=models.BooleanField(default=True, help_text='Permitir compartilhamento no X (antigo Twitter)', verbose_name='X (Twitter)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='compartilhamento_whatsapp',
            field=models.BooleanField(default=True, help_text='Permitir compartilhamento no WhatsApp', verbose_name='WhatsApp'),
        ),
    ]
