# Generated by Django 5.1.13 on 2025-10-29 17:52

from django.db import migrations


class Migration(migrations.Migration):
    """Merge de branches paralelas"""

    dependencies = [
        ('core', '0013_sitesettings_captcha_secret_key_and_more'),
        ('core', '0013a_sitesettings_compartilhar_rede_social_and_more'),
    ]

    operations = [
    ]
