# Generated by Django 5.1.13 on 2025-10-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_apisettings_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apisettings',
            options={'verbose_name': 'Configurações de Conteúdo Externo'},
        ),
        migrations.RemoveField(
            model_name='apisettings',
            name='api_login',
        ),
        migrations.RemoveField(
            model_name='apisettings',
            name='api_senha',
        ),
        migrations.AddField(
            model_name='apisettings',
            name='api_token',
            field=models.CharField(blank=True, help_text="Token para autenticação na API externa (Ex: 'Token 9944b09199c62bcf9418ad846dd0e4bbdfc6ee4b').", max_length=255, verbose_name='Token de Autenticação da API'),
        ),
    ]
