# Generated by Django 5.1.13 on 2025-10-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    """Merge consolidado de múltiplas branches"""

    dependencies = [
        ('core', '0014_merge_20251021_1740'),
        ('core', '0014a_sitesettings_compartilhamento_copiar_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='footer_imagem_sic',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='footer_link_sic',
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_informacoes',
            field=models.TextField(blank=True, help_text='Endereço, telefone, horário, CNPJ. Use <br> para quebras de linha.', verbose_name='Informações do Rodapé'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_titulo_instituicao',
            field=models.CharField(blank=True, max_length=255, verbose_name='Título da Instituição no Rodapé'),
        ),
    ]
