# Generated by Django 5.1.13 on 2025-10-24 10:31

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_sitesettings_footer_imagem_sic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='compartilhar_rede_social',
            field=wagtail.fields.StreamField([('redes_compartilhar', 2)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('facebook', 'Facebook'), ('x', 'X (Twitter)'), ('linkedin', 'LinkedIn'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('email', 'E-mail'), ('sms', 'SMS'), ('print', 'Imprimir'), ('copy', 'Copiar Link'), ('reddit', 'Reddit'), ('pinterest', 'Pinterest'), ('messenger', 'Messenger')], 'label': 'Rede de compartilhamento'}), 1: ('wagtail.blocks.ListBlock', (0,), {'help_text': 'Selecione as redes sociais nas quais o conteúdo poderá ser compartilhado.', 'label': 'Selecionar Redes de Compartilhamento'}), 2: ('wagtail.blocks.StructBlock', [[('redes', 1)]], {})}, help_text='Escolha quais redes sociais estarão disponíveis para compartilhamento. Cada tipo de rede só pode ser adicionado uma vez (máx. 1 por tipo).', verbose_name='Selecionar Redes para Compartilhamento'),
        ),
    ]
