# Generated by Django 5.1.13 on 2025-10-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_apisettings_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apisettings',
            name='api_token',
        ),
        migrations.AddField(
            model_name='apisettings',
            name='api_senha',
            field=models.CharField(blank=True, help_text='Senha para autenticação na API externa. Cuidado: será armazenada como texto plano.', max_length=255, verbose_name='Senha da API'),
        ),
        migrations.AddField(
            model_name='apisettings',
            name='api_usuario',
            field=models.CharField(blank=True, help_text='Usuário para autenticação na API externa.', max_length=255, verbose_name='Usuário da API'),
        ),
    ]
