# Generated by Django 5.1.13 on 2025-10-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_apisettings_api_token_apisettings_api_senha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apisettings',
            name='api_habilitada',
            field=models.BooleanField(default=False, help_text='Marque esta opção para ativar a busca de conteúdo de um portal externo.', verbose_name='Habilitar Integração via API'),
        ),
    ]
