# Generated by Django 5.1.11 on 2025-10-29 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_sitesettings_compartilhamento_copiar_link_and_more'),
        ('core', '0016_alter_sitesettings_compartilhar_rede_social'),
    ]

    operations = [
    ]
