# Generated by Django 5.1.13 on 2025-10-22 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_apisettings_api_habilitada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apisettings',
            name='puxar_avisos',
        ),
        migrations.RemoveField(
            model_name='apisettings',
            name='tags_avisos',
        ),
    ]
