# Generated by Django 5.1.13 on 2025-10-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_apisettings_puxar_avisos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apisettings',
            name='api_url',
            field=models.URLField(blank=True, help_text='URL base da API do portal de conteúdo externo. Ex:https://paraiba.pb.gov.br/', verbose_name='URL da API Externa'),
        ),
    ]
