# Generated by Django 5.1.13 on 2025-10-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_apisettings_api_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apisettings',
            name='puxar_noticias',
            field=models.BooleanField(default=False, help_text='Ativar para buscar notícias do portal externo.', verbose_name='Consumir Notícias'),
        ),
        migrations.AlterField(
            model_name='apisettings',
            name='tags_noticias',
            field=models.CharField(blank=True, help_text="Separar tags por vírgula. Ex: 'geral, importante'. Deixe em branco para buscar todas.", max_length=255, verbose_name='Tags para filtrar Notícias'),
        ),
    ]
