# Generated by Django 5.1.13 on 2025-10-30 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_sitesettings_captcha_secret_key_and_more'),
        ('core', '0020_alter_apisettings_puxar_noticias_and_more'),
    ]

    operations = [
    ]
