# Generated by Django 5.1.13 on 2025-10-31 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_sitesettings_compartilhamento_copiar_link_and_more'),
        ('core', '0021_merge_20251030_1554'),
    ]

    operations = [
    ]
