# Generated by Django 5.1.11 on 2025-11-03 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_sitesettings_footer_imagem_sic_and_more'),
        ('core', '0022_merge_20251031_1153'),
    ]

    operations = [
    ]
