# Generated by Django 5.1.11 on 2025-11-12 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_merge_20251103_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='compartilhar_rede_social',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='compartilhar_redes_sociais',
        ),
    ]
