# Generated by Django 5.1.11 on 2025-10-15 17:01

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorpoTecnicoGrupoPageIndex',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CorpoTecnicoPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('descricao', models.TextField(blank=True, help_text='Descrição da página para SEO e redes sociais', verbose_name='Descrição')),
                ('funcao', models.CharField(blank=True, help_text='Função ou cargo do membro do corpo técnico.', max_length=255, null=True, verbose_name='Função')),
                ('bio', wagtail.fields.StreamField([('paragraph_block', 0)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'description': 'A rich text paragraph', 'icon': 'pilcrow', 'preview_value': '\n            <h2>Our bread pledge</h2>\n            <p>As a bakery, <b>breads</b> have <i>always</i> been in our hearts.\n            <a href="https://en.wikipedia.org/wiki/Staple_food">Staple foods</a>\n            are essential for society, and – bread is the tastiest of all.\n            We love to transform batters and doughs into baked goods with a firm\n            dry crust and fluffy center.</p>\n            ', 'template': 'blocks/paragraph_block.html'})}, null=True, verbose_name='Biografia')),
                ('imagem', models.ForeignKey(blank=True, help_text='Imagem do membro do corpo técnico.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagem')),
                ('imagem_destaque', models.ForeignKey(blank=True, help_text='Imagem usada em destaque para SEO e redes sociais', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagem de Destaque')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CorpoTecnicoIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('sub_titulo', models.CharField(blank=True, help_text='Subtítulo da página do corpo técnico.', max_length=255, null=True, verbose_name='Subtítulo')),
                ('grupos_corpo_tecnico', wagtail.fields.StreamField([('grupo', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Título do Grupo', 'max_length': 255, 'required': False}), 1: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Selecione a página do grupo', 'page_type': ['paginas.CorpoTecnicoGrupoPageIndex'], 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('titulo', 0), ('grupo_page', 1)]], {'label': 'Grupo do Corpo Técnico'})}, null=True, verbose_name='Grupos do Corpo Técnico')),
                ('tecnico_em_destaque', models.ForeignKey(blank=True, help_text='Selecione um membro do corpo técnico para destacar na página inicial do corpo técnico.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='paginas.corpotecnicopage', verbose_name='Técnico em Destaque')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
