# Generated by Django 5.1.14 on 2025-11-25 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedirectPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('descricao', models.TextField(blank=True, help_text='Descrição da página, utilizada em SEO e redes sociais', verbose_name='Descrição')),
                ('external_url', models.URLField(blank=True, help_text='Ou insira uma URL externa (ex: https://exemplo.com)', max_length=500, null=True, verbose_name='URL externa')),
                ('imagem_destaque', models.ForeignKey(blank=True, help_text='Imagem usada em destaque para SEO e redes sociais', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagem de Destaque')),
                ('internal_page', models.ForeignKey(blank=True, help_text='Selecione uma página interna do site para redirecionar', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Página interna')),
            ],
            options={
                'verbose_name': 'Página Link',
                'verbose_name_plural': 'Páginas Link',
            },
            bases=('wagtailcore.page',),
        ),
    ]
