# Generated by Django 5.1.11 on 2025-10-15 19:09

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardLinhaDoTempoPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('descricao', models.TextField(blank=True, help_text='Descrição da página para SEO e redes sociais', verbose_name='Descrição')),
                ('images', wagtail.fields.StreamField([('image', 0)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagem'})}, help_text='Imagens relacionadas à página', verbose_name='Imagens')),
                ('texto_alternativo', models.TextField(blank=True, max_length=255, null=True, verbose_name='Texto alternativo da imagem')),
                ('titulo', models.TextField(blank=True, max_length=255, null=True, verbose_name='Título')),
                ('descricao_completa', models.TextField(blank=True, max_length=255, null=True, verbose_name='Descrição')),
                ('imagem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.image', verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Página de Card da Linha do Tempo',
            },
            bases=('wagtailcore.page',),
        ),
    ]
