# Generated by Django 5.1.11 on 2025-10-02 14:33

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corpotecnicogrupopageindex',
            name='titulo',
        ),
        migrations.RemoveField(
            model_name='corpotecnicopage',
            name='titulo',
        ),
        migrations.AlterField(
            model_name='corpotecnicoindexpage',
            name='grupos_corpo_tecnico',
            field=wagtail.fields.StreamField([('grupo', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Título do Grupo', 'max_length': 255, 'required': False}), 1: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Selecione a página do grupo', 'page_type': ['paginas.CorpoTecnicoGrupoPageIndex'], 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('titulo', 0), ('grupo_page', 1)]], {'label': 'Grupo do Corpo Técnico'})}, null=True, verbose_name='Grupos do Corpo Técnico'),
        ),
    ]
