# Generated by Django 5.1.12 on 2025-10-16 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardlinhadotempopage',
            name='data_publicacao',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Data de publicação do aviso'),
        ),
    ]
