# Generated by Django 5.1.11 on 2025-11-03 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CorpoTecnicoPage',
        ),
        migrations.DeleteModel(
            name='CorpoTecnicoGrupoPageIndex',
        ),
        migrations.DeleteModel(
            name='CorpoTecnicoIndexPage',
        ),
    ]
