# Generated by Django 5.1.11 on 2025-10-22 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0002_cardlinhadotempopage_data_publicacao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CardLinhaDoTempoPage',
        ),
    ]
