# Generated by Django 5.1.11 on 2025-10-14 14:03

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0003_alter_corpotecnicopage_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpotecnicopage',
            name='bio',
            field=wagtail.fields.StreamField([('paragraph_block', 0)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'description': 'A rich text paragraph', 'icon': 'pilcrow', 'preview_value': '\n            <h2>Our bread pledge</h2>\n            <p>As a bakery, <b>breads</b> have <i>always</i> been in our hearts.\n            <a href="https://en.wikipedia.org/wiki/Staple_food">Staple foods</a>\n            are essential for society, and – bread is the tastiest of all.\n            We love to transform batters and doughs into baked goods with a firm\n            dry crust and fluffy center.</p>\n            ', 'template': 'blocks/paragraph_block.html'})}, null=True, verbose_name='Biografia'),
        ),
    ]
