# Generated by Django 5.1.11 on 2025-10-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0004_alter_corpotecnicopage_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpotecnicoindexpage',
            name='sub_titulo',
            field=models.CharField(blank=True, help_text='Subtítulo da página do corpo técnico.', max_length=255, null=True, verbose_name='Subtítulo'),
        ),
    ]
