# Generated by Django 5.1.14 on 2025-11-24 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioSubmissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('dados_adicionais', models.JSONField(help_text='Campos customizados do formulário.', verbose_name='Dados Adicionais')),
                ('data_envio', models.DateTimeField(auto_now_add=True, verbose_name='Data de envio')),
                ('pagina', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Página de origem')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário da Intranet?')),
            ],
            options={
                'verbose_name': 'Envio do Formulário',
                'verbose_name_plural': 'Envios dos Formulários',
                'ordering': ['-data_envio'],
            },
        ),
        migrations.CreateModel(
            name='ArquivoSubmetido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_campo', models.CharField(max_length=255)),
                ('arquivo', models.FileField(upload_to='formularios_submetidos/')),
                ('submissao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos_submetidos', to='blocks.formulariosubmissao')),
            ],
        ),
    ]
