# Generated by Django 5.1.13 on 2025-10-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulariosubmissao',
            name='form_data',
        ),
        migrations.AddField(
            model_name='formulariosubmissao',
            name='dados_adicionais',
            field=models.JSONField(default=2, help_text='Campos customizados do formulário.', verbose_name='Dados Adicionais'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formulariosubmissao',
            name='nome_completo',
            field=models.CharField(default=2, max_length=255, verbose_name='Nome Completo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formulariosubmissao',
            name='titulo',
            field=models.CharField(default=2, max_length=255, verbose_name='Título'),
            preserve_default=False,
        ),
    ]
