# Generated by Django 5.1.13 on 2025-10-07 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0002_remove_formulariosubmissao_form_data_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formulariosubmissao',
            options={'ordering': ['-data_envio'], 'verbose_name': 'Envio do Formulário', 'verbose_name_plural': 'Envios dos Formulários'},
        ),
        migrations.RemoveField(
            model_name='formulariosubmissao',
            name='usuario',
        ),
    ]
