# Generated by Django 5.1.13 on 2025-10-07 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0005_alter_formulariosubmissao_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivoSubmetido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_campo', models.CharField(max_length=255)),
                ('arquivo', models.FileField(upload_to='formularios_submetidos/')),
                ('submissao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos_submetidos', to='blocks.formulariosubmissao')),
            ],
        ),
    ]
