# Generated by Django 5.1.11 on 2025-11-19 17:13

from django.db import migrations
import json


def migrate_streamfield_link_blocks(apps, schema_editor):
    """
    Migra dados de StreamField que contêm CardLinhaDoTempoBlock e LinkWithImageStructBlock.
    
    Transforma estrutura antiga:
        {'internal_page': X, 'external_url': Y, ...}
    
    Para nova estrutura:
        {'link': {'internal_page': X, 'external_url': Y, 'link_text': ''}, ...}
    
    IMPORTANTE: Esta migração apenas atualiza os dados JSON salvos no campo StreamField.
    Não há alteração de schema (campos do banco continuam iguais - são JSONField).
    """
    
    def transform_card_linha_do_tempo_block(block_data):
        """Transforma CardLinhaDoTempoBlock para usar campo 'link' aninhado."""
        if not isinstance(block_data, dict):
            return block_data, False
        
        # Se já tem campo 'link', não precisa migrar
        if 'link' in block_data:
            return block_data, False
        
        # Se tem campos antigos internal_page ou external_url, migrar
        has_old_fields = 'internal_page' in block_data or 'external_url' in block_data
        
        if has_old_fields:
            # Criar novo campo 'link' com dados antigos
            block_data['link'] = {
                'internal_page': block_data.pop('internal_page', None),
                'external_url': block_data.pop('external_url', None),
                'link_text': '',  # Campo obrigatório em LinkStructBlock
            }
            return block_data, True
        
        return block_data, False
    
    def transform_link_with_image_block(block_data):
        """Transforma LinkWithImageStructBlock para usar campo 'link' aninhado."""
        if not isinstance(block_data, dict):
            return block_data, False
        
        # Se já tem campo 'link', não precisa migrar
        if 'link' in block_data:
            return block_data, False
        
        # Se tem campos antigos internal_page ou external_url, migrar
        has_old_fields = 'internal_page' in block_data or 'external_url' in block_data
        
        if has_old_fields:
            # Criar novo campo 'link' com dados antigos
            # Preservar link_text se existir no nível superior
            link_text = block_data.get('link_text', '')
            
            block_data['link'] = {
                'internal_page': block_data.pop('internal_page', None),
                'external_url': block_data.pop('external_url', None),
                'link_text': link_text,
            }
            return block_data, True
        
        return block_data, False
    
    def process_streamfield(stream_data):
        """Processa recursivamente um StreamField procurando blocos para migrar."""
        if not isinstance(stream_data, list):
            return False
        
        modified = False
        
        for item in stream_data:
            if not isinstance(item, dict):
                continue
            
            block_type = item.get('type')
            value = item.get('value')
            
            # CardLinhaDoTempoBlock dentro de LinhaDoTempoBlock
            if block_type == 'linha_do_tempo' and isinstance(value, dict):
                cards = value.get('cards', [])
                if isinstance(cards, list):
                    for card in cards:
                        if isinstance(card, dict):
                            card_value = card.get('value')
                            if isinstance(card_value, dict):
                                card['value'], changed = transform_card_linha_do_tempo_block(card_value)
                                if changed:
                                    modified = True
            
            # LinkWithImageStructBlock (caso apareça diretamente em algum StreamField)
            elif block_type == 'link_with_image' and isinstance(value, dict):
                item['value'], changed = transform_link_with_image_block(value)
                if changed:
                    modified = True
        
        return modified
    
    # Buscar todos os modelos Page do Wagtail e processar StreamFields
    Page = apps.get_model('wagtailcore', 'Page')
    Revision = apps.get_model('wagtailcore', 'Revision')
    
    pages_migrated = 0
    revisions_migrated = 0
    
    # Migrar dados publicados (latest_revision_created_at)
    for page in Page.objects.all():
        modified = False
        modified_fields = []
        
        # Buscar campos StreamField dinamicamente
        for field in page._meta.fields:
            # StreamField é armazenado como JSONField ou TextField
            if field.get_internal_type() in ('JSONField', 'TextField'):
                field_value = getattr(page, field.name, None)
                
                if field_value:
                    try:
                        # Tentar parsear como JSON
                        if isinstance(field_value, str):
                            stream_data = json.loads(field_value)
                        elif isinstance(field_value, (list, dict)):
                            stream_data = field_value
                        else:
                            continue
                        
                        # Processar apenas se for lista (formato StreamField)
                        if isinstance(stream_data, list):
                            if process_streamfield(stream_data):
                                setattr(page, field.name, json.dumps(stream_data))
                                modified = True
                                modified_fields.append(field.name)
                    except (json.JSONDecodeError, AttributeError, TypeError, ValueError):
                        continue
        
        if modified:
            # Salvar apenas os campos modificados
            page.save(update_fields=modified_fields)
            pages_migrated += 1
    
    # Migrar revisões (histórico)
    for revision in Revision.objects.all():
        try:
            content = json.loads(revision.content_json) if isinstance(revision.content_json, str) else revision.content_json
            
            if not isinstance(content, dict):
                continue
            
            modified = False
            
            # Processar cada campo que possa ser StreamField
            for field_name, field_value in content.items():
                if isinstance(field_value, list):  # Formato StreamField
                    if process_streamfield(field_value):
                        modified = True
            
            if modified:
                revision.content_json = json.dumps(content)
                revision.save(update_fields=['content_json'])
                revisions_migrated += 1
        except (json.JSONDecodeError, AttributeError, TypeError, KeyError):
            continue
    
    print(f"\n✅ Migração concluída:")
    print(f"   - {pages_migrated} página(s) publicada(s) atualizada(s)")
    print(f"   - {revisions_migrated} revisão(ões) atualizada(s)")
    if pages_migrated == 0 and revisions_migrated == 0:
        print("   - Nenhum dado antigo encontrado (OK)")


def reverse_migration(apps, schema_editor):
    """
    Reverte a migração, convertendo dados de volta ao formato antigo.
    
    Transforma:
        {'link': {'internal_page': X, 'external_url': Y}, ...}
    
    De volta para:
        {'internal_page': X, 'external_url': Y, ...}
    """
    
    def reverse_link_block(block_data):
        """Reverte campo 'link' aninhado de volta aos campos antigos."""
        if not isinstance(block_data, dict):
            return block_data, False
        
        link = block_data.get('link')
        if link and isinstance(link, dict):
            # Mover campos de volta para nível superior
            block_data['internal_page'] = link.get('internal_page')
            block_data['external_url'] = link.get('external_url')
            # Remover campo 'link'
            del block_data['link']
            return block_data, True
        
        return block_data, False
    
    def process_streamfield(stream_data):
        """Processa recursivamente um StreamField revertendo blocos."""
        if not isinstance(stream_data, list):
            return False
        
        modified = False
        
        for item in stream_data:
            if not isinstance(item, dict):
                continue
            
            block_type = item.get('type')
            value = item.get('value')
            
            if block_type == 'linha_do_tempo' and isinstance(value, dict):
                cards = value.get('cards', [])
                if isinstance(cards, list):
                    for card in cards:
                        if isinstance(card, dict):
                            card_value = card.get('value')
                            if isinstance(card_value, dict):
                                card['value'], changed = reverse_link_block(card_value)
                                if changed:
                                    modified = True
            
            elif block_type == 'link_with_image' and isinstance(value, dict):
                item['value'], changed = reverse_link_block(value)
                if changed:
                    modified = True
        
        return modified
    
    Page = apps.get_model('wagtailcore', 'Page')
    Revision = apps.get_model('wagtailcore', 'Revision')
    
    pages_reverted = 0
    revisions_reverted = 0
    
    for page in Page.objects.all():
        modified = False
        modified_fields = []
        
        for field in page._meta.fields:
            if field.get_internal_type() in ('JSONField', 'TextField'):
                field_value = getattr(page, field.name, None)
                
                if field_value:
                    try:
                        if isinstance(field_value, str):
                            stream_data = json.loads(field_value)
                        elif isinstance(field_value, (list, dict)):
                            stream_data = field_value
                        else:
                            continue
                        
                        if isinstance(stream_data, list):
                            if process_streamfield(stream_data):
                                setattr(page, field.name, json.dumps(stream_data))
                                modified = True
                                modified_fields.append(field.name)
                    except (json.JSONDecodeError, AttributeError, TypeError, ValueError):
                        continue
        
        if modified:
            page.save(update_fields=modified_fields)
            pages_reverted += 1
    
    for revision in Revision.objects.all():
        try:
            content = json.loads(revision.content_json) if isinstance(revision.content_json, str) else revision.content_json
            
            if not isinstance(content, dict):
                continue
            
            modified = False
            
            for field_name, field_value in content.items():
                if isinstance(field_value, list):
                    if process_streamfield(field_value):
                        modified = True
            
            if modified:
                revision.content_json = json.dumps(content)
                revision.save(update_fields=['content_json'])
                revisions_reverted += 1
        except (json.JSONDecodeError, AttributeError, TypeError, KeyError):
            continue
    
    print(f"\n✅ Reversão concluída:")
    print(f"   - {pages_reverted} página(s) revertida(s)")
    print(f"   - {revisions_reverted} revisão(ões) revertida(s)")


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0006_arquivosubmetido'),
        ('wagtailcore', '__latest__'),
    ]

    operations = [
        migrations.RunPython(
            migrate_streamfield_link_blocks,
            reverse_code=reverse_migration,
        ),
    ]
