# Generated by Django 5.1.11 on 2025-08-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avisosindexpage',
            options={'verbose_name': 'Página de Índice de Avisos'},
        ),
        migrations.AlterField(
            model_name='avisospage',
            name='descricao',
            field=models.TextField(help_text='Breve descrição do conteúdo da página.', verbose_name='Descrição'),
        ),
    ]
