# Generated by Django 5.1.11 on 2025-09-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0002_alter_avisosindexpage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avisospage',
            name='descricao',
            field=models.TextField(help_text='Breve descrição do conteúdo da página.', max_length=255, verbose_name='Descrição'),
        ),
    ]
