# Generated by Django 5.1.11 on 2025-09-30 15:36

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0003_alter_avisospage_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='avisospage',
            name='images',
            field=wagtail.fields.StreamField([('image', 0)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagem'})}, help_text='Imagens relacionadas à página', verbose_name='Imagens'),
        ),
    ]
