# Generated by Django 5.1.13 on 2025-10-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0004_avisospage_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avisospage',
            options={'verbose_name': 'Aviso', 'verbose_name_plural': 'Avisos'},
        ),
        migrations.AddField(
            model_name='avisosindexpage',
            name='mostrar_destaque_primeiro',
            field=models.BooleanField(default=True, help_text='Marcar para exibir os avisos em destaque primeiro.'),
        ),
        migrations.AddField(
            model_name='avisospage',
            name='destaque',
            field=models.BooleanField(default=False, help_text='Marcar este aviso como destaque?', verbose_name='Exibir em Destaques'),
        ),
    ]
