# Generated by Django 5.1.13 on 2025-10-22 17:10

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0005_alter_avisospage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avisosindexpage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='avisospage',
            options={'default_permissions': [], 'permissions': [('view_conteudo_migrado', 'Pode ver conteúdo migrado (body_migrated)')]},
        ),
        migrations.RemoveField(
            model_name='avisosindexpage',
            name='mostrar_destaque_primeiro',
        ),
        migrations.AddField(
            model_name='avisospage',
            name='slideshow_imagens',
            field=models.BooleanField(default=False, help_text='Marque para exibir as imagens como slideshow na página da notícia.', verbose_name='Ativar slideshow de imagens'),
        ),
        migrations.AlterField(
            model_name='avisosindexpage',
            name='introduction',
            field=models.TextField(default='Todos os avisos', help_text='Texto para o topo da página de avisos'),
        ),
        migrations.AlterField(
            model_name='avisospage',
            name='arquivos',
            field=wagtail.fields.StreamField([('arquivo', 0)], blank=True, block_lookup={0: ('blocks.models.EspecificDocumentChooserBlock', (), {'label': 'Arquivos', 'required': True})}, null=True, verbose_name='Arquivos da notícia'),
        ),
        migrations.AlterField(
            model_name='avisospage',
            name='descricao',
            field=models.TextField(help_text='Breve descrição do conteúdo da página.', max_length=211, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='avisospage',
            name='destaque',
            field=models.BooleanField(default=False, help_text='Marque se esta notícia deve ser exibida em destaque na página inicial ou em listas de notícias. Só pode ser cadastrado 6 avisos  em destaque.', verbose_name='Notícia em destaque'),
        ),
        migrations.AlterField(
            model_name='avisospage',
            name='images',
            field=wagtail.fields.StreamField([('imagem', 0)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagem da notícia', 'required': True})}, null=True, verbose_name='Coleção de Imagens'),
        ),
        migrations.AlterField(
            model_name='avisospage',
            name='nao_exibir_lista_de_arquivos',
            field=models.BooleanField(default=False, help_text='Marque para não exibir a lista de arquivos na página da notícia.', verbose_name='Não exibir lista de arquivos'),
        ),
        migrations.AlterField(
            model_name='avisospage',
            name='subtitle',
            field=models.TextField(blank=True, max_length=255, verbose_name='Subtítulo'),
        ),
    ]
