# Generated by Django 5.1.13 on 2025-10-29 17:45

from django.db import migrations


class Migration(migrations.Migration):
    """Merge de duas branches paralelas de desenvolvimento"""

    dependencies = [
        ('avisos', '0005_alter_avisospage_options_and_more'),
        ('avisos', '0005a_alter_avisospage_options_remove_avisospage_subtitle_and_more'),
    ]

    operations = [
    ]
