# Generated by Django 5.1.11 on 2025-10-27 13:58

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0005_remove_avisospage_images_avisospage_imagem_destaque'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avisospage',
            options={'default_permissions': [], 'permissions': [('view_conteudo_migrado', 'Pode ver conteúdo migrado (body_migrated)')], 'verbose_name': 'Página de Aviso', 'verbose_name_plural': 'Páginas de Avisos'},
        ),
        migrations.RemoveField(
            model_name='avisospage',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='avisospage',
            name='destaque',
            field=models.BooleanField(default=False, help_text='Exibe o aviso em destaque na página inicial. Máximo de 6 avisos.', verbose_name='Aviso em destaque'),
        ),
        migrations.AddField(
            model_name='avisospage',
            name='images',
            field=wagtail.fields.StreamField([('imagem', 0)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagem do aviso', 'required': True})}, null=True, verbose_name='Coleção de Imagens'),
        ),
        migrations.AddField(
            model_name='avisospage',
            name='slideshow_imagens',
            field=models.BooleanField(default=False, help_text='Exibir as imagens como slideshow na página do aviso.', verbose_name='Ativar slideshow de imagens'),
        ),
    ]
