# Generated by Django 5.1.13 on 2025-10-31 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0005_alter_avisospage_body'),
        ('avisos', '0006_merge_linear'),
    ]

    operations = [
    ]
