# Generated by Django 5.1.13 on 2025-10-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0006_alter_avisosindexpage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avisospage',
            name='resumo',
            field=models.TextField(blank=True, help_text='Gerado automaticamente a partir do corpo ou descrição (120 caracteres).', verbose_name='Resumo automático'),
        ),
        migrations.AlterField(
            model_name='avisosindexpage',
            name='introduction',
            field=models.TextField(default='Todos os avisos', help_text='Texto exibido no topo da página de avisos.', verbose_name='Introdução'),
        ),
        migrations.AlterField(
            model_name='avisospage',
            name='body_migrated',
            field=models.TextField(blank=True, help_text='Usado apenas para conteúdo do antigo site Plone.', null=True, verbose_name='Conteúdo migrado do Plone'),
        ),
        migrations.AlterField(
            model_name='avisospage',
            name='destaque',
            field=models.BooleanField(default=False, help_text='Exibe o aviso em destaque na página inicial. Máximo de 6 avisos.', verbose_name='Notícia em destaque'),
        ),
        migrations.AlterField(
            model_name='avisospage',
            name='nao_exibir_lista_de_arquivos',
            field=models.BooleanField(default=False, help_text='Marque para ocultar a lista de arquivos.', verbose_name='Não exibir lista de arquivos'),
        ),
        migrations.AlterField(
            model_name='avisospage',
            name='plone_node_id',
            field=models.TextField(blank=True, db_index=True, help_text='ID do nó no Plone, usado para identificar a página migrada.', null=True, unique=True, verbose_name='ID Plone'),
        ),
        migrations.AlterField(
            model_name='avisospage',
            name='sensivel_periodo_eleitoral',
            field=models.BooleanField(default=False, help_text='Marque se este aviso deve ser ocultado durante o período eleitoral.', verbose_name='Aviso sensível ao período eleitoral'),
        ),
        migrations.AlterField(
            model_name='avisospage',
            name='slideshow_imagens',
            field=models.BooleanField(default=False, help_text='Exibir as imagens como slideshow na página do aviso.', verbose_name='Ativar slideshow de imagens'),
        ),
    ]
