# Generated by Django 5.1.13 on 2025-10-24 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0005_remove_avisospage_images_avisospage_imagem_destaque'),
        ('avisos', '0007_avisospage_resumo_alter_avisosindexpage_introduction_and_more'),
    ]

    operations = [
    ]
