# Generated by Django 5.1.13 on 2025-10-24 10:31

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0008_merge_20251024_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='avisospage',
            name='images',
            field=wagtail.fields.StreamField([('imagem', 0)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagem do aviso', 'required': True})}, null=True, verbose_name='Coleção de Imagens'),
        ),
        migrations.AlterField(
            model_name='avisospage',
            name='arquivos',
            field=wagtail.fields.StreamField([('arquivo', 0)], blank=True, block_lookup={0: ('blocks.models.EspecificDocumentChooserBlock', (), {'label': 'Arquivos', 'required': True})}, null=True, verbose_name='Arquivos do aviso'),
        ),
        migrations.AlterField(
            model_name='avisospage',
            name='destaque',
            field=models.BooleanField(default=False, help_text='Exibe o aviso em destaque na página inicial. Máximo de 6 avisos.', verbose_name='Aviso em destaque'),
        ),
    ]
