# Generated by Django 5.1.11 on 2025-10-28 13:13

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0008_merge_20251024_1024'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='avisospage',
            name='imagem_destaque',
            field=models.ForeignKey(blank=True, help_text='Imagem usada em destaque para SEO e redes sociais', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagem de Destaque'),
        ),
        migrations.AlterField(
            model_name='avisospage',
            name='arquivos',
            field=wagtail.fields.StreamField([('arquivo', 0)], blank=True, block_lookup={0: ('blocks.models.EspecificDocumentChooserBlock', (), {'label': 'Arquivos', 'required': True})}, null=True, verbose_name='Arquivos do aviso'),
        ),
        migrations.AlterField(
            model_name='avisospage',
            name='destaque',
            field=models.BooleanField(default=False, help_text='Exibe o aviso em destaque na página inicial. Máximo de 6 avisos.', verbose_name='Aviso em destaque'),
        ),
        migrations.AlterField(
            model_name='avisospage',
            name='images',
            field=wagtail.fields.StreamField([('imagem', 0)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagem do aviso', 'required': True})}, null=True, verbose_name='Coleção de Imagens'),
        ),
    ]
