# Generated by Django 5.1.13 on 2025-10-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0009_alter_avisosindexpage_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avisosindexpage',
            name='mostrar_destaque_primeiro',
        ),
        migrations.AlterField(
            model_name='avisospage',
            name='descricao',
            field=models.TextField(help_text='Breve descrição do conteúdo da página.', max_length=211, verbose_name='Descrição'),
        ),
    ]
