# Generated by Django 5.1.11 on 2025-10-29 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0009_avisospage_imagem_destaque_alter_avisospage_arquivos_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avisosindexpage',
            options={'verbose_name': 'Página de Índice de Avisos'},
        ),
        migrations.AlterModelOptions(
            name='avisospage',
            options={'default_permissions': [], 'permissions': [('view_conteudo_migrado', 'Pode ver conteúdo migrado (body_migrated)')], 'verbose_name': 'Página de Aviso', 'verbose_name_plural': 'Páginas de Avisos'},
        ),
        migrations.RemoveField(
            model_name='avisospage',
            name='subtitle',
        ),
    ]
