# Generated by Django 5.1.13 on 2025-10-31 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0010_remove_avisosindexpage_mostrar_destaque_primeiro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avisospage',
            name='descricao',
            field=models.TextField(help_text='Breve descrição do conteúdo da página.', max_length=255, verbose_name='Descrição'),
        ),
    ]
