# Generated by Django 5.1.11 on 2025-11-03 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0007_merge_20251031_1153'),
        ('avisos', '0011_alter_avisospage_descricao'),
    ]

    operations = [
    ]
