# Generated by Django 5.1.13 on 2025-11-07 15:23

import datetime
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0012_merge_20251103_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avisospage',
            name='arquivos',
            field=wagtail.fields.StreamField([('arquivo', 0)], blank=True, block_lookup={0: ('blocks.models.EspecificDocumentChooserBlock', (), {'label': 'Arquivos', 'required': True})}, null=True, verbose_name='Arquivos'),
        ),
        migrations.AlterField(
            model_name='avisospage',
            name='data_publicacao',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Data de publicação'),
        ),
        migrations.AlterField(
            model_name='avisospage',
            name='sensivel_periodo_eleitoral',
            field=models.BooleanField(default=False, help_text='Marque se este conteúdo deve ser ocultado durante o período eleitoral.', verbose_name='Sensível ao período eleitoral'),
        ),
    ]
