# Generated by Django 5.1.13 on 2025-10-31 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_remove_documentospage_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentosindexpage',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='documentospage',
            name='subtitle',
        ),
    ]
