# Generated by Django 5.1.11 on 2025-07-21 15:20

import datetime
import django.db.models.deletion
import wagtail.contrib.routable_page.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaDoDiaPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(default=datetime.datetime.today, verbose_name='Data da Agenda')),
                ('compromissos', wagtail.fields.StreamField([('compromisso', 7)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Título do compromisso', 'max_length': 255, 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Nome da autoridade', 'max_length': 255, 'required': False}), 2: ('wagtail.blocks.TimeBlock', (), {'label': 'Hora início', 'required': True}), 3: ('wagtail.blocks.TimeBlock', (), {'label': 'Hora término', 'required': True}), 4: ('wagtail.blocks.TextBlock', (), {'label': 'Outros Participantes', 'required': False}), 5: ('wagtail.blocks.TextBlock', (), {'label': 'Pauta', 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Local do compromisso', 'max_length': 255, 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('title', 0), ('nome_autoridade', 1), ('inicio', 2), ('termino', 3), ('outros_participantes', 4), ('pauta', 5), ('local', 6)]], {})}, verbose_name='Compromissos do Dia')),
                ('nome_autoridade', models.CharField(blank=True, default='', max_length=255, verbose_name='Nome da Autoridade')),
                ('local_padrao', models.CharField(blank=True, default='', max_length=255, verbose_name='Local padrão do compromisso')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='AgendaIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='AgendaPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('descricao', models.TextField(blank=True, default='', verbose_name='Descrição')),
                ('orgao', models.CharField(blank=True, default='', max_length=255, verbose_name='Órgão')),
                ('nome_autoridade', models.CharField(blank=True, default='', max_length=255, verbose_name='Nome da Autoridade')),
                ('local_padrao', models.CharField(default='', max_length=255, null=True, verbose_name='Local padrão do compromisso')),
                ('brasao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Brasão')),
                ('imagem_destaque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagem destaque')),
            ],
            options={
                'verbose_name': 'Página de Agenda',
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, 'wagtailcore.page'),
        ),
    ]
