# Generated by Django 5.1.11 on 2025-10-01 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_agendadodiapage_descricao_agendadodiapage_images_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendadodiapage',
            name='images',
        ),
        migrations.RemoveField(
            model_name='agendapage',
            name='images',
        ),
        migrations.AddField(
            model_name='agendadodiapage',
            name='imagem_destaque',
            field=models.ForeignKey(blank=True, help_text='Imagem usada em destaque para SEO e redes sociais', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagem de Destaque'),
        ),
    ]
