# Generated by Django 5.1.11 on 2025-11-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_remove_agendadodiapage_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendadodiapage',
            name='data_final_recorrencia',
            field=models.DateField(blank=True, help_text='Deixe em branco se não houver data final definida', null=True, verbose_name='Data final da recorrência'),
        ),
        migrations.AddField(
            model_name='agendadodiapage',
            name='habilitar_recorrencia',
            field=models.BooleanField(default=False, help_text='Marque para ativar a recorrência para este compromisso', verbose_name='Habilitar recorrência'),
        ),
        migrations.AddField(
            model_name='agendadodiapage',
            name='intervalo_recorrencia',
            field=models.PositiveIntegerField(default=1, help_text='Quantidade de dias/meses/anos entre cada ocorrência', verbose_name='Intervalo de recorrência'),
        ),
        migrations.AddField(
            model_name='agendadodiapage',
            name='tipo_recorrencia',
            field=models.CharField(choices=[('none', 'Sem recorrência'), ('days', 'Recorrência por dias'), ('months', 'Recorrência por meses'), ('years', 'Recorrência por anos')], default='none', max_length=10, verbose_name='Tipo de recorrência'),
        ),
    ]
