# Generated by Django 5.1.11 on 2025-11-14 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_alter_agendadodiapage_descricao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendadodiapage',
            options={'verbose_name': 'Agenda do Dia'},
        ),
    ]
