# Generated by Django 5.1.11 on 2025-11-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_alter_agendadodiapage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendadodiapage',
            name='slug_base',
            field=models.SlugField(blank=True, default='', help_text='Slug original sem sufixos de recorrência (preenchido automaticamente)', max_length=255, verbose_name='Slug base'),
        ),
        migrations.AddField(
            model_name='agendadodiapage',
            name='titulo_base',
            field=models.CharField(blank=True, default='', help_text='Título original sem sufixos de recorrência (preenchido automaticamente)', max_length=255, verbose_name='Título base'),
        ),
    ]
