# Generated by Django 5.1.11 on 2025-11-17 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_agendadodiapage_slug_base_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendadodiapage',
            name='slug_base',
        ),
        migrations.RemoveField(
            model_name='agendadodiapage',
            name='titulo_base',
        ),
    ]
