# Generated by Django 5.1.14 on 2025-11-25 16:27

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgpd', '0001_initial'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='lgpdpage',
            name='banner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Banner da página'),
        ),
        migrations.AddField(
            model_name='lgpdpage',
            name='corpo',
            field=wagtail.fields.StreamField([('titulo_texto', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Título', 'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': 'Texto', 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('titulo', 0), ('texto', 1)]], {'label': 'Título e Texto'})}, null=True, verbose_name='Conteúdo da página'),
        ),
        migrations.AddField(
            model_name='lgpdpage',
            name='introducao',
            field=models.TextField(blank=True, help_text='Texto introdutório', verbose_name='Introdução'),
        ),
        migrations.AddField(
            model_name='lgpdpage',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, verbose_name='Subtítulo'),
        ),
    ]
