# Generated by Django 5.1.11 on 2025-10-24 12:15

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgpd', '0001_initial'),
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='LGPDPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('descricao', models.TextField(blank=True, help_text='Descrição da página para SEO e redes sociais', verbose_name='Descrição')),
                ('images', wagtail.fields.StreamField([('image', 0)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagem'})}, help_text='Imagens relacionadas à página', verbose_name='Imagens')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Subtítulo')),
                ('lgpd_text', models.TextField(blank=True, help_text='Texto sobre proteção de dados e privacidade', verbose_name='Texto LGPD')),
                ('corpo', wagtail.fields.StreamField([('titulo_texto', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Título', 'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': 'Texto', 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('titulo', 0), ('texto', 1)]], {'label': 'Título e Texto'})}, null=True, verbose_name='Conteúdo da página')),
                ('banner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Banner da página')),
            ],
            options={
                'verbose_name': 'LGPD',
                'verbose_name_plural': 'LGPD',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.DeleteModel(
            name='LGPD',
        ),
    ]
