# Generated by Django 5.1.11 on 2025-10-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgpd', '0003_remove_lgpdpage_images_lgpdpage_imagem_destaque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lgpdpage',
            name='lgpd_text',
        ),
        migrations.AddField(
            model_name='lgpdpage',
            name='introducao',
            field=models.TextField(blank=True, help_text='Texto introdutório', verbose_name='Introdução'),
        ),
    ]
