# Generated by Django 5.1.11 on 2025-11-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgpd', '0004_remove_lgpdpage_lgpd_text_lgpdpage_introducao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lgpdpage',
            name='descricao',
            field=models.TextField(blank=True, help_text='Descrição da página, utilizada em SEO e redes sociais', verbose_name='Descrição'),
        ),
    ]
