# Generated by Django 5.1.11 on 2025-11-17 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lgpd', '0006_missaovisaovalores'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MissaoVisaoValores',
        ),
    ]
