# Generated by Django 5.1.11 on 2025-11-14 16:06

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgpd', '0006_missaovisaovalores'),
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComissaoEtica',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('descricao', models.TextField(blank=True, help_text='Descrição da página, utilizada em SEO e redes sociais', verbose_name='Descrição')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Subtítulo')),
                ('introducao', models.TextField(blank=True, help_text='Texto introdutório', verbose_name='Introdução')),
                ('corpo', wagtail.fields.StreamField([('titulo_texto', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Título', 'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': 'Texto', 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('titulo', 0), ('texto', 1)]], {'label': 'Título e Texto'})}, null=True, verbose_name='Conteúdo da página')),
                ('banner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Banner da página')),
                ('imagem_destaque', models.ForeignKey(blank=True, help_text='Imagem usada em destaque para SEO e redes sociais', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagem de Destaque')),
            ],
            options={
                'verbose_name': 'Comissão de Ética',
                'verbose_name_plural': 'Comissões de Ética',
            },
            bases=('wagtailcore.page',),
        ),
    ]
