# Generated by Django 5.1.13 on 2025-10-23 11:47

# api/migrations/0002_create_integration_group.py

from django.db import migrations

def create_integration_group(apps, schema_editor):
    """
    Cria o grupo 'Usuário de integração' se ele não existir.
    """
    Group = apps.get_model('auth', 'Group')
    Group.objects.get_or_create(name='Usuário de integração')


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RunPython(create_integration_group),
    ]

