# Generated by Django 5.1.13 on 2025-10-23 12:36

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_create_integration_group'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationUser',
            fields=[
            ],
            options={
                'verbose_name': 'Usuário de Integração',
                'verbose_name_plural': 'Usuários de Integração',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
