# Generated by Django 5.1.9 on 2025-07-01 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtaildocs', '0014_alter_document_file_size'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PloneImportedFile',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtaildocs.document')),
                ('plone_node_id', models.UUIDField(blank=True, db_index=True, help_text='ID do nó do arquivo no Plone.', null=True, unique=True)),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
                'abstract': False,
            },
            bases=('wagtaildocs.document',),
        ),
        migrations.CreateModel(
            name='PloneImportedImage',
            fields=[
                ('image_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailimages.image')),
                ('plone_node_id', models.UUIDField(blank=True, db_index=True, help_text='ID do nó da imagem no Plone.', null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailimages.image',),
        ),
    ]
