# Generated by Django 5.1.9 on 2025-07-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plone_migration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ploneimportedfile',
            name='slug_plone',
            field=models.CharField(blank=True, help_text='Slug original do Plone.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ploneimportedimage',
            name='slug_plone',
            field=models.CharField(blank=True, help_text='Slug original do Plone.', max_length=255, null=True),
        ),
    ]
