# Generated by Django 5.1.14 on 2025-11-25 16:27

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responsaveis', '0002_remove_comofuncionapage_body_and_more'),
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsaveisPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('descricao', models.TextField(blank=True, help_text='Descrição da página, utilizada em SEO e redes sociais', verbose_name='Descrição')),
                ('conteudo', wagtail.fields.StreamField([('hero', 7), ('features_grid', 14), ('richtext_section', 17), ('timeline', 24), ('faq', 30), ('cta_section', 38), ('testimonial', 45)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Título principal do hero (ex: NEUROATHENA)', 'max_length': 100, 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Subtítulo descritivo (ex: Sistema Multimodal de Triagem...)', 'max_length': 200, 'required': True}), 2: ('wagtail.blocks.TextBlock', (), {'help_text': 'Descrição detalhada do sistema', 'max_length': 500, 'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'default': 'Acessar Painel', 'help_text': 'Texto do botão principal', 'max_length': 50, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'default': '/painel/', 'help_text': 'URL do botão principal', 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'default': 'Admin Wagtail', 'help_text': 'Texto do botão secundário', 'max_length': 50, 'required': False}), 6: ('wagtail.blocks.URLBlock', (), {'default': '/cms/', 'help_text': 'URL do botão secundário', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('titulo', 0), ('subtitulo', 1), ('descricao', 2), ('cta_primario_texto', 3), ('cta_primario_url', 4), ('cta_secundario_texto', 5), ('cta_secundario_url', 6)]], {}), 8: ('wagtail.blocks.CharBlock', (), {'default': 'Recursos Principais', 'help_text': 'Título da seção de funcionalidades', 'max_length': 100, 'required': True}), 9: ('wagtail.blocks.CharBlock', (), {'help_text': 'Emoji do ícone (ex: 🧠, 📊, 👥)', 'max_length': 10, 'required': True}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': 'Título da funcionalidade', 'max_length': 100, 'required': True}), 11: ('wagtail.blocks.TextBlock', (), {'help_text': 'Descrição breve da funcionalidade', 'max_length': 300, 'required': True}), 12: ('wagtail.blocks.StructBlock', [[('icone', 9), ('titulo', 10), ('descricao', 11)]], {}), 13: ('wagtail.blocks.ListBlock', (12,), {'help_text': 'Cards de funcionalidades (recomendado: 3, 6 ou 9 para grid)', 'max_num': 9, 'min_num': 1}), 14: ('wagtail.blocks.StructBlock', [[('titulo_secao', 8), ('funcionalidades', 13)]], {}), 15: ('wagtail.blocks.CharBlock', (), {'label': 'Título', 'max_length': 200, 'required': False}), 16: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'h4', 'bold', 'italic', 'link', 'ul', 'ol', 'hr', 'document-link', 'image', 'embed'], 'label': 'Conteúdo'}), 17: ('wagtail.blocks.StructBlock', [[('titulo', 15), ('conteudo', 16)]], {}), 18: ('wagtail.blocks.CharBlock', (), {'label': 'Título da Seção', 'max_length': 200, 'required': False}), 19: ('wagtail.blocks.CharBlock', (), {'help_text': "Ex: '2023', '2024'", 'label': 'Ano', 'max_length': 10, 'required': False}), 20: ('wagtail.blocks.CharBlock', (), {'label': 'Título', 'max_length': 100}), 21: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'label': 'Descrição'}), 22: ('wagtail.blocks.StructBlock', [[('ano', 19), ('titulo', 20), ('descricao', 21)]], {}), 23: ('wagtail.blocks.ListBlock', (22,), {'label': 'Eventos', 'max_num': 10, 'min_num': 2}), 24: ('wagtail.blocks.StructBlock', [[('titulo', 18), ('eventos', 23)]], {}), 25: ('wagtail.blocks.CharBlock', (), {'default': 'Perguntas Frequentes', 'label': 'Título da Seção', 'max_length': 200}), 26: ('wagtail.blocks.CharBlock', (), {'label': 'Pergunta', 'max_length': 200}), 27: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'label': 'Resposta'}), 28: ('wagtail.blocks.StructBlock', [[('question', 26), ('answer', 27)]], {}), 29: ('wagtail.blocks.ListBlock', (28,), {'label': 'Perguntas e Respostas', 'min_num': 1}), 30: ('wagtail.blocks.StructBlock', [[('title', 25), ('items', 29)]], {}), 31: ('wagtail.blocks.CharBlock', (), {'label': 'Título', 'max_length': 200}), 32: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'label': 'Texto', 'required': False}), 33: ('wagtail.blocks.URLBlock', (), {'label': 'Link Botão Primário'}), 34: ('wagtail.blocks.CharBlock', (), {'label': 'Texto Botão Primário', 'max_length': 50}), 35: ('wagtail.blocks.URLBlock', (), {'label': 'Link Botão Secundário', 'required': False}), 36: ('wagtail.blocks.CharBlock', (), {'label': 'Texto Botão Secundário', 'max_length': 50, 'required': False}), 37: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagem de Fundo', 'required': False}), 38: ('wagtail.blocks.StructBlock', [[('titulo', 31), ('texto', 32), ('link_primario', 33), ('texto_primario', 34), ('link_secundario', 35), ('texto_secundario', 36), ('imagem_fundo', 37)]], {}), 39: ('wagtail.blocks.CharBlock', (), {'label': 'Nome', 'max_length': 100}), 40: ('wagtail.blocks.CharBlock', (), {'label': 'Função/Cargo', 'max_length': 100, 'required': False}), 41: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Foto', 'required': False}), 42: ('wagtail.blocks.TextBlock', (), {'label': 'Depoimento', 'max_length': 500}), 43: ('wagtail.blocks.StructBlock', [[('nome', 39), ('cargo', 40), ('foto', 41), ('texto', 42)]], {}), 44: ('wagtail.blocks.ListBlock', (43,), {'label': 'Depoimentos', 'max_num': 6, 'min_num': 1}), 45: ('wagtail.blocks.StructBlock', [[('titulo', 18), ('depoimentos', 44)]], {})}, verbose_name='Conteúdo da página')),
                ('imagem_destaque', models.ForeignKey(blank=True, help_text='Imagem usada em destaque para SEO e redes sociais', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagem de Destaque')),
            ],
            options={
                'verbose_name': 'Página Para Famílias',
                'verbose_name_plural': 'Páginas Para Famílias',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.DeleteModel(
            name='PararesponsaveisPage',
        ),
    ]
