# Generated by Django 5.1.14 on 2025-11-24 19:31

import datetime
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.contrib.routable_page.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaNoticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, unique=True, verbose_name='Nome da Categoria')),
            ],
            options={
                'verbose_name': 'Categoria de Conteúdo',
                'verbose_name_plural': 'Categorias de Conteúdos',
            },
        ),
        migrations.CreateModel(
            name='NoticiasIndexPages',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', models.TextField(default='Todas as Notícias', help_text='Texto para o topo da Página de Índice.')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='NoticiasPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('subtitle', models.TextField(blank=True, max_length=211, verbose_name='Subtítulo')),
                ('descricao', models.TextField(help_text='Breve descrição do conteúdo da página.', max_length=211, verbose_name='Descrição')),
                ('data_publicacao', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Data de publicação deste conteúdo')),
                ('body', wagtail.fields.StreamField([('paragraph_block', 0), ('image_block', 3), ('video_block', 6), ('table_block', 7)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'description': 'Um parágrafo de texto rico', 'icon': 'pilcrow', 'label': 'Texto de Parágrafo', 'preview_value': '\n            <h2>Our bread pledge</h2>\n            <p>As a bakery, <b>breads</b> have <i>always</i> been in our hearts.\n            <a href="https://en.wikipedia.org/wiki/Staple_food">Staple foods</a>\n            are essential for society, and – bread is the tastiest of all.\n            We love to transform batters and doughs into baked goods with a firm\n            dry crust and fluffy center.</p>\n            ', 'template': 'blocks/paragraph_block.html'}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('image', 1), ('caption', 2), ('attribution', 2)]], {'label': 'Bloco de Imagem com Legenda'}), 4: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': True}), 5: ('wagtail.blocks.URLBlock', (), {'label': 'URL do vídeo (iframe YouTube)', 'required': True}), 6: ('wagtail.blocks.StructBlock', [[('titulo', 4), ('srcIframe', 5)]], {'label': 'Bloco de Vídeo'}), 7: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'description': 'Uma tabela de dados', 'help_text': 'Insira os dados da tabela', 'icon': 'table', 'label': 'Bloco de Tabela', 'template': 'blocks/table.html'})}, null=True, verbose_name='Corpo da Página')),
                ('body_migrated', models.TextField(blank=True, help_text='Usado apenas para conteúdo do antigo site Plone.', null=True)),
                ('plone_node_id', models.TextField(blank=True, db_index=True, help_text='ID do nó no Plone, usado para identificar a página migrada.', null=True, unique=True)),
                ('sensivel_periodo_eleitoral', models.BooleanField(default=False, help_text='Marque se este conteúdo deve ser ocultado ou tratado de forma especial durante o período eleitoral.', verbose_name='Conteúdo sensível ao período eleitoral')),
                ('images', wagtail.fields.StreamField([('imagem', 0)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagem do conteúdo', 'required': True})}, null=True, verbose_name='Coleção de Imagens')),
                ('arquivos', wagtail.fields.StreamField([('arquivo', 0)], blank=True, block_lookup={0: ('blocks.models.EspecificDocumentChooserBlock', (), {'label': 'Arquivos', 'required': True})}, null=True, verbose_name='Arquivos relacionados')),
                ('slideshow_imagens', models.BooleanField(default=False, help_text='Marque para exibir as imagens como slideshow na página do conteúdo.', verbose_name='Ativar slideshow de imagens')),
                ('nao_exibir_lista_de_arquivos', models.BooleanField(default=False, help_text='Marque para não exibir a lista de arquivos na página do conteúdo.', verbose_name='Não exibir lista de arquivos')),
                ('destaque', models.BooleanField(default=False, help_text='Marque se este conteúdo deve ser exibido em destaque na página inicial ou em listas de conteúdos. Só pode ser cadastrado 6 conteúdos em destaque.', verbose_name='Conteúdo em destaque')),
                ('titulo_ultimas', models.CharField(blank=True, default='Últimas notícias', help_text='Título exibido na seção de itens recentes. Se deixado em branco, será usado o título padrão configurado.', max_length=70, verbose_name='Título da seção de itens recentes')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='noticias.categorianoticias', verbose_name='Categoria')),
                ('imagem_destaque', models.ForeignKey(blank=True, help_text='Imagem usada em destaque para SEO e redes sociais', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagem de Destaque')),
            ],
            options={
                'verbose_name': 'Página de Conteúdo',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NoticiasPageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='noticias.noticiaspage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='noticiaspage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='noticias.NoticiasPageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
