# Generated by Django 5.1.9 on 2025-06-04 14:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticiaspage',
            name='data_publicacao',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Data de publicação da notícias'),
        ),
    ]
