# Generated by Django 5.1.14 on 2025-11-24 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticiaspage',
            name='sensivel_periodo_eleitoral',
        ),
    ]
