# Generated by Django 5.1.9 on 2025-06-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_alter_noticiaspage_data_publicacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticiaspage',
            name='sensivel_periodo_eleitoral',
            field=models.BooleanField(default=False, help_text='Marque se esta notícia deve ser ocultada ou tratada de forma especial durante o período eleitoral.', verbose_name='Notícia sensível ao período eleitoral'),
        ),
    ]
