# Generated by Django 5.1.9 on 2025-06-16 16:55

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_noticiaspage_sensivel_periodo_eleitoral'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticiaspage',
            name='image',
        ),
        migrations.AddField(
            model_name='noticiaspage',
            name='images',
            field=wagtail.fields.StreamField([('imagem', 0)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagem da notícia', 'required': True})}, null=True, verbose_name='Coleção de Imagens'),
        ),
        migrations.AddField(
            model_name='noticiaspage',
            name='slideshow_imagens',
            field=models.BooleanField(default=False, help_text='Marque para exibir as imagens como slideshow na página da notícia.', verbose_name='Ativar slideshow de imagens'),
        ),
    ]
