# Generated by Django 5.1.9 on 2025-06-27 13:08

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0004_remove_noticiaspage_image_noticiaspage_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticiaspage',
            name='arquivos',
            field=wagtail.fields.StreamField([('arquivo', 0)], blank=True, block_lookup={0: ('blocks.models.EspecificDocumentChooserBlock', (), {'allowed_extensions': ['.txt'], 'label': 'Arquivo PDF', 'required': True})}, null=True, verbose_name='Arquivos da notícia'),
        ),
        migrations.AddField(
            model_name='noticiaspage',
            name='nao_exibir_lista_de_arquivos',
            field=models.BooleanField(default=False, help_text='Marque para não exibir a lista de arquivos na página da notícia.', verbose_name='Não exibir lista de arquivos'),
        ),
    ]
