# Generated by Django 5.1.9 on 2025-06-27 13:21

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0005_noticiaspage_arquivos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticiaspage',
            name='arquivos',
            field=wagtail.fields.StreamField([('arquivo', 0)], blank=True, block_lookup={0: ('blocks.models.EspecificDocumentChooserBlock', (), {'label': 'Arquivos', 'required': True})}, null=True, verbose_name='Arquivos da notícia'),
        ),
    ]
