# Generated by Django 5.1.9 on 2025-07-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0006_alter_noticiaspage_arquivos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticiaspage',
            name='plone_node_id',
            field=models.TextField(blank=True, db_index=True, help_text='ID do nó no Plone, usado para identificar a página migrada.', null=True, unique=True),
        )
    ]
