# Generated by Django 5.1.9 on 2025-07-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0007_alter_noticiaspage_plone_node_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticiaspage',
            name='descricao',
            field=models.TextField(blank=True, help_text='Breve descrição do conteúdo da página.', verbose_name='Descrição'),
        ),
    ]
