# Generated by Django 5.1.9 on 2025-07-04 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0009_alter_noticiaspage_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticiaspage',
            options={'permissions': [('view_conteudo_migrado', 'Pode ver conteúdo migrado (body_migrated)')]},
        ),
    ]
