# Generated by Django 5.1.9 on 2025-07-02 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0009_alter_noticiaspage_plone_node_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticiaspage',
            name='plone_node_id',
        ),
    ]
