# Generated by Django 5.1.9 on 2025-07-04 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0010_alter_noticiaspage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticiaspage',
            options={'default_permissions': [], 'permissions': [('view_conteudo_migrado', 'Pode ver conteúdo migrado (body_migrated)')]},
        ),
    ]
