# Generated by Django 5.1.11 on 2025-07-16 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0014_alter_noticiaspage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticiaspage',
            name='data_publicacao',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Data de publicação da notícia'),
        ),
    ]
