# Generated by Django 5.1.11 on 2025-08-11 12:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0014_alter_noticiaspage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticiaspage',
            name='descricao',
            field=models.TextField(blank=True, help_text='Breve descrição do conteúdo da página.', validators=[django.core.validators.MaxLengthValidator(230)], verbose_name='Descrição'),
        ),
    ]
