# Generated by Django 5.1.11 on 2025-08-22 13:05

from django.db import migrations


class Migration(migrations.Migration):
    """Merge de branches paralelas"""

    dependencies = [
        ('noticias', '0015_alter_noticiaspage_data_publicacao'),
        ('noticias', '0015a_alter_noticiaspage_descricao'),
    ]

    operations = [
    ]
