# Generated by Django 5.1.11 on 2025-08-28 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0016_merge_20250822_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticiasindexpages',
            name='introduction',
            field=models.TextField(blank=True, default='Todas as Notícias', help_text='Texto para o topo da notícia'),
        ),
    ]
