# Generated by Django 5.1.11 on 2025-09-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0017_alter_noticiasindexpages_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticiasindexpages',
            name='introduction',
            field=models.TextField(default='Todas as Notícias', help_text='Texto para o topo da notícia'),
        ),
    ]
