# Generated by Django 5.1.11 on 2025-09-08 14:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0018_alter_noticiasindexpages_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticiaspage',
            name='descricao',
            field=models.TextField(help_text='Breve descrição do conteúdo da página.', validators=[django.core.validators.MaxLengthValidator(230)], verbose_name='Descrição'),
        ),
    ]
