# Generated by Django 5.1.11 on 2025-09-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0019_alter_noticiaspage_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticiaspage',
            name='descricao',
            field=models.CharField(help_text='Breve descrição do conteúdo da página.', max_length=220, verbose_name='Descrição'),
        ),
    ]
