# Generated by Django 5.1.11 on 2025-09-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0020_alter_noticiaspage_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticiaspage',
            name='destaque',
            field=models.BooleanField(default=False, help_text='Marque se esta notícia deve ser exibida em destaque na página inicial ou em listas de notícias. Só pode ser cadastrado 6 noticias  em destaque.', verbose_name='Notícia em destaque'),
        ),
        migrations.AlterField(
            model_name='noticiaspage',
            name='descricao',
            field=models.TextField(help_text='Breve descrição do conteúdo da página.', max_length=211, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='noticiaspage',
            name='subtitle',
            field=models.TextField(blank=True, max_length=211, verbose_name='Subtítulo'),
        ),
    ]
