# Generated by Django 5.1.11 on 2025-09-24 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0021_noticiaspage_destaque_alter_noticiaspage_descricao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticiaspage',
            options={'default_permissions': [], 'permissions': [('view_conteudo_migrado', 'Pode ver conteúdo migrado (body_migrado)')]},
        ),
    ]
