# Generated by Django 5.1.13 on 2025-10-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0022_categorianoticias_alter_noticiaspage_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorianoticias',
            name='nome',
            field=models.CharField(max_length=40, unique=True, verbose_name='Nome da Categoria'),
        ),
    ]
