# Generated by Django 5.1.11 on 2025-09-24 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0022_alter_noticiaspage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticiaspage',
            options={'default_permissions': [], 'permissions': [('view_conteudo_migrado', 'Pode ver conteúdo migrado (body_migrated)')]},
        ),
    ]
