# Generated by Django 5.1.11 on 2025-09-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0023_alter_noticiaspage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticiaspage',
            name='descricao',
            field=models.TextField(help_text='Breve descrição do conteúdo da página.', max_length=211, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='noticiaspage',
            name='subtitle',
            field=models.TextField(blank=True, max_length=211, verbose_name='Subtítulo'),
        ),
    ]
