# Generated by Django 5.1.13 on 2025-10-31 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0022_noticiaspage_imagem_destaque'),
        ('noticias', '0023_alter_categorianoticias_nome'),
    ]

    operations = [
    ]
