# Generated by Django 5.1.13 on 2025-11-17 18:22

import datetime
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0024_merge_20251031_1153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorianoticias',
            options={'verbose_name': 'Categoria de Conteúdo', 'verbose_name_plural': 'Categorias de Conteúdos'},
        ),
        migrations.AlterModelOptions(
            name='noticiaspage',
            options={'verbose_name': 'Página de Conteúdo'},
        ),
        migrations.AddField(
            model_name='noticiaspage',
            name='titulo_ultimas',
            field=models.CharField(blank=True, help_text='Título exibido na seção de itens recentes. Se deixado em branco, será usado o título padrão configurado.', max_length=70, verbose_name='Título da seção de itens recentes'),
        ),
        migrations.AlterField(
            model_name='noticiasindexpages',
            name='introduction',
            field=models.TextField(default='Todas as Notícias', help_text='Texto para o topo da Página de Índice.'),
        ),
        migrations.AlterField(
            model_name='noticiaspage',
            name='arquivos',
            field=wagtail.fields.StreamField([('arquivo', 0)], blank=True, block_lookup={0: ('blocks.models.EspecificDocumentChooserBlock', (), {'label': 'Arquivos', 'required': True})}, null=True, verbose_name='Arquivos relacionados'),
        ),
        migrations.AlterField(
            model_name='noticiaspage',
            name='data_publicacao',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Data de publicação deste conteúdo'),
        ),
        migrations.AlterField(
            model_name='noticiaspage',
            name='destaque',
            field=models.BooleanField(default=False, help_text='Marque se este conteúdo deve ser exibido em destaque na página inicial ou em listas de conteúdos. Só pode ser cadastrado 6 conteúdos em destaque.', verbose_name='Conteúdo em destaque'),
        ),
        migrations.AlterField(
            model_name='noticiaspage',
            name='images',
            field=wagtail.fields.StreamField([('imagem', 0)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagem do conteúdo', 'required': True})}, null=True, verbose_name='Coleção de Imagens'),
        ),
        migrations.AlterField(
            model_name='noticiaspage',
            name='nao_exibir_lista_de_arquivos',
            field=models.BooleanField(default=False, help_text='Marque para não exibir a lista de arquivos na página do conteúdo.', verbose_name='Não exibir lista de arquivos'),
        ),
        migrations.AlterField(
            model_name='noticiaspage',
            name='sensivel_periodo_eleitoral',
            field=models.BooleanField(default=False, help_text='Marque se este conteúdo deve ser ocultado ou tratado de forma especial durante o período eleitoral.', verbose_name='Conteúdo sensível ao período eleitoral'),
        ),
        migrations.AlterField(
            model_name='noticiaspage',
            name='slideshow_imagens',
            field=models.BooleanField(default=False, help_text='Marque para exibir as imagens como slideshow na página do conteúdo.', verbose_name='Ativar slideshow de imagens'),
        ),
    ]
