# Generated by Django 5.1.11 on 2025-11-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0025_alter_categorianoticias_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticiaspage',
            name='titulo_ultimas',
            field=models.CharField(blank=True, default='Últimas notícias', help_text='Título exibido na seção de itens recentes. Se deixado em branco, será usado o título padrão configurado.', max_length=70, verbose_name='Título da seção de itens recentes'),
        ),
    ]
