# Generated by Django 5.1.11 on 2025-10-22 17:57

import datetime
import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinhaDoTempoIndex',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Página de Index da Linha do Tempo',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='LinhaDoTempoPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('descricao', models.TextField(blank=True, help_text='Descrição da página para SEO e redes sociais', verbose_name='Descrição')),
                ('images', wagtail.fields.StreamField([('image', 0)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagem'})}, help_text='Imagens relacionadas à página', verbose_name='Imagens')),
            ],
            options={
                'verbose_name': 'Página da Linha do Tempo',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CardLinhaDoTempoPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('descricao', models.TextField(blank=True, help_text='Descrição da página para SEO e redes sociais', verbose_name='Descrição')),
                ('images', wagtail.fields.StreamField([('image', 0)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagem'})}, help_text='Imagens relacionadas à página', verbose_name='Imagens')),
                ('titulo', models.CharField(blank=True, help_text='Título da página do card da linha do tempo', max_length=255, null=True, verbose_name='Título')),
                ('data_evento', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Data do evento')),
                ('texto_alternativo', models.TextField(blank=True, max_length=255, null=True, verbose_name='Texto alternativo da imagem')),
                ('descricao_completa', wagtail.fields.StreamField([('paragraph', 0)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'description': 'A rich text paragraph', 'icon': 'pilcrow', 'preview_value': '\n                        <h2>Our bread pledge</h2>\n                        <p>As a bakery, <b>breads</b> have <i>always</i> been in our hearts.\n                        <a href="https://en.wikipedia.org/wiki/Staple_food">Staple foods</a>\n                        are essential for society, and – bread is the tastiest of all.\n                        We love to transform batters and doughs into baked goods with a firm\n                        dry crust and fluffy center.</p>\n                        ', 'template': 'blocks/paragraph_block.html'})}, null=True, verbose_name='Descrição')),
                ('data_publicacao', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Data de publicação do aviso')),
                ('imagem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.image', verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Página de Card da Linha do Tempo',
            },
            bases=('wagtailcore.page',),
        ),
    ]
