# Generated by Django 5.1.11 on 2025-11-18 18:51

import datetime
import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinhaDoTempoIndex',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Página de Listagem de Diferentes Linhas do Tempo',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CardLinhaDoTempoPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('descricao', models.TextField(blank=True, help_text='Descrição da página, utilizada em SEO e redes sociais', verbose_name='Descrição')),
                ('data_evento', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Data do evento')),
                ('images', wagtail.fields.StreamField([('imagem', 0)], block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagem do conteúdo', 'required': True})}, help_text='Adicione uma ou mais imagens para esta linha do tempo.', verbose_name='Coleção de Imagens')),
                ('descricao_linha_do_tempo', wagtail.fields.StreamField([('paragraph', 0)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'description': 'A rich text paragraph', 'icon': 'pilcrow', 'preview_value': '\n                        <h2>Our bread pledge</h2>\n                        <p>As a bakery, <b>breads</b> have <i>always</i> been in our hearts.\n                        <a href="https://en.wikipedia.org/wiki/Staple_food">Staple foods</a>\n                        are essential for society, and – bread is the tastiest of all.\n                        We love to transform batters and doughs into baked goods with a firm\n                        dry crust and fluffy center.</p>\n                        ', 'template': 'blocks/paragraph_block.html'})}, verbose_name='Descrição de marco da linha do tempo')),
                ('exibir_toda_a_imagem', models.BooleanField(default=False, help_text='Se marcado, a imagem será exibida em sua forma original. Caso contrário, será exibida em seu tamanho original.', verbose_name='Exibir toda a imagem')),
                ('lista_videos', wagtail.fields.StreamField([('lista_videos', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Vídeos', 'required': False}), 1: ('wagtail.blocks.URLBlock', (), {'label': "URL do 'Ver todos'", 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': True}), 3: ('wagtail.blocks.URLBlock', (), {'label': 'URL do vídeo (iframe YouTube)', 'required': True}), 4: ('wagtail.blocks.StructBlock', [[('titulo', 2), ('srcIframe', 3)]], {}), 5: ('wagtail.blocks.ListBlock', (4,), {'label': 'Vídeos', 'max_num': 3}), 6: ('wagtail.blocks.StructBlock', [[('titulo', 0), ('ver_todos_url', 1), ('videos', 5)]], {})}, help_text='Adicione vídeos à página do card de linha do tempo', null=True, verbose_name='Lista de vídeos')),
                ('data_publicacao', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Data de publicação do aviso')),
                ('imagem_destaque', models.ForeignKey(blank=True, help_text='Imagem usada em destaque para SEO e redes sociais', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagem de Destaque')),
            ],
            options={
                'verbose_name': 'Página de Card da Linha do Tempo',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='LinhaDoTempoPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('descricao', models.TextField(blank=True, help_text='Descrição da página, utilizada em SEO e redes sociais', verbose_name='Descrição')),
                ('imagem_destaque', models.ForeignKey(blank=True, help_text='Imagem usada em destaque para SEO e redes sociais', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagem de Destaque')),
            ],
            options={
                'verbose_name': 'Página da Linha do Tempo',
            },
            bases=('wagtailcore.page',),
        ),
    ]
