# Generated by Django 5.1.11 on 2025-11-19 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linhasdotempo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardlinhadotempopage',
            name='exibir_toda_a_imagem',
        ),
    ]
