# Generated by Django 5.1.11 on 2025-10-24 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linhasdotempo', '0002_remove_cardlinhadotempopage_titulo'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linhadotempoindex',
            options={'verbose_name': 'Página de Listagem de Diferentes Linhas do Tempo'},
        ),
        migrations.RemoveField(
            model_name='cardlinhadotempopage',
            name='images',
        ),
        migrations.RemoveField(
            model_name='linhadotempopage',
            name='images',
        ),
        migrations.AddField(
            model_name='cardlinhadotempopage',
            name='imagem_destaque',
            field=models.ForeignKey(blank=True, help_text='Imagem usada em destaque para SEO e redes sociais', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagem de Destaque'),
        ),
        migrations.AddField(
            model_name='linhadotempopage',
            name='imagem_destaque',
            field=models.ForeignKey(blank=True, help_text='Imagem usada em destaque para SEO e redes sociais', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagem de Destaque'),
        ),
    ]
