# Generated by Django 5.1.12 on 2025-11-06 14:07

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linhasdotempo', '0003_alter_linhadotempoindex_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardlinhadotempopage',
            name='lista_videos',
            field=wagtail.fields.StreamField([('lista_videos', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Vídeos', 'required': False}), 1: ('wagtail.blocks.URLBlock', (), {'label': "URL do 'Ver todos'", 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': True}), 3: ('wagtail.blocks.URLBlock', (), {'label': 'URL do vídeo (iframe YouTube)', 'required': True}), 4: ('wagtail.blocks.StructBlock', [[('titulo', 2), ('srcIframe', 3)]], {}), 5: ('wagtail.blocks.ListBlock', (4,), {'label': 'Vídeos', 'max_num': 3}), 6: ('wagtail.blocks.StructBlock', [[('titulo', 0), ('ver_todos_url', 1), ('videos', 5)]], {})}, help_text='Adicione vídeos à página do card de linha do tempo', null=True, verbose_name='Lista de vídeos'),
        ),
    ]
