# Generated by Django 5.1.11 on 2025-11-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linhasdotempo', '0004_rename_descricao_to_descricao_linha_do_tempo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardlinhadotempopage',
            name='descricao',
            field=models.TextField(blank=True, help_text='Descrição da página para SEO e redes sociais', verbose_name='Descrição'),
        ),
    ]
