# Generated by Django 5.1.11 on 2025-11-12 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linhasdotempo', '0004_cardlinhadotempopage_lista_videos'),
        ('linhasdotempo', '0005_cardlinhadotempopage_descricao'),
    ]

    operations = [
    ]
