# Generated by Django 5.1.11 on 2025-11-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linhasdotempo', '0006_merge_20251112_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardlinhadotempopage',
            name='descricao',
            field=models.TextField(blank=True, help_text='Descrição da página, utilizada em SEO e redes sociais', verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='linhadotempopage',
            name='descricao',
            field=models.TextField(blank=True, help_text='Descrição da página, utilizada em SEO e redes sociais', verbose_name='Descrição'),
        ),
    ]
