# Generated by Django 5.1.12 on 2025-11-13 19:35

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linhasdotempo', '0007_alter_cardlinhadotempopage_descricao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardlinhadotempopage',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='cardlinhadotempopage',
            name='texto_alternativo',
        ),
        migrations.AddField(
            model_name='cardlinhadotempopage',
            name='imagens',
            field=wagtail.fields.StreamField([('imagem', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagem', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Texto descritivo para acessibilidade (será usado como alt text)', 'label': 'Texto alternativo', 'max_length': 255, 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('alt_text', 1)]], {'icon': 'image', 'label': 'Imagem'})}, help_text='Adicione uma ou mais imagens para esta linha do tempo.', null=True, verbose_name='Coleção de Imagens'),
        ),
    ]
