# Generated by Django 5.1.13 on 2025-11-03 16:01

import datetime
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.contrib.routable_page.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='DicasPresidenteIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', models.TextField(blank=True, help_text='Texto de apresentação no topo da página.', verbose_name='Introdução')),
                ('mensagem_presidente', models.TextField(blank=True, help_text='Mensagem introdutória do presidente (aparece em destaque).', verbose_name='Mensagem do Presidente')),
                ('mostrar_filtro_tipo', models.BooleanField(default=True, help_text='Permite filtrar dicas por tipo (mensagem, recomendação, etc).', verbose_name='Mostrar filtro por tipo')),
                ('foto_presidente', models.ForeignKey(blank=True, help_text='Foto para o banner da página.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Foto do Presidente')),
            ],
            options={
                'verbose_name': 'Página de Índice - Dicas do Presidente',
                'verbose_name_plural': 'Páginas de Índice - Dicas do Presidente',
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='DicasPresidentePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('tipo_dica', models.CharField(choices=[('mensagem', 'Mensagem Pessoal'), ('recomendacao', 'Recomendação/Estudo'), ('noticia_interna', 'Notícia Interna'), ('galeria', 'Galeria/Bastidores'), ('frase', 'Frase da Semana')], default='mensagem', help_text='Selecione o tipo de conteúdo desta dica.', max_length=20, verbose_name='Tipo de Dica')),
                ('descricao', models.TextField(help_text='Breve descrição ou resumo do conteúdo (aparece nas listagens).', max_length=255, verbose_name='Descrição/Resumo')),
                ('data_publicacao', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Data de publicação')),
                ('destaque', models.BooleanField(default=False, help_text='Marque para exibir esta dica em destaque na página principal.', verbose_name='Dica em destaque')),
                ('texto_mensagem', wagtail.fields.StreamField([('paragraph_block', 0), ('image_block', 3), ('video_block', 6), ('table_block', 7)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'description': 'Um parágrafo de texto rico', 'icon': 'pilcrow', 'label': 'Texto de Parágrafo', 'preview_value': '\n            <h2>Our bread pledge</h2>\n            <p>As a bakery, <b>breads</b> have <i>always</i> been in our hearts.\n            <a href="https://en.wikipedia.org/wiki/Staple_food">Staple foods</a>\n            are essential for society, and – bread is the tastiest of all.\n            We love to transform batters and doughs into baked goods with a firm\n            dry crust and fluffy center.</p>\n            ', 'template': 'blocks/paragraph_block.html'}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('image', 1), ('caption', 2), ('attribution', 2)]], {'label': 'Bloco de Imagem com Legenda'}), 4: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': True}), 5: ('wagtail.blocks.URLBlock', (), {'label': 'URL do vídeo (iframe YouTube)', 'required': True}), 6: ('wagtail.blocks.StructBlock', [[('titulo', 4), ('srcIframe', 5)]], {'label': 'Bloco de Vídeo'}), 7: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'description': 'Uma tabela de dados', 'help_text': 'Insira os dados da tabela', 'icon': 'table', 'label': 'Bloco de Tabela', 'template': 'blocks/table.html'})}, help_text='Mensagem motivacional ou comunicado do presidente.', null=True, verbose_name='Texto da Mensagem')),
                ('assinatura', models.CharField(blank=True, help_text="Ex: 'João Silva, Presidente'", max_length=100, verbose_name='Assinatura')),
                ('tipo_recomendacao', models.CharField(blank=True, choices=[('artigo', 'Artigo'), ('video', 'Vídeo'), ('podcast', 'Podcast'), ('livro', 'Livro'), ('estudo', 'Estudo/Relatório')], help_text='Tipo de conteúdo recomendado.', max_length=20, verbose_name='Tipo de Recomendação')),
                ('link_externo', models.URLField(blank=True, help_text='URL do artigo, vídeo, livro ou estudo recomendado.', verbose_name='Link Externo')),
                ('motivo_recomendacao', models.TextField(blank=True, help_text='Breve explicação do presidente sobre a recomendação.', verbose_name='Por que recomendo')),
                ('categoria_noticia', models.CharField(blank=True, choices=[('conquista', 'Conquista'), ('meta', 'Meta Alcançada'), ('evento', 'Evento'), ('comunicado', 'Comunicado Oficial')], help_text='Tipo de notícia interna.', max_length=20, verbose_name='Categoria da Notícia')),
                ('body', wagtail.fields.StreamField([('paragraph_block', 0), ('image_block', 3), ('video_block', 6), ('table_block', 7)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'description': 'Um parágrafo de texto rico', 'icon': 'pilcrow', 'label': 'Texto de Parágrafo', 'preview_value': '\n            <h2>Our bread pledge</h2>\n            <p>As a bakery, <b>breads</b> have <i>always</i> been in our hearts.\n            <a href="https://en.wikipedia.org/wiki/Staple_food">Staple foods</a>\n            are essential for society, and – bread is the tastiest of all.\n            We love to transform batters and doughs into baked goods with a firm\n            dry crust and fluffy center.</p>\n            ', 'template': 'blocks/paragraph_block.html'}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('image', 1), ('caption', 2), ('attribution', 2)]], {'label': 'Bloco de Imagem com Legenda'}), 4: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': True}), 5: ('wagtail.blocks.URLBlock', (), {'label': 'URL do vídeo (iframe YouTube)', 'required': True}), 6: ('wagtail.blocks.StructBlock', [[('titulo', 4), ('srcIframe', 5)]], {'label': 'Bloco de Vídeo'}), 7: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'description': 'Uma tabela de dados', 'help_text': 'Insira os dados da tabela', 'icon': 'table', 'label': 'Bloco de Tabela', 'template': 'blocks/table.html'})}, help_text='Corpo completo da dica (textos, imagens, vídeos, etc).', null=True, verbose_name='Conteúdo Principal')),
                ('galeria_imagens', wagtail.fields.StreamField([('imagem', 0)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagem', 'required': True})}, help_text='Fotos de eventos, visitas, bastidores.', null=True, verbose_name='Galeria de Imagens')),
                ('legenda_galeria', models.TextField(blank=True, help_text='Descrição geral da galeria de imagens.', verbose_name='Legenda da Galeria')),
                ('texto_frase', models.TextField(blank=True, help_text='Frase motivacional ou provocativa.', verbose_name='Frase Inspiradora')),
                ('autor_frase', models.CharField(blank=True, help_text='Quem disse a frase (opcional).', max_length=100, verbose_name='Autor da Frase')),
                ('arquivos', wagtail.fields.StreamField([('arquivo', 0)], blank=True, block_lookup={0: ('blocks.models.EspecificDocumentChooserBlock', (), {'label': 'Arquivo', 'required': True})}, help_text='PDFs, apresentações ou documentos relacionados.', null=True, verbose_name='Arquivos Anexos')),
                ('imagem_destaque', models.ForeignKey(blank=True, help_text='Imagem principal da dica (usada em cards e compartilhamento).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagem de Destaque')),
            ],
            options={
                'verbose_name': 'Dica do Presidente',
                'verbose_name_plural': 'Dicas do Presidente',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='DicasPresidentePageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='dicas_presidente.dicaspresidentepage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='dicaspresidentepage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='dicas_presidente.DicasPresidentePageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
