# Generated by Django 5.1.13 on 2025-11-06 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dicas_presidente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dicaspresidenteindexpage',
            name='mostrar_filtro_tipo',
        ),
    ]
