# Generated by Django 5.1.13 on 2025-11-06 17:30

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dicas_presidente', '0002_remove_dicaspresidenteindexpage_mostrar_filtro_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dicaspresidentepage',
            name='assinatura',
        ),
        migrations.RemoveField(
            model_name='dicaspresidentepage',
            name='autor_frase',
        ),
        migrations.RemoveField(
            model_name='dicaspresidentepage',
            name='body',
        ),
        migrations.RemoveField(
            model_name='dicaspresidentepage',
            name='categoria_noticia',
        ),
        migrations.RemoveField(
            model_name='dicaspresidentepage',
            name='galeria_imagens',
        ),
        migrations.RemoveField(
            model_name='dicaspresidentepage',
            name='legenda_galeria',
        ),
        migrations.RemoveField(
            model_name='dicaspresidentepage',
            name='link_externo',
        ),
        migrations.RemoveField(
            model_name='dicaspresidentepage',
            name='motivo_recomendacao',
        ),
        migrations.RemoveField(
            model_name='dicaspresidentepage',
            name='texto_frase',
        ),
        migrations.RemoveField(
            model_name='dicaspresidentepage',
            name='texto_mensagem',
        ),
        migrations.RemoveField(
            model_name='dicaspresidentepage',
            name='tipo_dica',
        ),
        migrations.RemoveField(
            model_name='dicaspresidentepage',
            name='tipo_recomendacao',
        ),
        migrations.AddField(
            model_name='dicaspresidentepage',
            name='conteudo',
            field=wagtail.fields.StreamField([('mensagem', 1), ('recomendacao', 5), ('noticia_interna', 7), ('galeria', 11), ('frase', 14)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': "Ex: 'João Silva, Presidente'", 'label': 'Assinatura', 'max_length': 100, 'required': False}), 1: ('wagtail.blocks.StructBlock', [[('assinatura', 0)]], {}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('artigo', 'Artigo'), ('video', 'Vídeo'), ('podcast', 'Podcast'), ('livro', 'Livro'), ('estudo', 'Estudo/Relatório')], 'help_text': 'Tipo de conteúdo recomendado.', 'label': 'Tipo de Recomendação'}), 3: ('wagtail.blocks.URLBlock', (), {'help_text': 'URL do artigo, vídeo, livro ou estudo recomendado.', 'label': 'Link Externo', 'required': False}), 4: ('wagtail.blocks.TextBlock', (), {'help_text': 'Breve explicação do presidente sobre a recomendação.', 'label': 'Por que recomendo', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('tipo', 2), ('link_externo', 3), ('motivo', 4)]], {}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('conquista', 'Conquista'), ('meta', 'Meta Alcançada'), ('evento', 'Evento'), ('comunicado', 'Comunicado Oficial')], 'help_text': 'Tipo de notícia interna.', 'label': 'Categoria da Notícia', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('categoria', 6)]], {}), 8: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagem'}), 9: ('wagtail.blocks.ListBlock', (8,), {'help_text': 'Fotos de eventos, visitas, bastidores.', 'label': 'Galeria de Imagens'}), 10: ('wagtail.blocks.TextBlock', (), {'help_text': 'Descrição geral da galeria de imagens.', 'label': 'Legenda da Galeria', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('imagens', 9), ('legenda', 10)]], {}), 12: ('wagtail.blocks.TextBlock', (), {'help_text': 'Frase motivacional ou provocativa.', 'label': 'Frase Inspiradora'}), 13: ('wagtail.blocks.CharBlock', (), {'help_text': 'Quem disse a frase (opcional).', 'label': 'Autor da Frase', 'max_length': 100, 'required': False}), 14: ('wagtail.blocks.StructBlock', [[('texto_frase', 12), ('autor', 13)]], {})}, help_text='Adicione um ou mais blocos para compor a dica.', verbose_name='Conteúdo'),
        ),
    ]
