# Generated by Django 5.1.13 on 2025-11-06 17:31

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dicas_presidente', '0003_remove_dicaspresidentepage_assinatura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicaspresidentepage',
            name='conteudo',
            field=wagtail.fields.StreamField([('mensagem', 2), ('recomendacao', 7), ('noticia_interna', 10), ('galeria', 14), ('frase', 17)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Mensagem motivacional ou comunicado do presidente.', 'verbose_name': 'Texto da Mensagem'}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': "Ex: 'João Silva, Presidente'", 'label': 'Assinatura', 'max_length': 100, 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('texto', 0), ('assinatura', 1)]], {}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('artigo', 'Artigo'), ('video', 'Vídeo'), ('podcast', 'Podcast'), ('livro', 'Livro'), ('estudo', 'Estudo/Relatório')], 'help_text': 'Tipo de conteúdo recomendado.', 'label': 'Tipo de Recomendação'}), 4: ('wagtail.blocks.URLBlock', (), {'help_text': 'URL do artigo, vídeo, livro ou estudo recomendado.', 'label': 'Link Externo', 'required': False}), 5: ('wagtail.blocks.TextBlock', (), {'help_text': 'Breve explicação do presidente sobre a recomendação.', 'label': 'Por que recomendo', 'required': False}), 6: ('wagtail.blocks.RichTextBlock', (), {'blank': True, 'help_text': 'Informações extras sobre a recomendação.', 'required': False, 'verbose_name': 'Conteúdo Adicional'}), 7: ('wagtail.blocks.StructBlock', [[('tipo', 3), ('link_externo', 4), ('motivo', 5), ('conteudo_adicional', 6)]], {}), 8: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('conquista', 'Conquista'), ('meta', 'Meta Alcançada'), ('evento', 'Evento'), ('comunicado', 'Comunicado Oficial')], 'help_text': 'Tipo de notícia interna.', 'label': 'Categoria da Notícia', 'required': False}), 9: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Corpo completo da notícia interna.', 'verbose_name': 'Conteúdo da Notícia'}), 10: ('wagtail.blocks.StructBlock', [[('categoria', 8), ('conteudo', 9)]], {}), 11: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagem'}), 12: ('wagtail.blocks.ListBlock', (11,), {'help_text': 'Fotos de eventos, visitas, bastidores.', 'label': 'Galeria de Imagens'}), 13: ('wagtail.blocks.TextBlock', (), {'help_text': 'Descrição geral da galeria de imagens.', 'label': 'Legenda da Galeria', 'required': False}), 14: ('wagtail.blocks.StructBlock', [[('imagens', 12), ('legenda', 13)]], {}), 15: ('wagtail.blocks.TextBlock', (), {'help_text': 'Frase motivacional ou provocativa.', 'label': 'Frase Inspiradora'}), 16: ('wagtail.blocks.CharBlock', (), {'help_text': 'Quem disse a frase (opcional).', 'label': 'Autor da Frase', 'max_length': 100, 'required': False}), 17: ('wagtail.blocks.StructBlock', [[('texto_frase', 15), ('autor', 16)]], {})}, help_text='Adicione um ou mais blocos para compor a dica.', verbose_name='Conteúdo'),
        ),
    ]
