# Generated by Django 5.1.13 on 2025-11-12 13:03

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicas_presidente', '0005_add_streamfield_blocks'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicaspresidentepage',
            name='imagens_dica',
            field=wagtail.fields.StreamField([('imagem', 0)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagem da dica', 'required': True})}, help_text='Adicione uma ou mais imagens para a dica.', null=True, verbose_name='Imagens da Dica'),
        ),
        migrations.AddField(
            model_name='dicaspresidentepage',
            name='slideshow_imagens',
            field=models.BooleanField(default=False, help_text='Exibir as imagens como slideshow.', verbose_name='Ativar slideshow de imagens'),
        ),
        migrations.AlterField(
            model_name='dicaspresidentepage',
            name='conteudo',
            field=wagtail.fields.StreamField([('mensagem', 2), ('recomendacao', 8), ('noticia_interna', 11), ('galeria', 15), ('frase', 18)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Mensagem motivacional ou comunicado do presidente.', 'verbose_name': 'Texto da Mensagem'}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': "Ex: 'João Silva, Presidente'", 'label': 'Assinatura', 'max_length': 100, 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('texto', 0), ('assinatura', 1)]], {}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('artigo', 'Artigo'), ('video', 'Vídeo'), ('podcast', 'Podcast'), ('livro', 'Livro'), ('estudo', 'Estudo/Relatório')], 'help_text': 'Tipo de conteúdo recomendado.', 'label': 'Tipo de Recomendação'}), 4: ('wagtail.blocks.URLBlock', (), {'help_text': 'URL do artigo, vídeo, livro ou estudo recomendado.', 'label': 'Link Externo', 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': "Texto customizado para o botão (deixe vazio para usar 'Acessar conteúdo recomendado').", 'label': 'Texto do Link', 'max_length': 200, 'required': False}), 6: ('wagtail.blocks.TextBlock', (), {'help_text': 'Breve explicação do presidente sobre a recomendação.', 'label': 'Por que recomendo', 'required': False}), 7: ('wagtail.blocks.RichTextBlock', (), {'blank': True, 'help_text': 'Informações extras sobre a recomendação.', 'required': False, 'verbose_name': 'Conteúdo Adicional'}), 8: ('wagtail.blocks.StructBlock', [[('tipo', 3), ('link_externo', 4), ('texto_link', 5), ('motivo', 6), ('conteudo_adicional', 7)]], {}), 9: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('conquista', 'Conquista'), ('meta', 'Meta Alcançada'), ('evento', 'Evento'), ('comunicado', 'Comunicado Oficial')], 'help_text': 'Tipo de post interno.', 'label': 'Categoria do Post', 'required': False}), 10: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Corpo completo do post interno.', 'verbose_name': 'Conteúdo do Post'}), 11: ('wagtail.blocks.StructBlock', [[('categoria', 9), ('conteudo', 10)]], {}), 12: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagem'}), 13: ('wagtail.blocks.ListBlock', (12,), {'help_text': 'Fotos de eventos, visitas, bastidores.', 'label': 'Galeria de Imagens'}), 14: ('wagtail.blocks.TextBlock', (), {'help_text': 'Descrição geral da galeria de imagens.', 'label': 'Legenda da Galeria', 'required': False}), 15: ('wagtail.blocks.StructBlock', [[('imagens', 13), ('legenda', 14)]], {}), 16: ('wagtail.blocks.TextBlock', (), {'help_text': 'Frase motivacional ou provocativa.', 'label': 'Frase Inspiradora'}), 17: ('wagtail.blocks.CharBlock', (), {'help_text': 'Quem disse a frase (opcional).', 'label': 'Autor da Frase', 'max_length': 100, 'required': False}), 18: ('wagtail.blocks.StructBlock', [[('texto_frase', 16), ('autor', 17)]], {})}, help_text='Adicione um ou mais blocos para compor a dica.', verbose_name='Conteúdo'),
        ),
        migrations.AlterField(
            model_name='dicaspresidentepage',
            name='imagem_destaque',
            field=models.ForeignKey(blank=True, help_text='Imagem usada em destaque para SEO e redes sociais', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagem de Destaque'),
        ),
    ]
