# Generated by Django 5.1.11 on 2025-10-21 13:24

import datetime
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.contrib.routable_page.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='CursosIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', models.TextField(blank=True, help_text='Texto para o topo da página de cursos')),
                ('mostrar_destaque_primeiro', models.BooleanField(default=True, help_text='Marcar para exibir os cursos em destaque primeiro.')),
            ],
            options={
                'verbose_name': 'Página de Índice de Cursos',
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='CursosPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('images', wagtail.fields.StreamField([('image', 0)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagem'})}, help_text='Imagens relacionadas à página', verbose_name='Imagens')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Subtítulo')),
                ('descricao', models.TextField(help_text='Breve descrição do curso.', max_length=255, verbose_name='Descrição')),
                ('data_publicacao', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Data de publicação do curso')),
                ('body', wagtail.fields.StreamField([('heading_block', 2), ('paragraph_block', 3), ('image_block', 6), ('block_quote', 9), ('embed_block', 10), ('iframe_block', 15), ('table_block', 16)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'blank': True, 'choices': [('', 'Select a header size'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')], 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('heading_text', 0), ('size', 1)]], {}), 3: ('wagtail.blocks.RichTextBlock', (), {'description': 'A rich text paragraph', 'icon': 'pilcrow', 'preview_value': '\n            <h2>Our bread pledge</h2>\n            <p>As a bakery, <b>breads</b> have <i>always</i> been in our hearts.\n            <a href="https://en.wikipedia.org/wiki/Staple_food">Staple foods</a>\n            are essential for society, and – bread is the tastiest of all.\n            We love to transform batters and doughs into baked goods with a firm\n            dry crust and fluffy center.</p>\n            ', 'template': 'blocks/paragraph_block.html'}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'required': False}), 6: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5), ('attribution', 5)]], {}), 7: ('wagtail.blocks.TextBlock', (), {}), 8: ('wagtail.blocks.CharBlock', (), {'blank': True, 'label': 'e.g. Mary Berry', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('text', 7), ('attribute_name', 8)]], {}), 10: ('wagtail.embeds.blocks.EmbedBlock', (), {'description': 'An embedded video or other media', 'help_text': 'Insert an embed URL e.g https://www.youtube.com/watch?v=SGJFWirQ3ks', 'icon': 'media', 'preview_template': 'blocks/preview/static_embed_block.html', 'preview_value': 'https://www.youtube.com/watch?v=mwrGSfiB1Mg', 'template': 'blocks/embed_block.html'}), 11: ('wagtail.blocks.URLBlock', (), {'label': 'URL do iframe', 'required': True}), 12: ('wagtail.blocks.CharBlock', (), {'default': '100%', 'help_text': 'Exemplo: 100% ou 600', 'label': 'Largura', 'required': False}), 13: ('wagtail.blocks.CharBlock', (), {'default': '400', 'help_text': 'Exemplo: 400', 'label': 'Altura', 'required': False}), 14: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'label': 'Permitir tela cheia', 'required': False}), 15: ('wagtail.blocks.StructBlock', [[('url', 11), ('width', 12), ('height', 13), ('allowfullscreen', 14)]], {'description': 'An embedded iframe', 'help_text': 'Insert an iframe URL e.g https://example.com', 'icon': 'site', 'template': 'blocks/iframe_block.html'}), 16: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'description': 'Uma tabela de dados', 'help_text': 'Insira os dados da tabela', 'icon': 'table'})}, null=True, verbose_name='Conteúdo do curso')),
                ('body_migrated', models.TextField(blank=True, help_text='Usado apenas para conteúdo do antigo site Plone.', null=True)),
                ('plone_node_id', models.TextField(blank=True, db_index=True, help_text='ID do nó no Plone, usado para identificar a página migrada.', null=True, unique=True)),
                ('destaque', models.BooleanField(default=False, help_text='Marcar este curso como destaque?', verbose_name='Exibir em Destaques')),
                ('arquivos', wagtail.fields.StreamField([('arquivo', 0)], blank=True, block_lookup={0: ('blocks.models.EspecificDocumentChooserBlock', (), {'label': 'Arquivos do curso', 'required': True})}, null=True, verbose_name='Arquivos do curso')),
                ('nao_exibir_lista_de_arquivos', models.BooleanField(default=False, help_text='Marque para não exibir a lista de arquivos na página do curso.', verbose_name='Não exibir lista de arquivos')),
            ],
            options={
                'verbose_name': 'Página de Curso',
                'verbose_name_plural': 'Páginas de Cursos',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CursosPageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='cursos.cursospage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cursospage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='cursos.CursosPageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
