# Generated by Django 5.1.13 on 2025-10-28 18:00

import datetime
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursospage',
            options={'default_permissions': [], 'permissions': [('view_conteudo_migrado', 'Pode ver conteúdo migrado (body_migrated)')], 'verbose_name': 'Página de Aviso', 'verbose_name_plural': 'Páginas de Cursos'},
        ),
        migrations.RemoveField(
            model_name='cursosindexpage',
            name='mostrar_destaque_primeiro',
        ),
        migrations.RemoveField(
            model_name='cursospage',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='cursospage',
            name='images',
            field=wagtail.fields.StreamField([('imagem', 0)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagem do aviso', 'required': True})}, null=True, verbose_name='Coleção de Imagens'),
        ),
        migrations.AddField(
            model_name='cursospage',
            name='sensivel_periodo_eleitoral',
            field=models.BooleanField(default=False, help_text='Marque se este aviso deve ser ocultado ou tratado de forma especial durante o período eleitoral.', verbose_name='Aviso sensível ao período eleitoral'),
        ),
        migrations.AddField(
            model_name='cursospage',
            name='slideshow_imagens',
            field=models.BooleanField(default=False, help_text='Exibir as imagens como slideshow na página do aviso.', verbose_name='Ativar slideshow de imagens'),
        ),
        migrations.AlterField(
            model_name='cursospage',
            name='arquivos',
            field=wagtail.fields.StreamField([('arquivo', 0)], blank=True, block_lookup={0: ('blocks.models.EspecificDocumentChooserBlock', (), {'label': 'Arquivos', 'required': True})}, null=True, verbose_name='Arquivos do aviso'),
        ),
        migrations.AlterField(
            model_name='cursospage',
            name='body',
            field=wagtail.fields.StreamField([('heading_block', 2), ('paragraph_block', 3), ('image_block', 6), ('block_quote', 9), ('embed_block', 10), ('iframe_block', 15), ('table_block', 16)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'blank': True, 'choices': [('', 'Select a header size'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')], 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('heading_text', 0), ('size', 1)]], {}), 3: ('wagtail.blocks.RichTextBlock', (), {'description': 'A rich text paragraph', 'icon': 'pilcrow', 'preview_value': '\n            <h2>Our bread pledge</h2>\n            <p>As a bakery, <b>breads</b> have <i>always</i> been in our hearts.\n            <a href="https://en.wikipedia.org/wiki/Staple_food">Staple foods</a>\n            are essential for society, and – bread is the tastiest of all.\n            We love to transform batters and doughs into baked goods with a firm\n            dry crust and fluffy center.</p>\n            ', 'template': 'blocks/paragraph_block.html'}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'required': False}), 6: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5), ('attribution', 5)]], {}), 7: ('wagtail.blocks.TextBlock', (), {}), 8: ('wagtail.blocks.CharBlock', (), {'blank': True, 'label': 'e.g. Mary Berry', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('text', 7), ('attribute_name', 8)]], {}), 10: ('wagtail.embeds.blocks.EmbedBlock', (), {'description': 'An embedded video or other media', 'help_text': 'Insert an embed URL e.g https://www.youtube.com/watch?v=SGJFWirQ3ks', 'icon': 'media', 'preview_template': 'blocks/preview/static_embed_block.html', 'preview_value': 'https://www.youtube.com/watch?v=mwrGSfiB1Mg', 'template': 'blocks/embed_block.html'}), 11: ('wagtail.blocks.URLBlock', (), {'label': 'URL do iframe', 'required': True}), 12: ('wagtail.blocks.CharBlock', (), {'default': '100%', 'help_text': 'Exemplo: 100% ou 600', 'label': 'Largura', 'required': False}), 13: ('wagtail.blocks.CharBlock', (), {'default': '400', 'help_text': 'Exemplo: 400', 'label': 'Altura', 'required': False}), 14: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'label': 'Permitir tela cheia', 'required': False}), 15: ('wagtail.blocks.StructBlock', [[('url', 11), ('width', 12), ('height', 13), ('allowfullscreen', 14)]], {'description': 'An embedded iframe', 'help_text': 'Insert an iframe URL e.g https://example.com', 'icon': 'site', 'template': 'blocks/iframe_block.html'}), 16: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'description': 'Uma tabela de dados', 'help_text': 'Insira os dados da tabela', 'icon': 'table'})}, null=True, verbose_name='Corpo da página'),
        ),
        migrations.AlterField(
            model_name='cursospage',
            name='data_publicacao',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Data de publicação do aviso'),
        ),
        migrations.AlterField(
            model_name='cursospage',
            name='descricao',
            field=models.TextField(help_text='Breve descrição do conteúdo da página.', max_length=255, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='cursospage',
            name='destaque',
            field=models.BooleanField(default=False, help_text='Exibe o aviso em destaque na página inicial. Máximo de 6 cursos.', verbose_name='Aviso em destaque'),
        ),
        migrations.AlterField(
            model_name='cursospage',
            name='nao_exibir_lista_de_arquivos',
            field=models.BooleanField(default=False, help_text='Marque para não exibir a lista de arquivos na página do aviso.', verbose_name='Não exibir lista de arquivos'),
        ),
    ]
