# Generated by Django 5.1.13 on 2025-10-28 18:04

import datetime
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_alter_cursospage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursospage',
            options={'default_permissions': [], 'permissions': [('view_conteudo_migrado', 'Pode ver conteúdo migrado (body_migrated)')], 'verbose_name': 'Página de Curso', 'verbose_name_plural': 'Páginas de Cursos'},
        ),
        migrations.RemoveField(
            model_name='cursospage',
            name='sensivel_periodo_eleitoral',
        ),
        migrations.RemoveField(
            model_name='cursospage',
            name='slideshow_imagens',
        ),
        migrations.AlterField(
            model_name='cursospage',
            name='arquivos',
            field=wagtail.fields.StreamField([('arquivo', 0)], blank=True, block_lookup={0: ('blocks.models.EspecificDocumentChooserBlock', (), {'label': 'Arquivos', 'required': True})}, null=True, verbose_name='Arquivos do curso'),
        ),
        migrations.AlterField(
            model_name='cursospage',
            name='data_publicacao',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Data de publicação do curso'),
        ),
        migrations.AlterField(
            model_name='cursospage',
            name='destaque',
            field=models.BooleanField(default=False, help_text='Exibe o curso em destaque na página inicial. Máximo de 6 cursos.', verbose_name='Curso em destaque'),
        ),
        migrations.AlterField(
            model_name='cursospage',
            name='images',
            field=wagtail.fields.StreamField([('imagem', 0)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagem do curso', 'required': True})}, null=True, verbose_name='Coleção de Imagens'),
        ),
        migrations.AlterField(
            model_name='cursospage',
            name='nao_exibir_lista_de_arquivos',
            field=models.BooleanField(default=False, help_text='Marque para não exibir a lista de arquivos na página do curso.', verbose_name='Não exibir lista de arquivos'),
        ),
    ]
