# Generated by Django 5.1.13 on 2025-10-29 17:55

from django.db import migrations


class Migration(migrations.Migration):
    """Merge de branches paralelas"""

    dependencies = [
        ('cursos', '0002a_remove_cursospage_images_cursospage_imagem_destaque'),
        ('cursos', '0003a_alter_cursospage_options_and_more'),
    ]

    operations = [
    ]
