# Generated by Django 5.1.13 on 2025-10-29 17:57

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_merge_20251029_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursospage',
            name='images',
            field=wagtail.fields.StreamField([('imagem', 0)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagem do curso', 'required': True})}, null=True, verbose_name='Coleção de Imagens'),
        ),
    ]
