# Generated by Django 5.1.13 on 2025-11-03 13:36

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_cursospage_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursospage',
            name='body',
            field=wagtail.fields.StreamField([('paragraph_block', 0), ('image_block', 3), ('video_block', 6), ('table_block', 7)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'description': 'Um parágrafo de texto rico', 'icon': 'pilcrow', 'label': 'Texto de Parágrafo', 'preview_value': '\n            <h2>Our bread pledge</h2>\n            <p>As a bakery, <b>breads</b> have <i>always</i> been in our hearts.\n            <a href="https://en.wikipedia.org/wiki/Staple_food">Staple foods</a>\n            are essential for society, and – bread is the tastiest of all.\n            We love to transform batters and doughs into baked goods with a firm\n            dry crust and fluffy center.</p>\n            ', 'template': 'blocks/paragraph_block.html'}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('image', 1), ('caption', 2), ('attribution', 2)]], {'label': 'Bloco de Imagem com Legenda'}), 4: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': True}), 5: ('wagtail.blocks.URLBlock', (), {'label': 'URL do vídeo (iframe YouTube)', 'required': True}), 6: ('wagtail.blocks.StructBlock', [[('titulo', 4), ('srcIframe', 5)]], {'label': 'Bloco de Vídeo'}), 7: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'description': 'Uma tabela de dados', 'help_text': 'Insira os dados da tabela', 'icon': 'table', 'label': 'Bloco de Tabela', 'template': 'blocks/table.html'})}, null=True, verbose_name='Corpo da página'),
        ),
    ]
