# Generated by Django 5.1.13 on 2025-11-17 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0006_alter_cursospage_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursospage',
            name='images',
        ),
    ]
