# Generated by Django 5.1.14 on 2025-11-24 19:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Questionário')),
                ('tipo', models.CharField(choices=[('mchat', 'M-CHAT (Modified Checklist for Autism in Toddlers)'), ('cars', 'CARS (Childhood Autism Rating Scale)'), ('abc', 'ABC (Autism Behavior Checklist)'), ('outro', 'Outro Questionário')], max_length=20, verbose_name='Tipo de Questionário')),
                ('descricao', models.TextField(help_text='Descrição detalhada do questionário e sua aplicação', verbose_name='Descrição')),
                ('faixa_etaria_minima', models.IntegerField(help_text='Idade mínima em meses para aplicação', verbose_name='Idade Mínima (meses)')),
                ('faixa_etaria_maxima', models.IntegerField(help_text='Idade máxima em meses para aplicação', verbose_name='Idade Máxima (meses)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Questionário',
                'verbose_name_plural': 'Questionários',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probabilidade_tea', models.FloatField(help_text='Probabilidade calculada pela IA (0-1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Probabilidade de TEA')),
                ('confianca', models.CharField(choices=[('muito_baixa', 'Muito Baixa'), ('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('muito_alta', 'Muito Alta')], max_length=20, verbose_name='Nível de Confiança')),
                ('score_texto', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Score Análise de Texto')),
                ('score_audio', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Score Análise de Áudio')),
                ('score_video', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Score Análise de Vídeo')),
                ('areas_risco', models.JSONField(blank=True, help_text="JSON com áreas e scores. Ex: {'comunicacao': 0.8, 'interacao_social': 0.7}", null=True, verbose_name='Áreas de Risco Identificadas')),
                ('recomendacoes', models.TextField(blank=True, help_text='Recomendações geradas pela IA', verbose_name='Recomendações')),
                ('modelo_utilizado', models.CharField(max_length=100, verbose_name='Modelo de IA Utilizado')),
                ('versao_modelo', models.CharField(max_length=50, verbose_name='Versão do Modelo')),
                ('processado_em', models.DateTimeField(auto_now_add=True, verbose_name='Processado em')),
            ],
            options={
                'verbose_name': 'Resultado da IA',
                'verbose_name_plural': 'Resultados da IA',
            },
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.IntegerField(help_text='Ordem de apresentação da pergunta', verbose_name='Ordem')),
                ('texto', models.TextField(verbose_name='Texto da Pergunta')),
                ('tipo_resposta', models.CharField(choices=[('sim_nao', 'Sim/Não'), ('escala_likert', 'Escala Likert (1-5)'), ('multipla_escolha', 'Múltipla Escolha'), ('texto_curto', 'Texto Curto')], default='sim_nao', max_length=20, verbose_name='Tipo de Resposta')),
                ('opcoes_resposta', models.JSONField(blank=True, help_text="JSON com opções para múltipla escolha. Ex: ['Opção 1', 'Opção 2']", null=True, verbose_name='Opções de Resposta')),
                ('peso_risco', models.FloatField(default=1.0, help_text='Peso desta pergunta no cálculo de risco (0-10)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Peso de Risco')),
                ('area_avaliada', models.CharField(blank=True, help_text='Ex: Comunicação, Interação Social, Comportamento', max_length=100, verbose_name='Área Avaliada')),
                ('questionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='triagem_ia.questionario', verbose_name='Questionário')),
            ],
            options={
                'verbose_name': 'Pergunta',
                'verbose_name_plural': 'Perguntas',
                'ordering': ['questionario', 'ordem'],
                'unique_together': {('questionario', 'ordem')},
            },
        ),
        migrations.CreateModel(
            name='AlertaIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(help_text='Ex: ausencia_contato_visual, estereotipia_motora', max_length=100, verbose_name='Tipo de Alerta')),
                ('severidade', models.CharField(choices=[('info', 'Informativo'), ('atencao', 'Atenção'), ('critico', 'Crítico')], max_length=20, verbose_name='Severidade')),
                ('descricao', models.TextField(verbose_name='Descrição do Alerta')),
                ('modalidade_origem', models.CharField(choices=[('texto', 'Texto'), ('audio', 'Áudio'), ('video', 'Vídeo'), ('questionario', 'Questionário')], max_length=20, verbose_name='Modalidade de Origem')),
                ('timestamp_deteccao', models.FloatField(blank=True, help_text='Para áudio/vídeo: segundo em que foi detectado', null=True, verbose_name='Timestamp de Detecção')),
                ('confianca_deteccao', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Confiança da Detecção')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('resultado_ia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='triagem_ia.resultadoia', verbose_name='Resultado IA')),
            ],
            options={
                'verbose_name': 'Alerta da IA',
                'verbose_name_plural': 'Alertas da IA',
                'ordering': ['-severidade', '-confianca_deteccao'],
            },
        ),
        migrations.CreateModel(
            name='Triagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_crianca', models.CharField(max_length=200, verbose_name='Nome da Criança')),
                ('data_nascimento_crianca', models.DateField(verbose_name='Data de Nascimento da Criança')),
                ('idade_meses', models.IntegerField(help_text='Calculado automaticamente', verbose_name='Idade em Meses')),
                ('status', models.CharField(choices=[('iniciada', 'Iniciada'), ('em_andamento', 'Em Andamento'), ('aguardando_analise', 'Aguardando Análise IA'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='iniciada', max_length=20, verbose_name='Status')),
                ('nivel_risco', models.CharField(blank=True, choices=[('baixo', 'Baixo Risco'), ('moderado', 'Risco Moderado'), ('alto', 'Alto Risco'), ('muito_alto', 'Risco Muito Alto')], max_length=20, null=True, verbose_name='Nível de Risco')),
                ('pontuacao_total', models.FloatField(blank=True, null=True, verbose_name='Pontuação Total')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações do Responsável')),
                ('iniciada_em', models.DateTimeField(auto_now_add=True, verbose_name='Iniciada em')),
                ('concluida_em', models.DateTimeField(blank=True, null=True, verbose_name='Concluída em')),
                ('questionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='triagens', to='triagem_ia.questionario', verbose_name='Questionário Utilizado')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triagens_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Triagem',
                'verbose_name_plural': 'Triagens',
                'ordering': ['-iniciada_em'],
            },
        ),
        migrations.AddField(
            model_name='resultadoia',
            name='triagem',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultado_ia', to='triagem_ia.triagem', verbose_name='Triagem'),
        ),
        migrations.CreateModel(
            name='ModalidadeTexto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_relato', models.TextField(help_text='Descrição de comportamentos observados', verbose_name='Relato do Responsável')),
                ('analise_sentimento', models.JSONField(blank=True, help_text='Resultado da análise de sentimento (positivo, negativo, neutro)', null=True, verbose_name='Análise de Sentimento')),
                ('palavras_chave', models.JSONField(blank=True, help_text='Lista de palavras-chave relacionadas a TEA', null=True, verbose_name='Palavras-Chave Extraídas')),
                ('score_ia', models.FloatField(blank=True, help_text='Probabilidade de indicadores de TEA (0-1)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Score IA')),
                ('processado_em', models.DateTimeField(blank=True, null=True, verbose_name='Processado em')),
                ('triagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analises_texto', to='triagem_ia.triagem', verbose_name='Triagem')),
            ],
            options={
                'verbose_name': 'Análise de Texto',
                'verbose_name_plural': 'Análises de Texto',
            },
        ),
        migrations.CreateModel(
            name='RespostaQuestionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta_texto', models.TextField(blank=True, verbose_name='Resposta em Texto')),
                ('resposta_numerica', models.IntegerField(blank=True, help_text='Para escalas Likert ou sim/não (0=não, 1=sim)', null=True, verbose_name='Resposta Numérica')),
                ('pontuacao_risco', models.FloatField(default=0.0, help_text='Calculado baseado no peso da pergunta e resposta', verbose_name='Pontuação de Risco')),
                ('respondida_em', models.DateTimeField(auto_now_add=True, verbose_name='Respondida em')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respostas', to='triagem_ia.pergunta', verbose_name='Pergunta')),
                ('triagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='triagem_ia.triagem', verbose_name='Triagem')),
            ],
            options={
                'verbose_name': 'Resposta do Questionário',
                'verbose_name_plural': 'Respostas do Questionário',
                'unique_together': {('triagem', 'pergunta')},
            },
        ),
    ]
