# Generated by Django 5.1.14 on 2025-11-24 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triagem_ia', '0001_initial'),
    ]

    operations = [
    ]
