# Generated by Django 5.1.5 on 2025-03-23 21:11

import django.core.validators
import re
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 4)], block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'Level 2 (child of level 1)'), ('h3', 'Level 3 (child of level 2)'), ('h4', 'Level 4 (child of level 3)'), ('h5', 'Level 5 (child of level 4)'), ('h6', 'Level 6 (child of level 5)')], 'help_text': 'These different heading levels help to communicate the organization and hierarchy of the content on a page.'}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'The text to appear in the heading.'}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Used to link to a specific location within this page. A slug should only contain letters, numbers, underscore (_), or hyphen (-).', 'required': False, 'validators': (django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid'),)}), 3: ('wagtail_color_panel.blocks.NativeColorBlock', (), {'required': False}), 4: ('wagtail.blocks.StructBlock', [[('heading_level', 0), ('heading_text', 1), ('target_slug', 2), ('color', 3)]], {})}, default=None),
        ),
    ]
