# Generated by Django 5.1.9 on 2025-05-30 11:37

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('acessos_rapidos', 5), ('banner_com_link', 9), ('lista_videos', 13), ('redes_sociais', 19)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': True}), 1: ('wagtail.blocks.URLBlock', (), {'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Classe do ícone (ex: fas fa-car)', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('titulo', 0), ('link', 1), ('icone', 2)]], {}), 4: ('wagtail.blocks.ListBlock', (3,), {'default': []}), 5: ('wagtail.blocks.StructBlock', [[('itens', 4)]], {}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagem do Banner', 'required': True}), 7: ('wagtail.blocks.URLBlock', (), {'label': 'URL do Banner', 'required': True}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Descrição da imagem (alt)', 'label': 'Texto alternativo', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('imagem', 6), ('link', 7), ('alt_texto', 8)]], {}), 10: ('wagtail.blocks.URLBlock', (), {'label': 'URL do vídeo (iframe YouTube)', 'required': True}), 11: ('wagtail.blocks.StructBlock', [[('titulo', 0), ('srcIframe', 10)]], {}), 12: ('wagtail.blocks.ListBlock', (11,), {'label': 'Vídeos', 'max_num': 3}), 13: ('wagtail.blocks.StructBlock', [[('videos', 12)]], {}), 14: ('wagtail.blocks.CharBlock', (), {'default': 'Siga-nos nas redes sociais', 'required': False}), 15: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Imagem que será exibida ao lado do texto.', 'required': False}), 16: ('wagtail.blocks.CharBlock', (), {'required': True}), 17: ('wagtail.blocks.StructBlock', [[('nome', 16), ('link', 1), ('icone', 16)]], {}), 18: ('wagtail.blocks.ListBlock', (17,), {'max_num': 4}), 19: ('wagtail.blocks.StructBlock', [[('titulo', 14), ('imagem', 15), ('redes', 18)]], {})}, default=None),
        ),
    ]
