# Generated by Django 5.1.9 on 2025-05-29 17:27

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('acessos_rapidos', 5), ('central_monitoramento', 11)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': True}), 1: ('wagtail.blocks.URLBlock', (), {'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Classe do ícone (ex: fas fa-car)', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('titulo', 0), ('link', 1), ('icone', 2)]], {}), 4: ('wagtail.blocks.ListBlock', (3,), {'default': []}), 5: ('wagtail.blocks.StructBlock', [[('itens', 4)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Descrição do Dado', 'max_length': 100, 'required': True}), 7: ('wagtail.blocks.FloatBlock', (), {'disabled': True, 'help_text': 'Preenchido automaticamente pela API', 'label': 'Valor do Dado Default', 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'label': 'ID do Card do Metabase', 'required': True}), 9: ('wagtail.blocks.StructBlock', [[('odometer_description', 6), ('odometer_value', 7), ('id_card', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {'label': 'Central de Monitoramento Detran'}), 11: ('wagtail.blocks.StructBlock', [[('odometers', 10)]], {})}, default=None, null=True),
        ),
    ]
