# Generated by Django 5.1.14 on 2025-11-25 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contatopage_alter_homepage_body_iamultimodalpage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iamultimodalpage',
            name='imagem_destaque',
        ),
        migrations.RemoveField(
            model_name='iamultimodalpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='responsaveispage',
            name='imagem_destaque',
        ),
        migrations.RemoveField(
            model_name='responsaveispage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='profissionaispage',
            name='imagem_destaque',
        ),
        migrations.RemoveField(
            model_name='profissionaispage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='sobrenospage',
            name='imagem_destaque',
        ),
        migrations.RemoveField(
            model_name='sobrenospage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='ContatoPage',
        ),
        migrations.DeleteModel(
            name='IAMultimodalPage',
        ),
        migrations.DeleteModel(
            name='responsaveisPage',
        ),
        migrations.DeleteModel(
            name='ProfissionaisPage',
        ),
        migrations.DeleteModel(
            name='SobreNosPage',
        ),
    ]
