# Generated by Django 5.1.11 on 2025-10-03 13:25

from django.db import migrations


class Migration(migrations.Migration):
    """Merge de branches paralelas"""

    dependencies = [
        ('home', '0021a_homepage_descricao_homepage_images'),
        ('home', '0022_alter_homepage_body'),
    ]

    operations = [
    ]
