# Generated by Django 5.1.11 on 2025-10-24 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_alter_homepage_body'),
        ('home', '0027_alter_homepage_body'),
    ]

    operations = [
    ]
