# Generated by Django 5.1.13 on 2025-10-24 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_merge_20251023_1240'),
        ('home', '0027_alter_homepage_body'),
    ]

    operations = [
    ]
