# Generated by Django 5.1.11 on 2025-10-24 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_alter_homepage_body'),
        ('home', '0028_merge_20251024_1024'),
    ]

    operations = [
    ]
