# Generated by Django 5.1.11 on 2025-10-28 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_merge_20251028_1505'),
        ('home', '0029_alter_homepage_body'),
    ]

    operations = [
    ]
