# Generated by Django 5.1.11 on 2025-10-29 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_alter_homepage_body'),
        ('home', '0030_merge_20251028_1615'),
    ]

    operations = [
    ]
