# Generated by Django 5.1.11 on 2025-11-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_alter_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='descricao',
            field=models.TextField(blank=True, help_text='Descrição da página, utilizada em SEO e redes sociais', verbose_name='Descrição'),
        ),
    ]
