# Generated by Django 5.2.8 on 2025-11-08 01:56

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.RichTextField(blank=True, verbose_name='Conteúdo')),
            ],
            options={
                'verbose_name': 'Página Inicial',
                'verbose_name_plural': 'Páginas Iniciais',
            },
            bases=('wagtailcore.page',),
        ),
    ]
