# Generated by Django 5.1.14 on 2025-11-25 16:52

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitucionalIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Página Index Institucional',
                'verbose_name_plural': 'Páginas Institucionais',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='EquipePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('descricao', models.TextField(blank=True, help_text='Descrição da página, utilizada em SEO e redes sociais', verbose_name='Descrição')),
                ('conteudo', wagtail.fields.StreamField([('hero', 7), ('richtext_section', 10), ('features_grid', 17)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Título principal do hero (ex: NEUROATHENA)', 'max_length': 100, 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Subtítulo descritivo (ex: Sistema Multimodal de Triagem...)', 'max_length': 200, 'required': True}), 2: ('wagtail.blocks.TextBlock', (), {'help_text': 'Descrição detalhada do sistema', 'max_length': 500, 'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'default': 'Acessar Painel', 'help_text': 'Texto do botão principal', 'max_length': 50, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'default': '/painel/', 'help_text': 'URL do botão principal', 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'default': 'Admin Wagtail', 'help_text': 'Texto do botão secundário', 'max_length': 50, 'required': False}), 6: ('wagtail.blocks.URLBlock', (), {'default': '/cms/', 'help_text': 'URL do botão secundário', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('titulo', 0), ('subtitulo', 1), ('descricao', 2), ('cta_primario_texto', 3), ('cta_primario_url', 4), ('cta_secundario_texto', 5), ('cta_secundario_url', 6)]], {}), 8: ('wagtail.blocks.CharBlock', (), {'label': 'Título', 'max_length': 200, 'required': False}), 9: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'h4', 'bold', 'italic', 'link', 'ul', 'ol', 'hr', 'document-link', 'image', 'embed'], 'label': 'Conteúdo'}), 10: ('wagtail.blocks.StructBlock', [[('titulo', 8), ('conteudo', 9)]], {}), 11: ('wagtail.blocks.CharBlock', (), {'default': 'Recursos Principais', 'help_text': 'Título da seção de funcionalidades', 'max_length': 100, 'required': True}), 12: ('wagtail.blocks.CharBlock', (), {'help_text': 'Emoji do ícone (ex: 🧠, 📊, 👥)', 'max_length': 10, 'required': True}), 13: ('wagtail.blocks.CharBlock', (), {'help_text': 'Título da funcionalidade', 'max_length': 100, 'required': True}), 14: ('wagtail.blocks.TextBlock', (), {'help_text': 'Descrição breve da funcionalidade', 'max_length': 300, 'required': True}), 15: ('wagtail.blocks.StructBlock', [[('icone', 12), ('titulo', 13), ('descricao', 14)]], {}), 16: ('wagtail.blocks.ListBlock', (15,), {'help_text': 'Cards de funcionalidades (recomendado: 3, 6 ou 9 para grid)', 'max_num': 9, 'min_num': 1}), 17: ('wagtail.blocks.StructBlock', [[('titulo_secao', 11), ('funcionalidades', 16)]], {})}, verbose_name='Conteúdo da página')),
                ('imagem_destaque', models.ForeignKey(blank=True, help_text='Imagem usada em destaque para SEO e redes sociais', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagem de Destaque')),
            ],
            options={
                'verbose_name': 'Página Equipe',
                'verbose_name_plural': 'Páginas Equipe',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='LocalizacaoPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('descricao', models.TextField(blank=True, help_text='Descrição da página, utilizada em SEO e redes sociais', verbose_name='Descrição')),
                ('body', wagtail.fields.StreamField([('localizacoes', 9)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Localização', 'help_text': 'Título da seção de localização', 'max_length': 255, 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Nome do local', 'max_length': 255, 'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Endereço completo', 'max_length': 255, 'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'CEP', 'max_length': 40, 'required': True}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Número de telefone', 'max_length': 40, 'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Horário de atendimento. Ex.: das 8h às 16h30', 'max_length': 100, 'required': True}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Imagem do local (opcional)', 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'default': 'Como Chegar', 'help_text': 'Título da seção antes do mapa', 'max_length': 255, 'required': True}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Cole aqui o código HTML do iframe fornecido pelo Google Maps (menu Compartilhar > Incorporar um mapa).', 'label': 'HTML do Google Maps (iframe)', 'required': True}), 9: ('wagtail.blocks.StructBlock', [[('titulo_secao_localizacao', 0), ('nome_local', 1), ('endereco', 2), ('cep', 3), ('telefone', 4), ('horario_atendimento', 5), ('imagem', 6), ('titulo_secao_mapa', 7), ('iframe_google_maps', 8)]], {})}, verbose_name='Conteúdo da página')),
                ('imagem_destaque', models.ForeignKey(blank=True, help_text='Imagem usada em destaque para SEO e redes sociais', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagem de Destaque')),
            ],
            options={
                'verbose_name': 'Página de Localização',
                'verbose_name_plural': 'Páginas de Localização',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='MembroEquipePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('descricao', models.TextField(blank=True, help_text='Descrição da página, utilizada em SEO e redes sociais', verbose_name='Descrição')),
                ('cargo', models.CharField(blank=True, max_length=100, verbose_name='Cargo')),
                ('especialidade', models.CharField(blank=True, max_length=200, verbose_name='Especialidade')),
                ('conteudo', wagtail.fields.StreamField([('richtext_section', 2), ('image_text', 8)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Título', 'max_length': 200, 'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'h4', 'bold', 'italic', 'link', 'ul', 'ol', 'hr', 'document-link', 'image', 'embed'], 'label': 'Conteúdo'}), 2: ('wagtail.blocks.StructBlock', [[('titulo', 0), ('conteudo', 1)]], {}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagem'}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('esquerda', 'Esquerda'), ('direita', 'Direita')], 'label': 'Posição da Imagem'}), 5: ('wagtail.blocks.RichTextBlock', (), {'features': ['h3', 'h4', 'bold', 'italic', 'link', 'ul', 'ol'], 'label': 'Texto'}), 6: ('wagtail.blocks.URLBlock', (), {'label': 'Link do Botão', 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'label': 'Texto do Botão', 'max_length': 50, 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('imagem', 3), ('alinhamento', 4), ('titulo', 0), ('texto', 5), ('link', 6), ('texto_link', 7)]], {})}, verbose_name='Biografia e informações')),
                ('imagem_destaque', models.ForeignKey(blank=True, help_text='Imagem usada em destaque para SEO e redes sociais', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagem de Destaque')),
            ],
            options={
                'verbose_name': 'Membro da Equipe',
                'verbose_name_plural': 'Membros da Equipe',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='MissaoVisaoPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('descricao', models.TextField(blank=True, help_text='Descrição da página, utilizada em SEO e redes sociais', verbose_name='Descrição')),
                ('conteudo', wagtail.fields.StreamField([('hero', 7), ('richtext_section', 10), ('features_grid', 17), ('image_text', 23)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Título principal do hero (ex: NEUROATHENA)', 'max_length': 100, 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Subtítulo descritivo (ex: Sistema Multimodal de Triagem...)', 'max_length': 200, 'required': True}), 2: ('wagtail.blocks.TextBlock', (), {'help_text': 'Descrição detalhada do sistema', 'max_length': 500, 'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'default': 'Acessar Painel', 'help_text': 'Texto do botão principal', 'max_length': 50, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'default': '/painel/', 'help_text': 'URL do botão principal', 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'default': 'Admin Wagtail', 'help_text': 'Texto do botão secundário', 'max_length': 50, 'required': False}), 6: ('wagtail.blocks.URLBlock', (), {'default': '/cms/', 'help_text': 'URL do botão secundário', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('titulo', 0), ('subtitulo', 1), ('descricao', 2), ('cta_primario_texto', 3), ('cta_primario_url', 4), ('cta_secundario_texto', 5), ('cta_secundario_url', 6)]], {}), 8: ('wagtail.blocks.CharBlock', (), {'label': 'Título', 'max_length': 200, 'required': False}), 9: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'h4', 'bold', 'italic', 'link', 'ul', 'ol', 'hr', 'document-link', 'image', 'embed'], 'label': 'Conteúdo'}), 10: ('wagtail.blocks.StructBlock', [[('titulo', 8), ('conteudo', 9)]], {}), 11: ('wagtail.blocks.CharBlock', (), {'default': 'Recursos Principais', 'help_text': 'Título da seção de funcionalidades', 'max_length': 100, 'required': True}), 12: ('wagtail.blocks.CharBlock', (), {'help_text': 'Emoji do ícone (ex: 🧠, 📊, 👥)', 'max_length': 10, 'required': True}), 13: ('wagtail.blocks.CharBlock', (), {'help_text': 'Título da funcionalidade', 'max_length': 100, 'required': True}), 14: ('wagtail.blocks.TextBlock', (), {'help_text': 'Descrição breve da funcionalidade', 'max_length': 300, 'required': True}), 15: ('wagtail.blocks.StructBlock', [[('icone', 12), ('titulo', 13), ('descricao', 14)]], {}), 16: ('wagtail.blocks.ListBlock', (15,), {'help_text': 'Cards de funcionalidades (recomendado: 3, 6 ou 9 para grid)', 'max_num': 9, 'min_num': 1}), 17: ('wagtail.blocks.StructBlock', [[('titulo_secao', 11), ('funcionalidades', 16)]], {}), 18: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagem'}), 19: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('esquerda', 'Esquerda'), ('direita', 'Direita')], 'label': 'Posição da Imagem'}), 20: ('wagtail.blocks.RichTextBlock', (), {'features': ['h3', 'h4', 'bold', 'italic', 'link', 'ul', 'ol'], 'label': 'Texto'}), 21: ('wagtail.blocks.URLBlock', (), {'label': 'Link do Botão', 'required': False}), 22: ('wagtail.blocks.CharBlock', (), {'label': 'Texto do Botão', 'max_length': 50, 'required': False}), 23: ('wagtail.blocks.StructBlock', [[('imagem', 18), ('alinhamento', 19), ('titulo', 8), ('texto', 20), ('link', 21), ('texto_link', 22)]], {})}, verbose_name='Conteúdo da página')),
                ('imagem_destaque', models.ForeignKey(blank=True, help_text='Imagem usada em destaque para SEO e redes sociais', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagem de Destaque')),
            ],
            options={
                'verbose_name': 'Página Missão e Visão',
                'verbose_name_plural': 'Páginas Missão e Visão',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ParceriasPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('descricao', models.TextField(blank=True, help_text='Descrição da página, utilizada em SEO e redes sociais', verbose_name='Descrição')),
                ('conteudo', wagtail.fields.StreamField([('hero', 7), ('richtext_section', 10), ('features_grid', 17), ('statistics', 24)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Título principal do hero (ex: NEUROATHENA)', 'max_length': 100, 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Subtítulo descritivo (ex: Sistema Multimodal de Triagem...)', 'max_length': 200, 'required': True}), 2: ('wagtail.blocks.TextBlock', (), {'help_text': 'Descrição detalhada do sistema', 'max_length': 500, 'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'default': 'Acessar Painel', 'help_text': 'Texto do botão principal', 'max_length': 50, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'default': '/painel/', 'help_text': 'URL do botão principal', 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'default': 'Admin Wagtail', 'help_text': 'Texto do botão secundário', 'max_length': 50, 'required': False}), 6: ('wagtail.blocks.URLBlock', (), {'default': '/cms/', 'help_text': 'URL do botão secundário', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('titulo', 0), ('subtitulo', 1), ('descricao', 2), ('cta_primario_texto', 3), ('cta_primario_url', 4), ('cta_secundario_texto', 5), ('cta_secundario_url', 6)]], {}), 8: ('wagtail.blocks.CharBlock', (), {'label': 'Título', 'max_length': 200, 'required': False}), 9: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'h4', 'bold', 'italic', 'link', 'ul', 'ol', 'hr', 'document-link', 'image', 'embed'], 'label': 'Conteúdo'}), 10: ('wagtail.blocks.StructBlock', [[('titulo', 8), ('conteudo', 9)]], {}), 11: ('wagtail.blocks.CharBlock', (), {'default': 'Recursos Principais', 'help_text': 'Título da seção de funcionalidades', 'max_length': 100, 'required': True}), 12: ('wagtail.blocks.CharBlock', (), {'help_text': 'Emoji do ícone (ex: 🧠, 📊, 👥)', 'max_length': 10, 'required': True}), 13: ('wagtail.blocks.CharBlock', (), {'help_text': 'Título da funcionalidade', 'max_length': 100, 'required': True}), 14: ('wagtail.blocks.TextBlock', (), {'help_text': 'Descrição breve da funcionalidade', 'max_length': 300, 'required': True}), 15: ('wagtail.blocks.StructBlock', [[('icone', 12), ('titulo', 13), ('descricao', 14)]], {}), 16: ('wagtail.blocks.ListBlock', (15,), {'help_text': 'Cards de funcionalidades (recomendado: 3, 6 ou 9 para grid)', 'max_num': 9, 'min_num': 1}), 17: ('wagtail.blocks.StructBlock', [[('titulo_secao', 11), ('funcionalidades', 16)]], {}), 18: ('wagtail.blocks.CharBlock', (), {'label': 'Título da Seção', 'max_length': 200, 'required': False}), 19: ('wagtail.blocks.CharBlock', (), {'help_text': "Ex: '95%', '1000+'", 'label': 'Número', 'max_length': 20}), 20: ('wagtail.blocks.CharBlock', (), {'label': 'Descrição', 'max_length': 100}), 21: ('wagtail.blocks.TextBlock', (), {'label': 'Descrição Detalhada', 'max_length': 200, 'required': False}), 22: ('wagtail.blocks.StructBlock', [[('numero', 19), ('label', 20), ('descricao', 21)]], {}), 23: ('wagtail.blocks.ListBlock', (22,), {'label': 'Estatísticas', 'max_num': 6, 'min_num': 2}), 24: ('wagtail.blocks.StructBlock', [[('titulo', 18), ('estatisticas', 23)]], {})}, verbose_name='Conteúdo da página')),
                ('imagem_destaque', models.ForeignKey(blank=True, help_text='Imagem usada em destaque para SEO e redes sociais', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagem de Destaque')),
            ],
            options={
                'verbose_name': 'Página Parcerias',
                'verbose_name_plural': 'Páginas Parcerias',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SobreNosPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('descricao', models.TextField(blank=True, help_text='Descrição da página, utilizada em SEO e redes sociais', verbose_name='Descrição')),
                ('conteudo', wagtail.fields.StreamField([('hero', 7), ('richtext_section', 10), ('image_text', 16), ('statistics', 23), ('timeline', 29), ('testimonial', 36)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Título principal do hero (ex: NEUROATHENA)', 'max_length': 100, 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Subtítulo descritivo (ex: Sistema Multimodal de Triagem...)', 'max_length': 200, 'required': True}), 2: ('wagtail.blocks.TextBlock', (), {'help_text': 'Descrição detalhada do sistema', 'max_length': 500, 'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'default': 'Acessar Painel', 'help_text': 'Texto do botão principal', 'max_length': 50, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'default': '/painel/', 'help_text': 'URL do botão principal', 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'default': 'Admin Wagtail', 'help_text': 'Texto do botão secundário', 'max_length': 50, 'required': False}), 6: ('wagtail.blocks.URLBlock', (), {'default': '/cms/', 'help_text': 'URL do botão secundário', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('titulo', 0), ('subtitulo', 1), ('descricao', 2), ('cta_primario_texto', 3), ('cta_primario_url', 4), ('cta_secundario_texto', 5), ('cta_secundario_url', 6)]], {}), 8: ('wagtail.blocks.CharBlock', (), {'label': 'Título', 'max_length': 200, 'required': False}), 9: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'h4', 'bold', 'italic', 'link', 'ul', 'ol', 'hr', 'document-link', 'image', 'embed'], 'label': 'Conteúdo'}), 10: ('wagtail.blocks.StructBlock', [[('titulo', 8), ('conteudo', 9)]], {}), 11: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagem'}), 12: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('esquerda', 'Esquerda'), ('direita', 'Direita')], 'label': 'Posição da Imagem'}), 13: ('wagtail.blocks.RichTextBlock', (), {'features': ['h3', 'h4', 'bold', 'italic', 'link', 'ul', 'ol'], 'label': 'Texto'}), 14: ('wagtail.blocks.URLBlock', (), {'label': 'Link do Botão', 'required': False}), 15: ('wagtail.blocks.CharBlock', (), {'label': 'Texto do Botão', 'max_length': 50, 'required': False}), 16: ('wagtail.blocks.StructBlock', [[('imagem', 11), ('alinhamento', 12), ('titulo', 8), ('texto', 13), ('link', 14), ('texto_link', 15)]], {}), 17: ('wagtail.blocks.CharBlock', (), {'label': 'Título da Seção', 'max_length': 200, 'required': False}), 18: ('wagtail.blocks.CharBlock', (), {'help_text': "Ex: '95%', '1000+'", 'label': 'Número', 'max_length': 20}), 19: ('wagtail.blocks.CharBlock', (), {'label': 'Descrição', 'max_length': 100}), 20: ('wagtail.blocks.TextBlock', (), {'label': 'Descrição Detalhada', 'max_length': 200, 'required': False}), 21: ('wagtail.blocks.StructBlock', [[('numero', 18), ('label', 19), ('descricao', 20)]], {}), 22: ('wagtail.blocks.ListBlock', (21,), {'label': 'Estatísticas', 'max_num': 6, 'min_num': 2}), 23: ('wagtail.blocks.StructBlock', [[('titulo', 17), ('estatisticas', 22)]], {}), 24: ('wagtail.blocks.CharBlock', (), {'help_text': "Ex: '2023', '2024'", 'label': 'Ano', 'max_length': 10, 'required': False}), 25: ('wagtail.blocks.CharBlock', (), {'label': 'Título', 'max_length': 100}), 26: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'label': 'Descrição'}), 27: ('wagtail.blocks.StructBlock', [[('ano', 24), ('titulo', 25), ('descricao', 26)]], {}), 28: ('wagtail.blocks.ListBlock', (27,), {'label': 'Eventos', 'max_num': 10, 'min_num': 2}), 29: ('wagtail.blocks.StructBlock', [[('titulo', 17), ('eventos', 28)]], {}), 30: ('wagtail.blocks.CharBlock', (), {'label': 'Nome', 'max_length': 100}), 31: ('wagtail.blocks.CharBlock', (), {'label': 'Função/Cargo', 'max_length': 100, 'required': False}), 32: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Foto', 'required': False}), 33: ('wagtail.blocks.TextBlock', (), {'label': 'Depoimento', 'max_length': 500}), 34: ('wagtail.blocks.StructBlock', [[('nome', 30), ('cargo', 31), ('foto', 32), ('texto', 33)]], {}), 35: ('wagtail.blocks.ListBlock', (34,), {'label': 'Depoimentos', 'max_num': 6, 'min_num': 1}), 36: ('wagtail.blocks.StructBlock', [[('titulo', 17), ('depoimentos', 35)]], {})}, verbose_name='Conteúdo da página')),
                ('imagem_destaque', models.ForeignKey(blank=True, help_text='Imagem usada em destaque para SEO e redes sociais', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagem de Destaque')),
            ],
            options={
                'verbose_name': 'Página Sobre Nós',
                'verbose_name_plural': 'Páginas Sobre Nós',
            },
            bases=('wagtailcore.page',),
        ),
    ]
