# Generated by Django 5.1.11 on 2025-10-02 14:22

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitucionalIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Página Index Institucional',
                'verbose_name_plural': 'Páginas Institucionais',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='LocalizacaoPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('descricao', models.TextField(blank=True, help_text='Descrição da página para SEO e redes sociais', verbose_name='Descrição')),
                ('body', wagtail.fields.StreamField([('localizacoes', 9)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Localização', 'help_text': 'Título da seção de localização', 'max_length': 255, 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Nome do local', 'max_length': 255, 'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Endereço completo', 'max_length': 255, 'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'CEP', 'max_length': 40, 'required': True}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Número de telefone', 'max_length': 40, 'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Horário de atendimento. Ex.: das 8h às 16h30', 'max_length': 100, 'required': True}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Imagem do local (opcional)', 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'default': 'Como Chegar', 'help_text': 'Título da seção antes do mapa', 'max_length': 255, 'required': True}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Cole aqui o código HTML do iframe fornecido pelo Google Maps (menu Compartilhar > Incorporar um mapa).', 'label': 'HTML do Google Maps (iframe)', 'required': True}), 9: ('wagtail.blocks.StructBlock', [[('titulo_secao_localizacao', 0), ('nome_local', 1), ('endereco', 2), ('cep', 3), ('telefone', 4), ('horario_atendimento', 5), ('imagem', 6), ('titulo_secao_mapa', 7), ('iframe_google_maps', 8)]], {})}, verbose_name='Conteúdo da página')),
            ],
            options={
                'verbose_name': 'Página de Localização',
                'verbose_name_plural': 'Páginas de Localização',
            },
            bases=('wagtailcore.page',),
        ),
    ]
