# Generated by Django 5.1.11 on 2025-08-07 13:19

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalizacaoPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('endereco', models.CharField(help_text='Endereço completo', max_length=255)),
                ('cep', models.CharField(help_text='CEP', max_length=10)),
                ('telefone', models.CharField(help_text='Número de telefone', max_length=20)),
                ('cidade_estado', models.CharField(help_text='Cidade e Estado', max_length=100)),
                ('horario_atendimento', models.CharField(help_text='Horário de atendimento', max_length=100)),
                ('nome_local', models.CharField(help_text='Nome do local', max_length=255)),
                ('body', wagtail.fields.StreamField([('google_maps_embed', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Cole aqui o código HTML do iframe fornecido pelo Google Maps (menu Compartilhar > Incorporar um mapa).', 'label': 'HTML do Google Maps (iframe)', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'default': '100%', 'help_text': 'Exemplo: 100% ou 600', 'label': 'Largura', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'default': '400', 'help_text': 'Exemplo: 400', 'label': 'Altura', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('iframe_html', 0), ('largura', 1), ('altura', 2)]], {})}, verbose_name='Conteúdo da página')),
            ],
            options={
                'verbose_name': 'Página de Localização',
                'verbose_name_plural': 'Páginas de Localização',
            },
            bases=('wagtailcore.page',),
        ),
    ]
