# Generated by Django 5.1.11 on 2025-10-15 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0001_initial'),
        ('paginas', '0001_initial'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecretariadoGrupoPageIndex',
            fields=[
                ('corpotecnicogrupopageindex_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='paginas.corpotecnicogrupopageindex')),
            ],
            options={
                'abstract': False,
            },
            bases=('paginas.corpotecnicogrupopageindex',),
        ),
        migrations.CreateModel(
            name='SecretariadoIndex',
            fields=[
                ('corpotecnicoindexpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='paginas.corpotecnicoindexpage')),
            ],
            options={
                'abstract': False,
            },
            bases=('paginas.corpotecnicoindexpage',),
        ),
        migrations.CreateModel(
            name='SecretariadoPage',
            fields=[
                ('corpotecnicopage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='paginas.corpotecnicopage')),
            ],
            options={
                'abstract': False,
            },
            bases=('paginas.corpotecnicopage',),
        ),
        migrations.AddField(
            model_name='localizacaopage',
            name='imagem_destaque',
            field=models.ForeignKey(blank=True, help_text='Imagem usada em destaque para SEO e redes sociais', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagem de Destaque'),
        ),
    ]
