# Generated by Django 5.1.11 on 2025-08-07 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0002_remove_localizacaopage_cep_and_more'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitucionalIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Página Institucional',
                'verbose_name_plural': 'Páginas Institucionais',
            },
            bases=('wagtailcore.page',),
        ),
    ]
