# Generated by Django 5.1.11 on 2025-11-03 13:48

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0002_secretariadogrupopageindex_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secretariadoindex',
            name='grupos_corpo_tecnico',
            field=wagtail.fields.StreamField([('grupo', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Título do Grupo', 'max_length': 255, 'required': False}), 1: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Selecione a página do grupo do secretariado', 'page_type': ['institucional.SecretariadoGrupoPageIndex'], 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('titulo', 0), ('grupo_page', 1)]], {'label': 'Grupo do Secretariado'})}, null=True, verbose_name='Grupos do Secretariado'),
        ),
    ]
