# Generated by Django 5.1.11 on 2025-08-11 16:52

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0004_alter_localizacaopage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localizacaopage',
            name='body',
            field=wagtail.fields.StreamField([('localizacoes', 7)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Nome do local', 'max_length': 255, 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Endereço completo', 'max_length': 255, 'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'CEP', 'max_length': 40, 'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Número de telefone', 'max_length': 40, 'required': True}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Horário de atendimento. Ex.: das 8h às 16h30', 'max_length': 100, 'required': True}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Imagem do local (opcional)', 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'Cole aqui o código HTML do iframe fornecido pelo Google Maps (menu Compartilhar > Incorporar um mapa).', 'label': 'HTML do Google Maps (iframe)', 'required': True}), 7: ('wagtail.blocks.StructBlock', [[('nome_local', 0), ('endereco', 1), ('cep', 2), ('telefone', 3), ('horario_atendimento', 4), ('imagem', 5), ('iframe_google_maps', 6)]], {})}, verbose_name='Conteúdo da página'),
        ),
    ]
