# Generated by Django 5.1.11 on 2025-08-22 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0005_alter_localizacaopage_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institucionalindexpage',
            options={'verbose_name': 'Página Index Institucional', 'verbose_name_plural': 'Páginas Institucionais'},
        ),
    ]
