# Generated by Django 5.1.11 on 2025-09-03 12:16

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0006_alter_institucionalindexpage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localizacaopage',
            name='body',
            field=wagtail.fields.StreamField([('localizacoes', 9)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Localização', 'help_text': 'Título da seção de localização', 'max_length': 255, 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Nome do local', 'max_length': 255, 'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Endereço completo', 'max_length': 255, 'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'CEP', 'max_length': 40, 'required': True}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Número de telefone', 'max_length': 40, 'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Horário de atendimento. Ex.: das 8h às 16h30', 'max_length': 100, 'required': True}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Imagem do local (opcional)', 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'default': 'Como Chegar', 'help_text': 'Título da seção antes do mapa', 'max_length': 255, 'required': True}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Cole aqui o código HTML do iframe fornecido pelo Google Maps (menu Compartilhar > Incorporar um mapa).', 'label': 'HTML do Google Maps (iframe)', 'required': True}), 9: ('wagtail.blocks.StructBlock', [[('titulo_secao_localizacao', 0), ('nome_local', 1), ('endereco', 2), ('cep', 3), ('telefone', 4), ('horario_atendimento', 5), ('imagem', 6), ('titulo_secao_mapa', 7), ('iframe_google_maps', 8)]], {})}, verbose_name='Conteúdo da página'),
        ),
    ]
