# Generated by Django 5.1.11 on 2025-09-30 15:36

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0007_alter_localizacaopage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='localizacaopage',
            name='descricao',
            field=models.TextField(blank=True, help_text='Descrição da página para SEO e redes sociais', verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='localizacaopage',
            name='images',
            field=wagtail.fields.StreamField([('image', 0)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagem'})}, help_text='Imagens relacionadas à página', verbose_name='Imagens'),
        ),
    ]
