# Generated by Django 5.1.13 on 2025-10-09 11:34

import datetime
import django.db.models.deletion
import wagtail.contrib.routable_page.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditaisIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Página de Índice de Editais',
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='EditalPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('images', wagtail.fields.StreamField([('image', 0)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagem'})}, help_text='Imagens relacionadas à página', verbose_name='Imagens')),
                ('numero', models.CharField(max_length=50, verbose_name='Número do Edital')),
                ('ano', models.IntegerField(default=2025, verbose_name='Ano do Edital')),
                ('descricao', wagtail.fields.RichTextField(help_text='Breve descrição sobre o objetivo do edital.', verbose_name='Descrição do Edital')),
                ('data_publicacao', models.DateField(default=datetime.datetime.today, verbose_name='Data de publicação do edital')),
                ('situacao', models.CharField(choices=[('aberto', 'Aberto'), ('em_andamento', 'Em Andamento'), ('encerrado', 'Encerrado'), ('suspenso', 'Suspenso'), ('cancelado', 'Cancelado')], default='aberto', max_length=20, verbose_name='Situação do Edital')),
                ('fases_edital', wagtail.fields.StreamField([('fase', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Título da Fase', 'required': True}), 1: ('wagtail.blocks.DateTimeBlock', (), {'label': 'Data e Hora da Fase', 'required': True}), 2: ('wagtail.blocks.RichTextBlock', (), {'label': 'Descrição da Fase', 'required': False}), 3: ('blocks.models.EspecificDocumentChooserBlock', (), {'label': 'Arquivo', 'required': False}), 4: ('wagtail.blocks.ListBlock', (3,), {'label': 'Arquivos da Fase', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('titulo_fase', 0), ('data_fase', 1), ('descricao', 2), ('arquivos', 4)]], {})}, help_text='Adicione as fases do edital, como abertura, inscrições, retificações, resultados, etc.', verbose_name='Fases do Edital (Ciclo de Vida)')),
            ],
            options={
                'verbose_name': 'Página de Edital',
                'verbose_name_plural': 'Páginas de Editais',
            },
            bases=('wagtailcore.page',),
        ),
    ]
