# Generated by Django 5.1.13 on 2025-10-09 13:02

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editais', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editalpage',
            name='fases_edital',
            field=wagtail.fields.StreamField([('fase', 9)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Título da Fase', 'required': True}), 1: ('wagtail.blocks.DateTimeBlock', (), {'label': 'Data e Hora da Fase', 'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Nome para exibição do arquivo', 'required': True}), 3: ('blocks.models.EspecificDocumentChooserBlock', (), {'label': 'Arquivo', 'required': True}), 4: ('wagtail.blocks.StructBlock', [[('nome_documento', 2), ('documento', 3)]], {'icon': 'doc-full-inverse', 'label': 'Arquivo'}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Nome para exibição do link', 'required': True}), 6: ('wagtail.blocks.URLBlock', (), {'label': 'URL do link externo', 'required': True}), 7: ('wagtail.blocks.StructBlock', [[('nome_link', 5), ('url', 6)]], {'icon': 'link', 'label': 'Link Externo'}), 8: ('wagtail.blocks.StreamBlock', [[('arquivo', 4), ('link_externo', 7)]], {'required': False}), 9: ('wagtail.blocks.StructBlock', [[('titulo_fase', 0), ('data_fase', 1), ('anexo', 8)]], {})}, help_text='Adicione as fases do edital, como abertura, inscrições, retificações, resultados, etc.', verbose_name='Fases do Edital (Ciclo de Vida)'),
        ),
    ]
