# Generated by Django 5.1.13 on 2025-10-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editais', '0002_alter_editalpage_fases_edital'),
    ]

    operations = [
        migrations.AddField(
            model_name='editalpage',
            name='rotulo_numero',
            field=models.CharField(default='Nº', help_text='Texto que precede o número. Ex: Nº, Processo.', max_length=20, verbose_name='Rótulo do Número'),
        ),
        migrations.AddField(
            model_name='editalpage',
            name='tipo_publicacao',
            field=models.CharField(default='Edital', help_text='Ex: Edital, Chamada Pública, Aviso de Licitação.', max_length=100, verbose_name='Tipo de Publicação'),
        ),
    ]
