# Generated by Django 5.1.13 on 2025-10-20 13:03

import datetime
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editais', '0003_editalpage_rotulo_numero_editalpage_tipo_publicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editalpage',
            name='ano',
            field=models.IntegerField(default=2025, verbose_name='Ano'),
        ),
        migrations.AlterField(
            model_name='editalpage',
            name='data_publicacao',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Data de publicação'),
        ),
        migrations.AlterField(
            model_name='editalpage',
            name='descricao',
            field=wagtail.fields.RichTextField(help_text='Breve descrição sobre o objeto.', verbose_name='Descrição da Publicação'),
        ),
        migrations.AlterField(
            model_name='editalpage',
            name='fases_edital',
            field=wagtail.fields.StreamField([('fase', 9)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Título da Fase', 'required': True}), 1: ('wagtail.blocks.DateTimeBlock', (), {'label': 'Data e Hora da Fase', 'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Nome para exibição do arquivo', 'required': True}), 3: ('blocks.models.EspecificDocumentChooserBlock', (), {'label': 'Arquivo', 'required': True}), 4: ('wagtail.blocks.StructBlock', [[('nome_documento', 2), ('documento', 3)]], {'icon': 'doc-full-inverse', 'label': 'Arquivo'}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Nome para exibição do link', 'required': True}), 6: ('wagtail.blocks.URLBlock', (), {'label': 'URL do link externo', 'required': True}), 7: ('wagtail.blocks.StructBlock', [[('nome_link', 5), ('url', 6)]], {'icon': 'link', 'label': 'Link Externo'}), 8: ('wagtail.blocks.StreamBlock', [[('arquivo', 4), ('link_externo', 7)]], {'required': False}), 9: ('wagtail.blocks.StructBlock', [[('titulo_fase', 0), ('data_fase', 1), ('anexo', 8)]], {})}, help_text='Adicione as fases da publicação, como abertura, inscrições, retificações, resultados, etc.', verbose_name='Fases (Ciclo de Vida)'),
        ),
        migrations.AlterField(
            model_name='editalpage',
            name='numero',
            field=models.CharField(max_length=50, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='editalpage',
            name='situacao',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('em_andamento', 'Em Andamento'), ('encerrado', 'Encerrado'), ('suspenso', 'Suspenso'), ('cancelado', 'Cancelado')], default='aberto', max_length=20, verbose_name='Situação da Publicação'),
        ),
    ]

# Generated by Django 5.1.11 on 2025-10-17 11:01

import datetime
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editais', '0003_editalpage_rotulo_numero_editalpage_tipo_publicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editalpage',
            name='ano',
            field=models.IntegerField(default=2025, verbose_name='Ano'),
        ),
        migrations.AlterField(
            model_name='editalpage',
            name='data_publicacao',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Data de publicação'),
        ),
        migrations.AlterField(
            model_name='editalpage',
            name='descricao',
            field=wagtail.fields.RichTextField(help_text='Breve descrição sobre o objeto.', verbose_name='Descrição da Publicação'),
        ),
        migrations.AlterField(
            model_name='editalpage',
            name='fases_edital',
            field=wagtail.fields.StreamField([('fase', 9)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Título da Fase', 'required': True}), 1: ('wagtail.blocks.DateTimeBlock', (), {'label': 'Data e Hora da Fase', 'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Nome para exibição do arquivo', 'required': True}), 3: ('blocks.models.EspecificDocumentChooserBlock', (), {'label': 'Arquivo', 'required': True}), 4: ('wagtail.blocks.StructBlock', [[('nome_documento', 2), ('documento', 3)]], {'icon': 'doc-full-inverse', 'label': 'Arquivo'}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Nome para exibição do link', 'required': True}), 6: ('wagtail.blocks.URLBlock', (), {'label': 'URL do link externo', 'required': True}), 7: ('wagtail.blocks.StructBlock', [[('nome_link', 5), ('url', 6)]], {'icon': 'link', 'label': 'Link Externo'}), 8: ('wagtail.blocks.StreamBlock', [[('arquivo', 4), ('link_externo', 7)]], {'required': False}), 9: ('wagtail.blocks.StructBlock', [[('titulo_fase', 0), ('data_fase', 1), ('anexo', 8)]], {})}, help_text='Adicione as fases da publicação, como abertura, inscrições, retificações, resultados, etc.', verbose_name='Fases (Ciclo de Vida)'),
        ),
        migrations.AlterField(
            model_name='editalpage',
            name='numero',
            field=models.CharField(max_length=50, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='editalpage',
            name='situacao',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('em_andamento', 'Em Andamento'), ('encerrado', 'Encerrado'), ('suspenso', 'Suspenso'), ('cancelado', 'Cancelado')], default='aberto', max_length=20, verbose_name='Situação da Publicação'),
        ),
    ]
