# Generated by Django 5.1.10 on 2025-06-11 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LinkCabecalho',
        ),
    ]
