# Generated by Django 5.1.10 on 2025-06-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('links', '0002_delete_linkcabecalho'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkCabecalhoItemBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título do Link')),
                ('url', models.URLField(help_text='O link no padrão ex.: https://www.detran.pb.gov.br/', max_length=255, verbose_name='URL')),
                ('target', models.CharField(choices=[('_self', 'Mesma Aba'), ('_blank', 'Nova Aba')], default='_self', max_length=10, verbose_name='Abrir Link em')),
            ],
            options={
                'verbose_name': 'Link para Cabeçalho',
                'verbose_name_plural': 'Links para Cabeçalho',
                'ordering': ['titulo'],
            },
        ),
    ]
