# Generated by Django 5.1.10 on 2025-06-12 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linkcabecalhoitemblock',
            options={'ordering': ['titulo'], 'verbose_name': 'Link do Menu', 'verbose_name_plural': 'Link do Menu'},
        ),
    ]
