# Generated by Django 5.1.11 on 2025-07-15 11:34

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0005_alter_linkcabecalhoitemblock_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('titulo', models.CharField(max_length=255, verbose_name='Título do Submenu')),
                ('url', models.URLField(max_length=255, verbose_name='URL')),
                ('target', models.CharField(choices=[('_self', 'Mesma Aba'), ('_blank', 'Nova Aba')], default='_self', max_length=10, verbose_name='Abrir Link em')),
                ('parent', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='submenus', to='links.linkcabecalhoitemblock')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
    ]
