# Generated by Django 5.1.13 on 2025-10-15 10:46

import django.core.validators
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.contrib.routable_page.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('section', 5)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Título da Seção', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Nome ou Setor', 'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Telefone', 'required': True, 'validators': [django.core.validators.RegexValidator(message='Use um formato de telefone válido, ex: (83) 3208-4451.', regex='^\\(?\\d{2}\\)?\\s?\\d{4,5}-?\\d{4}$')]}), 3: ('wagtail.blocks.StructBlock', [[('title', 1), ('phone', 2)]], {}), 4: ('wagtail.blocks.ListBlock', (3,), {}), 5: ('wagtail.blocks.StructBlock', [[('section_title', 0), ('contacts', 4)]], {})})),
                ('layout', models.CharField(choices=[('50_50', '2 Colunas'), ('100_col1', '1 Coluna')], default='50_50', max_length=10)),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='ContactPageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='contatos.contactpage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='contactpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='contatos.ContactPageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
