# Generated by Django 5.1.11 on 2025-10-28 17:34

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.contrib.routable_page.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContatosPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('coluna_1', wagtail.fields.StreamField([('contatos_section', 11)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Título da Seção', 'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('small', 'Pequeno'), ('medium', 'Médio'), ('large', 'Grande')], 'label': 'Tamanho do Título'}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('none', 'Sem marcador'), ('dot', 'Ponto •'), ('diamond', 'Diamante ♦'), ('triangle', 'Triângulo ►'), ('chevron', 'Ponta de Flecha ›'), ('black_diamond', 'Diamante Negro ◆')], 'label': 'Estilo da lista da seção'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Título (Ex: Presidência)', 'required': False}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('phone', 'Telefone'), ('email', 'E-mail'), ('whatsapp', 'WhatsApp'), ('text', 'Outro (Texto)')], 'label': 'Tipo de Contato'}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Informação', 'required': True}), 6: ('wagtail.blocks.StructBlock', [[('tipo', 4), ('info', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {'label': 'Informações de Contato'}), 8: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'label': 'Mostrar linha separadora após este grupo', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('titulo', 3), ('informacoes', 7), ('mostrar_linha_separadora', 8)]], {}), 10: ('wagtail.blocks.StreamBlock', [[('contato_simples', 9)]], {'label': 'Itens de Contato', 'use_json_field': True}), 11: ('wagtail.blocks.StructBlock', [[('section_title', 0), ('title_size', 1), ('list_style', 2), ('itens_contato', 10)]], {})}, verbose_name='Coluna 1')),
                ('coluna_2', wagtail.fields.StreamField([('contatos_section', 11)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Título da Seção', 'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('small', 'Pequeno'), ('medium', 'Médio'), ('large', 'Grande')], 'label': 'Tamanho do Título'}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('none', 'Sem marcador'), ('dot', 'Ponto •'), ('diamond', 'Diamante ♦'), ('triangle', 'Triângulo ►'), ('chevron', 'Ponta de Flecha ›'), ('black_diamond', 'Diamante Negro ◆')], 'label': 'Estilo da lista da seção'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Título (Ex: Presidência)', 'required': False}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('phone', 'Telefone'), ('email', 'E-mail'), ('whatsapp', 'WhatsApp'), ('text', 'Outro (Texto)')], 'label': 'Tipo de Contato'}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Informação', 'required': True}), 6: ('wagtail.blocks.StructBlock', [[('tipo', 4), ('info', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {'label': 'Informações de Contato'}), 8: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'label': 'Mostrar linha separadora após este grupo', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('titulo', 3), ('informacoes', 7), ('mostrar_linha_separadora', 8)]], {}), 10: ('wagtail.blocks.StreamBlock', [[('contato_simples', 9)]], {'label': 'Itens de Contato', 'use_json_field': True}), 11: ('wagtail.blocks.StructBlock', [[('section_title', 0), ('title_size', 1), ('list_style', 2), ('itens_contato', 10)]], {})}, verbose_name='Coluna 2')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='ContatosPageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='contatos.contatospage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='contatospage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='contatos.ContatosPageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
