# Generated by Django 5.1.13 on 2025-10-15 11:43

import django.core.validators
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0002_rename_contactpagetag_contatospagetag_contatospage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contatospage',
            name='layout',
        ),
        migrations.AddField(
            model_name='contatospage',
            name='titulo',
            field=models.CharField(default='Contatos', max_length=255, verbose_name='Título da Página'),
        ),
        migrations.AlterField(
            model_name='contatospage',
            name='body',
            field=wagtail.fields.StreamField([('coluna', 8)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('coluna_1', 'Primeira Coluna'), ('coluna_2', 'Segunda Coluna'), ('coluna_3', 'Widgets')], 'label': 'Posição do bloco na página'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Título da Seção', 'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Nome ou Setor', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Telefone', 'required': True, 'validators': [django.core.validators.RegexValidator(message='Use um formato de telefone válido, ex: (83) 3208-4451.', regex='^\\(?\\d{2}\\)?\\s?\\d{4,5}-?\\d{4}$')]}), 4: ('wagtail.blocks.StructBlock', [[('title', 2), ('phone', 3)]], {}), 5: ('wagtail.blocks.ListBlock', (4,), {}), 6: ('wagtail.blocks.StructBlock', [[('section_title', 1), ('contatos', 5)]], {}), 7: ('wagtail.blocks.StreamBlock', [[('contatos_section', 6)]], {'label': 'Conteúdo do bloco', 'required': True}), 8: ('wagtail.blocks.StructBlock', [[('coluna', 0), ('conteudo', 7)]], {})}, verbose_name='Conteúdo da Página'),
        ),
    ]
