# Generated by Django 5.1.13 on 2025-10-15 13:47

import django.core.validators
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0003_remove_contatospage_layout_contatospage_titulo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contatospage',
            name='body',
            field=wagtail.fields.StreamField([('coluna', 10)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('coluna_1', 'Primeira Coluna'), ('coluna_2', 'Segunda Coluna'), ('coluna_3', 'Widgets')], 'label': 'Posição do bloco na página'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Título da Seção', 'required': True}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('small', 'Pequeno'), ('medium', 'Médio'), ('large', 'Grande')], 'label': 'Tamanho do Título'}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('none', 'Sem marcador'), ('dot', 'Ponto •'), ('diamond', 'Diamante ♦'), ('arrow', 'Seta ➤'), ('triangle', 'Triângulo ▲'), ('chevron', 'Ponta de Flecha'), ('black_diamond', 'Diamante Negro ◆')], 'label': 'Estilo da lista de contatos'}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Nome ou Setor', 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Telefone', 'required': True, 'validators': [django.core.validators.RegexValidator(message='Use um formato de telefone válido, ex: (83) 3208-4451.', regex='^\\(?\\d{2}\\)?\\s?\\d{4,5}-?\\d{4}$')]}), 6: ('wagtail.blocks.StructBlock', [[('title', 4), ('phone', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {}), 8: ('wagtail.blocks.StructBlock', [[('section_title', 1), ('title_size', 2), ('list_style', 3), ('contatos', 7)]], {}), 9: ('wagtail.blocks.StreamBlock', [[('contatos_section', 8)]], {'label': 'Conteúdo do bloco', 'required': True}), 10: ('wagtail.blocks.StructBlock', [[('coluna', 0), ('conteudo', 9)]], {})}, verbose_name='Conteúdo da Página'),
        ),
    ]
