# Generated by Django 5.1.13 on 2025-10-21 14:03

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0004_alter_contatospage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='contatospage',
            name='layout',
            field=models.CharField(choices=[('40_40_20', 'Três Colunas (40/40/20)'), ('50_50', 'Duas Colunas (50/50)'), ('70_30', 'Duas Colunas (70/30)'), ('60_40', 'Duas Colunas (60/40)'), ('100_col1', 'Uma Coluna (Principal)'), ('100_col2', 'Uma Coluna (Secundária)'), ('100_widget', 'Uma Coluna (Widgets)')], default='50_50', max_length=20, verbose_name='Layout da Página'),
        ),
        migrations.AlterField(
            model_name='contatospage',
            name='body',
            field=wagtail.fields.StreamField([('coluna', 20)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('coluna_1', 'Primeira Coluna'), ('coluna_2', 'Segunda Coluna'), ('coluna_3', 'Widgets')], 'label': 'Posição do bloco na página'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Título da Seção', 'required': True}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('small', 'Pequeno'), ('medium', 'Médio'), ('large', 'Grande')], 'label': 'Tamanho do Título'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Título (Ex: Presidência)', 'required': False}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('none', 'Sem marcador'), ('dot', 'Ponto •'), ('diamond', 'Diamante ♦'), ('arrow', 'Seta ➤'), ('triangle', 'Triângulo ▲'), ('chevron', 'Ponta de Flecha ›'), ('black_diamond', 'Diamante Negro ◆')], 'label': 'Estilo da lista de contatos'}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('phone', 'Telefone'), ('email', 'E-mail'), ('whatsapp', 'WhatsApp'), ('text', 'Outro (Texto)')], 'label': 'Tipo de Contato'}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Informação', 'required': True}), 7: ('wagtail.blocks.StructBlock', [[('tipo', 5), ('info', 6)]], {}), 8: ('wagtail.blocks.ListBlock', (7,), {'label': 'Informações de Contato'}), 9: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'label': 'Mostrar linha separadora após este grupo', 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('titulo', 3), ('list_style', 4), ('informacoes', 8), ('mostrar_linha_separadora', 9)]], {}), 11: ('wagtail.blocks.CharBlock', (), {'label': 'Título do Grupo (Ex: Assessorias)', 'required': True}), 12: ('wagtail.blocks.CharBlock', (), {'label': 'Nome do Contato ou Setor', 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('titulo', 12), ('informacoes', 8)]], {}), 14: ('wagtail.blocks.ListBlock', (13,), {}), 15: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('none', 'Sem marcador'), ('dot', 'Ponto •'), ('diamond', 'Diamante ♦'), ('arrow', 'Seta ➤'), ('triangle', 'Triângulo ▲'), ('chevron', 'Ponta de Flecha'), ('black_diamond', 'Diamante Negro ◆')], 'label': 'Estilo da lista de contatos'}), 16: ('wagtail.blocks.StructBlock', [[('titulo_grupo', 11), ('mostrar_linha_separadora', 9), ('contatos', 14), ('list_style', 15)]], {}), 17: ('wagtail.blocks.StreamBlock', [[('contato_simples', 10), ('grupo_contatos', 16)]], {'label': 'Itens de Contato', 'use_json_field': True}), 18: ('wagtail.blocks.StructBlock', [[('section_title', 1), ('title_size', 2), ('itens_contato', 17)]], {}), 19: ('wagtail.blocks.StreamBlock', [[('contatos_section', 18)]], {'label': 'Conteúdo do bloco', 'required': True}), 20: ('wagtail.blocks.StructBlock', [[('coluna', 0), ('conteudo', 19)]], {})}, verbose_name='Conteúdo da Página'),
        ),
    ]
