# Generated by Django 5.1.13 on 2025-10-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0005_contatospage_layout_alter_contatospage_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contatospage',
            name='layout',
        ),
        migrations.AddField(
            model_name='contatospage',
            name='two_column_layout_choice',
            field=models.CharField(blank=True, choices=[('50_50', 'Duas Colunas (50/50)'), ('70_30', 'Duas Colunas (70/30)'), ('60_40', 'Duas Colunas (60/40)')], default='50_50', help_text='Selecione o layout para as duas colunas de conteúdo. Será ignorado se a página tiver 1 ou 3 colunas.', max_length=20, null=True, verbose_name='Escolha de Layout para Duas Colunas'),
        ),
    ]
