# Generated by Django 5.1.13 on 2025-10-24 14:31

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0008_remove_contatospage_coluna_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contatospage',
            name='body',
            field=wagtail.fields.StreamField([('contatos_section', 16)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Título da Seção', 'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('small', 'Pequeno'), ('medium', 'Médio'), ('large', 'Grande')], 'label': 'Tamanho do Título'}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Título (Ex: Presidência)', 'required': False}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('none', 'Sem marcador'), ('dot', 'Ponto •'), ('diamond', 'Diamante ♦'), ('arrow', 'Seta ➤'), ('triangle', 'Triângulo ▲'), ('chevron', 'Ponta de Flecha ›'), ('black_diamond', 'Diamante Negro ◆')], 'label': 'Estilo da lista de contatos'}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('phone', 'Telefone'), ('email', 'E-mail'), ('whatsapp', 'WhatsApp'), ('text', 'Outro (Texto)')], 'label': 'Tipo de Contato'}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Informação', 'required': True}), 6: ('wagtail.blocks.StructBlock', [[('tipo', 4), ('info', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {'label': 'Informações de Contato'}), 8: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'label': 'Mostrar linha separadora após este grupo', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('titulo', 2), ('list_style', 3), ('informacoes', 7), ('mostrar_linha_separadora', 8)]], {}), 10: ('wagtail.blocks.CharBlock', (), {'label': 'Título do Grupo (Ex: Assessorias)', 'required': True}), 11: ('wagtail.blocks.CharBlock', (), {'label': 'Nome do Contato ou Setor', 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('titulo', 11), ('informacoes', 7)]], {}), 13: ('wagtail.blocks.ListBlock', (12,), {}), 14: ('wagtail.blocks.StructBlock', [[('titulo_grupo', 10), ('list_style', 3), ('mostrar_linha_separadora', 8), ('contatos', 13)]], {}), 15: ('wagtail.blocks.StreamBlock', [[('contato_simples', 9), ('grupo_contatos', 14)]], {'label': 'Itens de Contato', 'use_json_field': True}), 16: ('wagtail.blocks.StructBlock', [[('section_title', 0), ('title_size', 1), ('itens_contato', 15)]], {})}, verbose_name='Corpo da Página'),
        ),
    ]
