# Generated by Django 5.1.13 on 2025-10-24 17:43

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0009_alter_contatospage_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contatospage',
            name='body',
        ),
        migrations.RemoveField(
            model_name='contatospage',
            name='titulo',
        ),
        migrations.AddField(
            model_name='contatospage',
            name='coluna_1',
            field=wagtail.fields.StreamField([('contatos_section', 11)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Título da Seção', 'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('small', 'Pequeno'), ('medium', 'Médio'), ('large', 'Grande')], 'label': 'Tamanho do Título'}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('none', 'Sem marcador'), ('dot', 'Ponto •'), ('diamond', 'Diamante ♦'), ('triangle', 'Triângulo ►'), ('chevron', 'Ponta de Flecha ›'), ('black_diamond', 'Diamante Negro ◆')], 'label': 'Estilo da lista da seção'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Título (Ex: Presidência)', 'required': False}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('phone', 'Telefone'), ('email', 'E-mail'), ('whatsapp', 'WhatsApp'), ('text', 'Outro (Texto)')], 'label': 'Tipo de Contato'}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Informação', 'required': True}), 6: ('wagtail.blocks.StructBlock', [[('tipo', 4), ('info', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {'label': 'Informações de Contato'}), 8: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'label': 'Mostrar linha separadora após este grupo', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('titulo', 3), ('informacoes', 7), ('mostrar_linha_separadora', 8)]], {}), 10: ('wagtail.blocks.StreamBlock', [[('contato_simples', 9)]], {'label': 'Itens de Contato', 'use_json_field': True}), 11: ('wagtail.blocks.StructBlock', [[('section_title', 0), ('title_size', 1), ('list_style', 2), ('itens_contato', 10)]], {})}, verbose_name='Coluna 1'),
        ),
        migrations.AddField(
            model_name='contatospage',
            name='coluna_2',
            field=wagtail.fields.StreamField([('contatos_section', 11)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Título da Seção', 'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('small', 'Pequeno'), ('medium', 'Médio'), ('large', 'Grande')], 'label': 'Tamanho do Título'}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('none', 'Sem marcador'), ('dot', 'Ponto •'), ('diamond', 'Diamante ♦'), ('triangle', 'Triângulo ►'), ('chevron', 'Ponta de Flecha ›'), ('black_diamond', 'Diamante Negro ◆')], 'label': 'Estilo da lista da seção'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Título (Ex: Presidência)', 'required': False}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('phone', 'Telefone'), ('email', 'E-mail'), ('whatsapp', 'WhatsApp'), ('text', 'Outro (Texto)')], 'label': 'Tipo de Contato'}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Informação', 'required': True}), 6: ('wagtail.blocks.StructBlock', [[('tipo', 4), ('info', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {'label': 'Informações de Contato'}), 8: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'label': 'Mostrar linha separadora após este grupo', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('titulo', 3), ('informacoes', 7), ('mostrar_linha_separadora', 8)]], {}), 10: ('wagtail.blocks.StreamBlock', [[('contato_simples', 9)]], {'label': 'Itens de Contato', 'use_json_field': True}), 11: ('wagtail.blocks.StructBlock', [[('section_title', 0), ('title_size', 1), ('list_style', 2), ('itens_contato', 10)]], {})}, verbose_name='Coluna 2'),
        ),
    ]
