# Generated by Django 5.1.14 on 2025-11-24 19:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTerapia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Terapia')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('cor', models.CharField(default='#3498db', help_text='Cor para representação visual (hex). Ex: #3498db', max_length=7, verbose_name='Cor')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Tipo de Terapia',
                'verbose_name_plural': 'Tipos de Terapias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Crianca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, verbose_name='Sexo')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='criancas/fotos/', verbose_name='Foto de Perfil')),
                ('diagnostico_tea', models.BooleanField(default=False, help_text='Indica se a criança já possui diagnóstico de TEA', verbose_name='Diagnóstico de TEA')),
                ('data_diagnostico', models.DateField(blank=True, null=True, verbose_name='Data do Diagnóstico')),
                ('observacoes_gerais', models.TextField(blank=True, help_text='Informações relevantes sobre a criança', verbose_name='Observações Gerais')),
                ('ativo', models.BooleanField(default=True, help_text='Perfil ativo para registro', verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criancas', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Criança',
                'verbose_name_plural': 'Crianças',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='RegistroDiario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data do Registro')),
                ('humor_geral', models.CharField(choices=[('muito_feliz', '😄 Muito Feliz'), ('feliz', '🙂 Feliz'), ('neutro', '😐 Neutro'), ('triste', '😢 Triste'), ('irritado', '😠 Irritado')], max_length=20, verbose_name='Humor Geral do Dia')),
                ('horas_sono', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='Horas de Sono')),
                ('qualidade_sono', models.CharField(blank=True, choices=[('excelente', 'Excelente'), ('boa', 'Boa'), ('regular', 'Regular'), ('ruim', 'Ruim')], max_length=20, null=True, verbose_name='Qualidade do Sono')),
                ('alimentacao_adequada', models.BooleanField(default=True, help_text='A criança se alimentou adequadamente?', verbose_name='Alimentação Adequada')),
                ('observacoes_alimentacao', models.TextField(blank=True, verbose_name='Observações sobre Alimentação')),
                ('iniciou_comunicacao', models.IntegerField(default=0, help_text='Número de vezes que iniciou comunicação espontânea', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Iniciativas de Comunicação')),
                ('palavras_novas', models.TextField(blank=True, help_text='Registre palavras ou frases novas usadas hoje', verbose_name='Palavras ou Frases Novas')),
                ('episodios_crise', models.IntegerField(default=0, help_text='Número de crises ou birras', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Episódios de Crise')),
                ('descricao_crises', models.TextField(blank=True, help_text='Contexto e gatilhos das crises', verbose_name='Descrição das Crises')),
                ('comportamentos_repetitivos', models.BooleanField(default=False, verbose_name='Comportamentos Repetitivos Observados')),
                ('descricao_comportamentos', models.TextField(blank=True, verbose_name='Descrição dos Comportamentos')),
                ('interacao_outras_criancas', models.BooleanField(default=False, verbose_name='Interagiu com Outras Crianças')),
                ('contato_visual', models.CharField(blank=True, choices=[('frequente', 'Frequente'), ('ocasional', 'Ocasional'), ('raro', 'Raro'), ('ausente', 'Ausente')], max_length=20, null=True, verbose_name='Contato Visual')),
                ('atividades_realizadas', models.TextField(blank=True, help_text='Brincadeiras, terapias, passeios, etc.', verbose_name='Atividades Realizadas')),
                ('conquistas_dia', models.TextField(blank=True, help_text='Marcos ou progressos observados', verbose_name='Conquistas do Dia')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações Gerais')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado Por')),
                ('crianca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_diarios', to='painel_diario.crianca', verbose_name='Criança')),
            ],
            options={
                'verbose_name': 'Registro Diário',
                'verbose_name_plural': 'Registros Diários',
                'ordering': ['-data'],
                'unique_together': {('crianca', 'data')},
            },
        ),
        migrations.CreateModel(
            name='MidiaRegistroDiario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('foto', 'Foto'), ('video', 'Vídeo'), ('audio', 'Áudio')], max_length=10, verbose_name='Tipo de Mídia')),
                ('arquivo', models.FileField(upload_to='registros_diarios/midias/%Y/%m/', verbose_name='Arquivo')),
                ('descricao', models.CharField(blank=True, help_text='Breve descrição do que está sendo registrado', max_length=500, verbose_name='Descrição')),
                ('duracao_segundos', models.IntegerField(blank=True, help_text='Para vídeos e áudios', null=True, verbose_name='Duração (segundos)')),
                ('analisado_ia', models.BooleanField(default=False, verbose_name='Analisado por IA')),
                ('resultado_analise', models.JSONField(blank=True, help_text='Resultado da análise de IA da mídia', null=True, verbose_name='Resultado da Análise')),
                ('enviado_em', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midias', to='painel_diario.registrodiario', verbose_name='Registro Diário')),
            ],
            options={
                'verbose_name': 'Mídia do Registro',
                'verbose_name_plural': 'Mídias dos Registros',
                'ordering': ['-enviado_em'],
            },
        ),
        migrations.CreateModel(
            name='SessaoTerapia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profissional_nome', models.CharField(max_length=200, verbose_name='Nome do Profissional')),
                ('data_hora', models.DateTimeField(verbose_name='Data e Hora da Sessão')),
                ('duracao_minutos', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Duração (minutos)')),
                ('presenca', models.CharField(choices=[('presente', 'Presente'), ('ausente', 'Ausente'), ('cancelada', 'Cancelada')], default='presente', max_length=20, verbose_name='Presença')),
                ('objetivos_sessao', models.TextField(blank=True, verbose_name='Objetivos da Sessão')),
                ('atividades_realizadas', models.TextField(blank=True, verbose_name='Atividades Realizadas')),
                ('progressos_observados', models.TextField(blank=True, verbose_name='Progressos Observados')),
                ('dificuldades_encontradas', models.TextField(blank=True, verbose_name='Dificuldades Encontradas')),
                ('observacoes_profissional', models.TextField(blank=True, verbose_name='Observações do Profissional')),
                ('observacoes_responsavel', models.TextField(blank=True, verbose_name='Observações do Responsável')),
                ('avaliacao_geral', models.IntegerField(blank=True, help_text='1=Muito difícil, 5=Excelente progresso', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Avaliação Geral (1-5)')),
                ('engajamento_crianca', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Engajamento da Criança (1-5)')),
                ('proxima_sessao', models.DateTimeField(blank=True, null=True, verbose_name='Próxima Sessão Agendada')),
                ('tarefas_casa', models.TextField(blank=True, help_text='Atividades para o responsável realizar em casa', verbose_name='Tarefas para Casa')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessoes_terapia_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Registrado Por')),
                ('crianca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes_terapia', to='painel_diario.crianca', verbose_name='Criança')),
                ('tipo_terapia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessoes', to='painel_diario.tipoterapia', verbose_name='Tipo de Terapia')),
            ],
            options={
                'verbose_name': 'Sessão de Terapia',
                'verbose_name_plural': 'Sessões de Terapia',
                'ordering': ['-data_hora'],
            },
        ),
    ]
